'use client';

import React, { useState, useEffect, useRef } from 'react';
import { 
  GitBranch, 
  Terminal as TermIcon, 
  Play, 
  Pause, 
  ChevronDown, 
  ChevronUp, 
  AlertCircle, 
  Clock,
  Coins,
  Cpu
} from 'lucide-react';
import DashboardLayout from '../../components/DashboardLayout';
import { apiService } from '../../lib/api';
import { MockSchedulerDecision } from '../../lib/mockData';
import { useLanguage } from '../../context/LanguageContext';

export default function SchedulerDecisionsPage() {
  const { language, t } = useLanguage();
  const [expandedId, setExpandedId] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  // Live simulation feed state
  const [isSimulating, setIsSimulating] = useState(true);
  const [simulatedDecisions, setSimulatedDecisions] = useState<MockSchedulerDecision[]>([]);
  const simulatedCountRef = useRef(0);

  useEffect(() => {
    async function loadDecisions() {
      setLoading(true);
      try {
        const fetched = await apiService.listSchedulerDecisions();
        setSimulatedDecisions(fetched);
      } catch (err) {
        console.error('Failed to load scheduler decisions', err);
      } finally {
        setLoading(false);
      }
    }
    loadDecisions();
  }, []);

  // Real-time decision flow simulation
  useEffect(() => {
    if (!isSimulating || loading) return;

    const interval = setInterval(() => {
      simulatedCountRef.current += 1;
      const count = simulatedCountRef.current;
      
      const newMock: MockSchedulerDecision = {
        created_at: new Date().toISOString(),
        request_id: `req_simulated_${count}_${Math.floor(Math.random()*10000)}`,
        model: Math.random() > 0.4 ? 'gpt-4o-mini' : 'claude-3-5-sonnet',
        source_endpoint: Math.random() > 0.5 ? '/v1/chat/completions' : '/v1/messages',
        candidate_count: 2,
        selected_account_id: Math.random() > 0.5 ? 'acc-01' : 'acc-02',
        selected_account_name: Math.random() > 0.5 ? 'OpenAI Main Pool #1' : 'Anthropic Corporate Pool',
        rejected_count: 1,
        rejected_reasons: [
          { 
            account: 'acc-03 (Gemini Public)', 
            reason: language === 'en' 
              ? 'Lease target exceeded SLA threshold (>300ms)' 
              : '租约目标响应超出 SLA 阈值范围 (>300ms)' 
          }
        ],
        scores: [
          { 
            account: 'OpenAI Pool #1', 
            score: parseFloat((0.85 + Math.random()*0.14).toFixed(2)), 
            latency: parseFloat((0.8 + Math.random()*0.19).toFixed(2)), 
            cost: parseFloat((0.85 + Math.random()*0.1).toFixed(2)), 
            quota: parseFloat((0.9 + Math.random()*0.09).toFixed(2)) 
          },
          { 
            account: 'Anthropic Corp', 
            score: parseFloat((0.82 + Math.random()*0.16).toFixed(2)), 
            latency: parseFloat((0.8 + Math.random()*0.18).toFixed(2)), 
            cost: parseFloat((0.9 + Math.random()*0.08).toFixed(2)), 
            quota: parseFloat((0.85 + Math.random()*0.14).toFixed(2)) 
          }
        ],
        warnings: [],
        logs: language === 'en' ? [
          `[Scheduler] Evaluating lease request for tenant ID tenant-sim-${count}`,
          `[Scheduler] Resolved endpoints capability matrix successfully`,
          `[Scheduler] Selecting best candidate under "balanced" strategy...`,
          `[Scheduler] Confirmed target lease lease-sim-${count} deployed`
        ] : [
          `[调度程序] 正在评估租户 ID 为 tenant-sim-${count} 的访问通道租约请求`,
          `[调度程序] 成功解析上游端点能力对应矩阵关系表`,
          `[调度程序] 正在基于 "均衡平衡" 调度策略筛选最优服务商候选...`,
          `[调度程序] 已确认将访问权授权给激活租约通道 lease-sim-${count}`
        ]
      };

      setSimulatedDecisions(prev => [newMock, ...prev.slice(0, 14)]);
    }, 4500);

    return () => clearInterval(interval);
  }, [isSimulating, loading, language]);

  const toggleExpand = (id: string) => {
    setExpandedId(prev => prev === id ? null : id);
  };

  // Localized values
  const textTitle = language === 'en' ? 'Scheduler Decisions Feed' : '调度调度决策流';
  const textDesc = language === 'en' 
    ? 'Audit lease contracts, scoring distributions, and failover evidence generated by our dynamic router.' 
    : '审核由我们的大模型自适应调度引擎生成的访问通道租约合同、评分分布以及故障转移排除证据。';
  const textDecisionsCount = language === 'en' ? 'FAILOVER / EXCLUDED CANDIDATES' : '故障转移 / 被排除候选上游';

  return (
    <DashboardLayout allowedRole="admin">
      <div className="space-y-8 animate-bloom">
        
        {/* Header Block (rounded-2xl) */}
        <div className="bg-srapi-card border border-srapi-border rounded-2xl p-6 flex flex-col sm:flex-row sm:items-center justify-between gap-6 tactile-card">
          <div className="space-y-1">
            <h3 className="font-serif font-medium text-lg tracking-tight">{textTitle}</h3>
            <p className="text-xs text-srapi-text-secondary font-sans leading-relaxed">{textDesc}</p>
          </div>

          <button
            onClick={() => setIsSimulating(!isSimulating)}
            className={`px-5 py-3.5 border rounded-full text-xs font-mono font-bold tracking-wider uppercase transition-all active:scale-[0.96] flex items-center gap-2 cursor-pointer ${
              isSimulating 
                ? 'border-green-500/20 text-green-700 bg-green-500/10 hover:bg-green-500/20' 
                : 'border-srapi-border text-srapi-text-secondary hover:bg-srapi-card-muted'
            }`}
          >
            {isSimulating ? <Play size={12} className="animate-pulse" /> : <Pause size={12} />}
            {isSimulating ? t('streaming') : t('paused')}
          </button>
        </div>

        {/* Decisions Feed Logs */}
        {loading ? (
          <div className="py-12 text-center font-mono">
            <div className="w-6 h-6 border-t-2 border-srapi-primary rounded-full animate-spin mx-auto mb-3"></div>
            <p className="text-xs text-srapi-text-secondary">{t('accessingLogs')}</p>
          </div>
        ) : (
          <div className="space-y-6">
            {simulatedDecisions.map((dec) => {
              const isExpanded = expandedId === dec.request_id;
              
              return (
                <div 
                  key={dec.request_id} 
                  className={`bg-srapi-card border border-srapi-border rounded-3xl transition-all overflow-hidden tactile-card ${
                    isExpanded ? 'ring-1 ring-srapi-primary border-srapi-primary/50 shadow-lg' : 'hover:bg-srapi-card-muted/10'
                  }`}
                >
                  
                  {/* Top Summary Banner */}
                  <div 
                    onClick={() => toggleExpand(dec.request_id)}
                    className="p-5 md:p-6 flex flex-col md:flex-row md:items-center justify-between gap-4 cursor-pointer select-none"
                  >
                    <div className="flex flex-wrap items-center gap-3.5">
                      <div className="p-2 bg-srapi-card-muted border border-srapi-border rounded-xl text-srapi-primary">
                        <GitBranch size={16} />
                      </div>
                      
                      <div className="space-y-1">
                        <div className="flex items-center gap-2.5">
                          <code className="text-xs font-bold text-srapi-text-primary select-all">
                            {dec.request_id}
                          </code>
                          <span className="px-2 py-0.5 bg-srapi-card-muted border border-srapi-border rounded text-[9px] font-bold text-srapi-text-secondary font-mono">
                            {dec.model}
                          </span>
                        </div>
                        <div className="text-[10px] font-mono text-srapi-text-secondary flex items-center gap-1.5 font-bold">
                          <span>{dec.source_endpoint}</span>
                          <span>•</span>
                          <span>{new Date(dec.created_at).toLocaleTimeString()}</span>
                        </div>
                      </div>
                    </div>

                    <div className="flex items-center gap-4 text-xs font-mono">
                      <div className="text-right hidden md:block space-y-0.5">
                        <span className="text-[9px] text-srapi-text-secondary block font-bold tracking-wider">{t('leasedUpstream')}</span>
                        <span className="font-bold text-srapi-text-primary font-serif italic">{dec.selected_account_name}</span>
                      </div>

                      <div className="flex items-center gap-2.5">
                        <span className="text-[10px] font-bold border border-green-500/20 text-green-700 bg-green-500/10 px-2.5 py-0.5 rounded-full uppercase">
                          {t('routed')}
                        </span>
                        {isExpanded ? <ChevronUp size={16} /> : <ChevronDown size={16} />}
                      </div>
                    </div>
                  </div>

                  {/* Expanded Scoring Breakdown and Logs */}
                  {isExpanded && (
                    <div className="border-t border-srapi-border p-6 space-y-6 bg-srapi-card-muted/10 animate-bloom">
                      
                      {/* Grid sections */}
                      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 md:gap-8">
                        
                        {/* Candidates Score Breakdown */}
                        <div className="space-y-4">
                          <span className="text-[10px] uppercase font-mono tracking-widest text-srapi-text-secondary font-bold block border-b border-srapi-border pb-1">
                            {t('candidatesScores')}
                          </span>

                          <div className="space-y-4.5">
                            {dec.scores.map((cand, idx) => (
                              <div key={idx} className="space-y-2">
                                <div className="flex justify-between text-[11px] font-mono">
                                  <span className="font-bold text-srapi-text-primary font-serif">{cand.account}</span>
                                  <span className="font-bold text-srapi-primary">{language === 'en' ? 'Overall' : '综合得分'}: {cand.score}</span>
                                </div>

                                {/* Score matrix bars */}
                                <div className="space-y-1.5 text-[9px] font-mono text-srapi-text-secondary bg-srapi-card p-3 border border-srapi-border rounded-xl">
                                  {/* Latency */}
                                  <div className="flex items-center gap-3">
                                    <span className="w-20 flex items-center gap-0.5"><Clock size={10} /> {t('latencyMetric')}</span>
                                    <div className="flex-grow h-[1px] bg-srapi-border relative">
                                      <div className="absolute h-2 w-[1px] bg-green-700 -top-[3px]" style={{ left: `${cand.latency * 100}%` }}></div>
                                    </div>
                                    <span className="w-6 text-right">{(cand.latency * 10).toFixed(1)}</span>
                                  </div>

                                  {/* Cost */}
                                  <div className="flex items-center gap-3">
                                    <span className="w-20 flex items-center gap-0.5"><Coins size={10} /> {t('costMetric')}</span>
                                    <div className="flex-grow h-[1px] bg-srapi-border relative">
                                      <div className="absolute h-2 w-[1px] bg-srapi-primary -top-[3px]" style={{ left: `${cand.cost * 100}%` }}></div>
                                    </div>
                                    <span className="w-6 text-right">{(cand.cost * 10).toFixed(1)}</span>
                                  </div>

                                  {/* Quota */}
                                  <div className="flex items-center gap-3">
                                    <span className="w-20 flex items-center gap-0.5"><Cpu size={10} /> {t('quotaMetric')}</span>
                                    <div className="flex-grow h-[1px] bg-srapi-border relative">
                                      <div className="absolute h-2 w-[1px] bg-blue-500 -top-[3px]" style={{ left: `${cand.quota * 100}%` }}></div>
                                    </div>
                                    <span className="w-6 text-right">{(cand.quota * 10).toFixed(1)}</span>
                                  </div>
                                </div>
                              </div>
                            ))}
                          </div>
                        </div>

                        {/* Failover and Exclusions */}
                        <div className="space-y-4">
                          <span className="text-[10px] uppercase font-mono tracking-widest text-srapi-text-secondary font-bold block border-b border-srapi-border pb-1">
                            {textDecisionsCount} ({dec.rejected_count})
                          </span>

                          {dec.rejected_reasons.length === 0 ? (
                            <div className="p-5 border border-dashed border-srapi-border rounded-2xl text-center text-xs text-srapi-text-secondary font-mono">
                              {t('noFailoverDesc')}
                            </div>
                          ) : (
                            <div className="space-y-3 text-[10px] font-mono">
                              {dec.rejected_reasons.map((re, idx) => (
                                <div key={idx} className="p-4 border border-srapi-primary/20 bg-srapi-primary/5 rounded-2xl text-srapi-primary flex items-start gap-2.5">
                                  <AlertCircle size={14} className="mt-0.5 flex-shrink-0" />
                                  <div className="space-y-0.5">
                                    <p className="font-bold">{re.account}</p>
                                    <p className="text-[9px] text-srapi-text-secondary font-sans leading-relaxed">{re.reason}</p>
                                  </div>
                                </div>
                              ))}
                            </div>
                          )}
                        </div>

                      </div>

                      {/* Raw reasoning logs console */}
                      <div className="space-y-2.5">
                        <span className="text-[10px] uppercase font-mono tracking-widest text-srapi-text-secondary font-bold flex items-center gap-1.5">
                          <TermIcon size={12} />
                          {t('reasoningLogs')}
                        </span>

                        <pre className="p-4 bg-srapi-card border border-srapi-border rounded-2xl text-[10px] font-mono text-srapi-text-primary leading-relaxed space-y-1.5 overflow-x-auto select-all shadow-inner">
                          {dec.logs.map((logLine, idx) => (
                            <div key={idx} className="truncate">
                              {logLine}
                            </div>
                          ))}
                        </pre>
                      </div>

                    </div>
                  )}

                </div>
              );
            })}
          </div>
        )}

      </div>
    </DashboardLayout>
  );
}
