// Package migrations embeds SRapi's versioned PostgreSQL migrations so that a
// compiled binary can apply them at startup without shipping the .sql files
// alongside it.
//
// Ent remains the schema source of truth; these files are generated by
// `make migration-diff` and verified against the Ent schema by
// `make migration-check`. The embed path is relative to this file, which is the
// reason the applier lives in internal/platform/db while the embed lives here:
// go:embed cannot reference parent directories.
package migrations

import (
	"embed"
	"io/fs"
)

//go:embed postgres/up/*.sql
var upFS embed.FS

// UpFS returns a filesystem rooted at the directory that contains the
// versioned up migrations (i.e. the *.sql files are at the root of the returned
// fs.FS). Callers should treat the returned filesystem as read-only.
func UpFS() fs.FS {
	sub, err := fs.Sub(upFS, "postgres/up")
	if err != nil {
		// fs.Sub only fails on an invalid path; the embed pattern above is a
		// compile-time constant, so this is unreachable in practice.
		panic(err)
	}
	return sub
}
