// Code generated by ent, DO NOT EDIT.

package accountgroup

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldDescription, v))
}

// StrategyHint applies equality check predicate on the "strategy_hint" field. It's identical to StrategyHintEQ.
func StrategyHint(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldStrategyHint, v))
}

// RateMultiplier applies equality check predicate on the "rate_multiplier" field. It's identical to RateMultiplierEQ.
func RateMultiplier(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldRateMultiplier, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContainsFold(FieldName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContainsFold(FieldDescription, v))
}

// ProviderScopeJSONIsNil applies the IsNil predicate on the "provider_scope_json" field.
func ProviderScopeJSONIsNil() predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIsNull(FieldProviderScopeJSON))
}

// ProviderScopeJSONNotNil applies the NotNil predicate on the "provider_scope_json" field.
func ProviderScopeJSONNotNil() predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotNull(FieldProviderScopeJSON))
}

// ModelScopeJSONIsNil applies the IsNil predicate on the "model_scope_json" field.
func ModelScopeJSONIsNil() predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIsNull(FieldModelScopeJSON))
}

// ModelScopeJSONNotNil applies the NotNil predicate on the "model_scope_json" field.
func ModelScopeJSONNotNil() predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotNull(FieldModelScopeJSON))
}

// StrategyHintEQ applies the EQ predicate on the "strategy_hint" field.
func StrategyHintEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldStrategyHint, v))
}

// StrategyHintNEQ applies the NEQ predicate on the "strategy_hint" field.
func StrategyHintNEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNEQ(FieldStrategyHint, v))
}

// StrategyHintIn applies the In predicate on the "strategy_hint" field.
func StrategyHintIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIn(FieldStrategyHint, vs...))
}

// StrategyHintNotIn applies the NotIn predicate on the "strategy_hint" field.
func StrategyHintNotIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotIn(FieldStrategyHint, vs...))
}

// StrategyHintGT applies the GT predicate on the "strategy_hint" field.
func StrategyHintGT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGT(FieldStrategyHint, v))
}

// StrategyHintGTE applies the GTE predicate on the "strategy_hint" field.
func StrategyHintGTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGTE(FieldStrategyHint, v))
}

// StrategyHintLT applies the LT predicate on the "strategy_hint" field.
func StrategyHintLT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLT(FieldStrategyHint, v))
}

// StrategyHintLTE applies the LTE predicate on the "strategy_hint" field.
func StrategyHintLTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLTE(FieldStrategyHint, v))
}

// StrategyHintContains applies the Contains predicate on the "strategy_hint" field.
func StrategyHintContains(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContains(FieldStrategyHint, v))
}

// StrategyHintHasPrefix applies the HasPrefix predicate on the "strategy_hint" field.
func StrategyHintHasPrefix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasPrefix(FieldStrategyHint, v))
}

// StrategyHintHasSuffix applies the HasSuffix predicate on the "strategy_hint" field.
func StrategyHintHasSuffix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasSuffix(FieldStrategyHint, v))
}

// StrategyHintEqualFold applies the EqualFold predicate on the "strategy_hint" field.
func StrategyHintEqualFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEqualFold(FieldStrategyHint, v))
}

// StrategyHintContainsFold applies the ContainsFold predicate on the "strategy_hint" field.
func StrategyHintContainsFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContainsFold(FieldStrategyHint, v))
}

// RateMultiplierEQ applies the EQ predicate on the "rate_multiplier" field.
func RateMultiplierEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldRateMultiplier, v))
}

// RateMultiplierNEQ applies the NEQ predicate on the "rate_multiplier" field.
func RateMultiplierNEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNEQ(FieldRateMultiplier, v))
}

// RateMultiplierIn applies the In predicate on the "rate_multiplier" field.
func RateMultiplierIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIn(FieldRateMultiplier, vs...))
}

// RateMultiplierNotIn applies the NotIn predicate on the "rate_multiplier" field.
func RateMultiplierNotIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotIn(FieldRateMultiplier, vs...))
}

// RateMultiplierGT applies the GT predicate on the "rate_multiplier" field.
func RateMultiplierGT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGT(FieldRateMultiplier, v))
}

// RateMultiplierGTE applies the GTE predicate on the "rate_multiplier" field.
func RateMultiplierGTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGTE(FieldRateMultiplier, v))
}

// RateMultiplierLT applies the LT predicate on the "rate_multiplier" field.
func RateMultiplierLT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLT(FieldRateMultiplier, v))
}

// RateMultiplierLTE applies the LTE predicate on the "rate_multiplier" field.
func RateMultiplierLTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLTE(FieldRateMultiplier, v))
}

// RateMultiplierContains applies the Contains predicate on the "rate_multiplier" field.
func RateMultiplierContains(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContains(FieldRateMultiplier, v))
}

// RateMultiplierHasPrefix applies the HasPrefix predicate on the "rate_multiplier" field.
func RateMultiplierHasPrefix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasPrefix(FieldRateMultiplier, v))
}

// RateMultiplierHasSuffix applies the HasSuffix predicate on the "rate_multiplier" field.
func RateMultiplierHasSuffix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasSuffix(FieldRateMultiplier, v))
}

// RateMultiplierEqualFold applies the EqualFold predicate on the "rate_multiplier" field.
func RateMultiplierEqualFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEqualFold(FieldRateMultiplier, v))
}

// RateMultiplierContainsFold applies the ContainsFold predicate on the "rate_multiplier" field.
func RateMultiplierContainsFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContainsFold(FieldRateMultiplier, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.AccountGroup {
	return predicate.AccountGroup(sql.FieldContainsFold(FieldStatus, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountGroup) predicate.AccountGroup {
	return predicate.AccountGroup(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountGroup) predicate.AccountGroup {
	return predicate.AccountGroup(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountGroup) predicate.AccountGroup {
	return predicate.AccountGroup(sql.NotPredicates(p))
}
