// Code generated by ent, DO NOT EDIT.

package qualityevalsample

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the qualityevalsample type in the database.
	Label = "quality_eval_sample"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldFeedbackID holds the string denoting the feedback_id field in the database.
	FieldFeedbackID = "feedback_id"
	// FieldRequestID holds the string denoting the request_id field in the database.
	FieldRequestID = "request_id"
	// FieldDecisionID holds the string denoting the decision_id field in the database.
	FieldDecisionID = "decision_id"
	// FieldAttemptNo holds the string denoting the attempt_no field in the database.
	FieldAttemptNo = "attempt_no"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldProviderID holds the string denoting the provider_id field in the database.
	FieldProviderID = "provider_id"
	// FieldModel holds the string denoting the model field in the database.
	FieldModel = "model"
	// FieldSourceEndpoint holds the string denoting the source_endpoint field in the database.
	FieldSourceEndpoint = "source_endpoint"
	// FieldSampleRequestHash holds the string denoting the sample_request_hash field in the database.
	FieldSampleRequestHash = "sample_request_hash"
	// FieldSamplePayloadCiphertext holds the string denoting the sample_payload_ciphertext field in the database.
	FieldSamplePayloadCiphertext = "sample_payload_ciphertext"
	// FieldPayloadVersion holds the string denoting the payload_version field in the database.
	FieldPayloadVersion = "payload_version"
	// FieldCapturedAt holds the string denoting the captured_at field in the database.
	FieldCapturedAt = "captured_at"
	// Table holds the table name of the qualityevalsample in the database.
	Table = "quality_eval_samples"
)

// Columns holds all SQL columns for qualityevalsample fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldFeedbackID,
	FieldRequestID,
	FieldDecisionID,
	FieldAttemptNo,
	FieldAccountID,
	FieldProviderID,
	FieldModel,
	FieldSourceEndpoint,
	FieldSampleRequestHash,
	FieldSamplePayloadCiphertext,
	FieldPayloadVersion,
	FieldCapturedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RequestIDValidator is a validator for the "request_id" field. It is called by the builders before save.
	RequestIDValidator func(string) error
	// DefaultAttemptNo holds the default value on creation for the "attempt_no" field.
	DefaultAttemptNo int
	// DefaultModel holds the default value on creation for the "model" field.
	DefaultModel string
	// DefaultSourceEndpoint holds the default value on creation for the "source_endpoint" field.
	DefaultSourceEndpoint string
	// SampleRequestHashValidator is a validator for the "sample_request_hash" field. It is called by the builders before save.
	SampleRequestHashValidator func(string) error
	// DefaultPayloadVersion holds the default value on creation for the "payload_version" field.
	DefaultPayloadVersion string
)

// OrderOption defines the ordering options for the QualityEvalSample queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByFeedbackID orders the results by the feedback_id field.
func ByFeedbackID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeedbackID, opts...).ToFunc()
}

// ByRequestID orders the results by the request_id field.
func ByRequestID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestID, opts...).ToFunc()
}

// ByDecisionID orders the results by the decision_id field.
func ByDecisionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecisionID, opts...).ToFunc()
}

// ByAttemptNo orders the results by the attempt_no field.
func ByAttemptNo(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAttemptNo, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByProviderID orders the results by the provider_id field.
func ByProviderID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProviderID, opts...).ToFunc()
}

// ByModel orders the results by the model field.
func ByModel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldModel, opts...).ToFunc()
}

// BySourceEndpoint orders the results by the source_endpoint field.
func BySourceEndpoint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceEndpoint, opts...).ToFunc()
}

// BySampleRequestHash orders the results by the sample_request_hash field.
func BySampleRequestHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSampleRequestHash, opts...).ToFunc()
}

// ByPayloadVersion orders the results by the payload_version field.
func ByPayloadVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPayloadVersion, opts...).ToFunc()
}

// ByCapturedAt orders the results by the captured_at field.
func ByCapturedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCapturedAt, opts...).ToFunc()
}
