// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// APIKeysColumns holds the columns for the "api_keys" table.
	APIKeysColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "prefix", Type: field.TypeString},
		{Name: "hash", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "scopes_json", Type: field.TypeJSON, Nullable: true},
		{Name: "allowed_models_json", Type: field.TypeJSON, Nullable: true},
		{Name: "rpm_limit", Type: field.TypeInt, Nullable: true},
		{Name: "tpm_limit", Type: field.TypeInt, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_used_at", Type: field.TypeTime, Nullable: true},
	}
	// APIKeysTable holds the schema information for the "api_keys" table.
	APIKeysTable = &schema.Table{
		Name:       "api_keys",
		Columns:    APIKeysColumns,
		PrimaryKey: []*schema.Column{APIKeysColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apikey_prefix",
				Unique:  true,
				Columns: []*schema.Column{APIKeysColumns[6]},
			},
			{
				Name:    "apikey_user_id_status",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[4], APIKeysColumns[8]},
			},
			{
				Name:    "apikey_expires_at",
				Unique:  false,
				Columns: []*schema.Column{APIKeysColumns[13]},
			},
		},
	}
	// APIKeyGroupsColumns holds the columns for the "api_key_groups" table.
	APIKeyGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "api_key_id", Type: field.TypeInt},
		{Name: "account_group_id", Type: field.TypeInt},
	}
	// APIKeyGroupsTable holds the schema information for the "api_key_groups" table.
	APIKeyGroupsTable = &schema.Table{
		Name:       "api_key_groups",
		Columns:    APIKeyGroupsColumns,
		PrimaryKey: []*schema.Column{APIKeyGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "apikeygroup_api_key_id_account_group_id",
				Unique:  true,
				Columns: []*schema.Column{APIKeyGroupsColumns[3], APIKeyGroupsColumns[4]},
			},
			{
				Name:    "apikeygroup_account_group_id",
				Unique:  false,
				Columns: []*schema.Column{APIKeyGroupsColumns[4]},
			},
		},
	}
	// AccountGroupsColumns holds the columns for the "account_groups" table.
	AccountGroupsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "provider_scope_json", Type: field.TypeJSON, Nullable: true},
		{Name: "model_scope_json", Type: field.TypeJSON, Nullable: true},
		{Name: "strategy_hint", Type: field.TypeString, Default: "balanced"},
		{Name: "status", Type: field.TypeString, Default: "active"},
	}
	// AccountGroupsTable holds the schema information for the "account_groups" table.
	AccountGroupsTable = &schema.Table{
		Name:       "account_groups",
		Columns:    AccountGroupsColumns,
		PrimaryKey: []*schema.Column{AccountGroupsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accountgroup_name",
				Unique:  true,
				Columns: []*schema.Column{AccountGroupsColumns[3]},
			},
			{
				Name:    "accountgroup_status",
				Unique:  false,
				Columns: []*schema.Column{AccountGroupsColumns[8]},
			},
		},
	}
	// AccountGroupMembersColumns holds the columns for the "account_group_members" table.
	AccountGroupMembersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "account_id", Type: field.TypeInt},
		{Name: "account_group_id", Type: field.TypeInt},
	}
	// AccountGroupMembersTable holds the schema information for the "account_group_members" table.
	AccountGroupMembersTable = &schema.Table{
		Name:       "account_group_members",
		Columns:    AccountGroupMembersColumns,
		PrimaryKey: []*schema.Column{AccountGroupMembersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accountgroupmember_account_id_account_group_id",
				Unique:  true,
				Columns: []*schema.Column{AccountGroupMembersColumns[3], AccountGroupMembersColumns[4]},
			},
			{
				Name:    "accountgroupmember_account_group_id",
				Unique:  false,
				Columns: []*schema.Column{AccountGroupMembersColumns[4]},
			},
		},
	}
	// AccountHealthSnapshotsColumns holds the columns for the "account_health_snapshots" table.
	AccountHealthSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeInt},
		{Name: "provider_id", Type: field.TypeInt},
		{Name: "status", Type: field.TypeString, Default: "healthy"},
		{Name: "success_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "error_rate", Type: field.TypeFloat64, Default: 0},
		{Name: "latency_p50_ms", Type: field.TypeInt, Default: 0},
		{Name: "latency_p95_ms", Type: field.TypeInt, Default: 0},
		{Name: "rate_limit_count", Type: field.TypeInt, Default: 0},
		{Name: "timeout_count", Type: field.TypeInt, Default: 0},
		{Name: "cooldown_until", Type: field.TypeTime, Nullable: true},
		{Name: "circuit_state", Type: field.TypeString, Default: "closed"},
		{Name: "snapshot_at", Type: field.TypeTime},
	}
	// AccountHealthSnapshotsTable holds the schema information for the "account_health_snapshots" table.
	AccountHealthSnapshotsTable = &schema.Table{
		Name:       "account_health_snapshots",
		Columns:    AccountHealthSnapshotsColumns,
		PrimaryKey: []*schema.Column{AccountHealthSnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accounthealthsnapshot_account_id_snapshot_at",
				Unique:  false,
				Columns: []*schema.Column{AccountHealthSnapshotsColumns[1], AccountHealthSnapshotsColumns[12]},
			},
			{
				Name:    "accounthealthsnapshot_provider_id_snapshot_at",
				Unique:  false,
				Columns: []*schema.Column{AccountHealthSnapshotsColumns[2], AccountHealthSnapshotsColumns[12]},
			},
			{
				Name:    "accounthealthsnapshot_status",
				Unique:  false,
				Columns: []*schema.Column{AccountHealthSnapshotsColumns[3]},
			},
		},
	}
	// AccountQuotaSnapshotsColumns holds the columns for the "account_quota_snapshots" table.
	AccountQuotaSnapshotsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeInt},
		{Name: "provider_id", Type: field.TypeInt},
		{Name: "quota_type", Type: field.TypeString},
		{Name: "remaining", Type: field.TypeString, Default: "0"},
		{Name: "used", Type: field.TypeString, Default: "0"},
		{Name: "quota_limit", Type: field.TypeString, Default: "0"},
		{Name: "remaining_ratio", Type: field.TypeFloat64, Default: 0},
		{Name: "reset_at", Type: field.TypeTime, Nullable: true},
		{Name: "snapshot_at", Type: field.TypeTime},
	}
	// AccountQuotaSnapshotsTable holds the schema information for the "account_quota_snapshots" table.
	AccountQuotaSnapshotsTable = &schema.Table{
		Name:       "account_quota_snapshots",
		Columns:    AccountQuotaSnapshotsColumns,
		PrimaryKey: []*schema.Column{AccountQuotaSnapshotsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "accountquotasnapshot_account_id_quota_type_snapshot_at",
				Unique:  false,
				Columns: []*schema.Column{AccountQuotaSnapshotsColumns[1], AccountQuotaSnapshotsColumns[3], AccountQuotaSnapshotsColumns[9]},
			},
			{
				Name:    "accountquotasnapshot_reset_at",
				Unique:  false,
				Columns: []*schema.Column{AccountQuotaSnapshotsColumns[8]},
			},
		},
	}
	// AffiliateLedgersColumns holds the columns for the "affiliate_ledgers" table.
	AffiliateLedgersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "related_user_id", Type: field.TypeInt},
		{Name: "payment_order_id", Type: field.TypeInt, Nullable: true},
		{Name: "subscription_id", Type: field.TypeInt, Nullable: true},
		{Name: "type", Type: field.TypeString},
		{Name: "amount", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "reference_id", Type: field.TypeString},
		{Name: "metadata_json", Type: field.TypeJSON, Nullable: true},
		{Name: "settled_at", Type: field.TypeTime, Nullable: true},
	}
	// AffiliateLedgersTable holds the schema information for the "affiliate_ledgers" table.
	AffiliateLedgersTable = &schema.Table{
		Name:       "affiliate_ledgers",
		Columns:    AffiliateLedgersColumns,
		PrimaryKey: []*schema.Column{AffiliateLedgersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "affiliateledger_reference_id",
				Unique:  true,
				Columns: []*schema.Column{AffiliateLedgersColumns[11]},
			},
			{
				Name:    "affiliateledger_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AffiliateLedgersColumns[3], AffiliateLedgersColumns[1]},
			},
			{
				Name:    "affiliateledger_related_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AffiliateLedgersColumns[4], AffiliateLedgersColumns[1]},
			},
			{
				Name:    "affiliateledger_payment_order_id",
				Unique:  false,
				Columns: []*schema.Column{AffiliateLedgersColumns[5]},
			},
			{
				Name:    "affiliateledger_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{AffiliateLedgersColumns[7], AffiliateLedgersColumns[1]},
			},
		},
	}
	// AffiliateRulesColumns holds the columns for the "affiliate_rules" table.
	AffiliateRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "trigger_type", Type: field.TypeString},
		{Name: "rate", Type: field.TypeString, Default: "0.00000000"},
		{Name: "fixed_amount", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "max_rebate_amount", Type: field.TypeString, Default: "0.00000000"},
		{Name: "valid_from", Type: field.TypeTime, Nullable: true},
		{Name: "valid_to", Type: field.TypeTime, Nullable: true},
		{Name: "metadata_json", Type: field.TypeJSON, Nullable: true},
	}
	// AffiliateRulesTable holds the schema information for the "affiliate_rules" table.
	AffiliateRulesTable = &schema.Table{
		Name:       "affiliate_rules",
		Columns:    AffiliateRulesColumns,
		PrimaryKey: []*schema.Column{AffiliateRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "affiliaterule_trigger_type_currency_status",
				Unique:  false,
				Columns: []*schema.Column{AffiliateRulesColumns[5], AffiliateRulesColumns[8], AffiliateRulesColumns[4]},
			},
			{
				Name:    "affiliaterule_valid_from_valid_to",
				Unique:  false,
				Columns: []*schema.Column{AffiliateRulesColumns[10], AffiliateRulesColumns[11]},
			},
		},
	}
	// AuditLogsColumns holds the columns for the "audit_logs" table.
	AuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "actor_user_id", Type: field.TypeInt, Nullable: true},
		{Name: "action", Type: field.TypeString},
		{Name: "resource_type", Type: field.TypeString},
		{Name: "resource_id", Type: field.TypeString, Default: ""},
		{Name: "before_json", Type: field.TypeJSON, Nullable: true},
		{Name: "after_json", Type: field.TypeJSON, Nullable: true},
		{Name: "ip", Type: field.TypeString, Default: ""},
		{Name: "user_agent", Type: field.TypeString, Default: ""},
		{Name: "trace_id", Type: field.TypeString, Default: ""},
	}
	// AuditLogsTable holds the schema information for the "audit_logs" table.
	AuditLogsTable = &schema.Table{
		Name:       "audit_logs",
		Columns:    AuditLogsColumns,
		PrimaryKey: []*schema.Column{AuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "auditlog_actor_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[3], AuditLogsColumns[1]},
			},
			{
				Name:    "auditlog_resource_type_resource_id",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[5], AuditLogsColumns[6]},
			},
			{
				Name:    "auditlog_action_created_at",
				Unique:  false,
				Columns: []*schema.Column{AuditLogsColumns[4], AuditLogsColumns[1]},
			},
		},
	}
	// BillingLedgersColumns holds the columns for the "billing_ledgers" table.
	BillingLedgersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "type", Type: field.TypeString},
		{Name: "amount", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "balance_before", Type: field.TypeString, Default: "0.00000000"},
		{Name: "balance_after", Type: field.TypeString, Default: "0.00000000"},
		{Name: "reference_type", Type: field.TypeString, Default: ""},
		{Name: "reference_id", Type: field.TypeString, Default: ""},
		{Name: "metadata_json", Type: field.TypeJSON, Nullable: true},
	}
	// BillingLedgersTable holds the schema information for the "billing_ledgers" table.
	BillingLedgersTable = &schema.Table{
		Name:       "billing_ledgers",
		Columns:    BillingLedgersColumns,
		PrimaryKey: []*schema.Column{BillingLedgersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "billingledger_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{BillingLedgersColumns[3], BillingLedgersColumns[1]},
			},
			{
				Name:    "billingledger_reference_type_reference_id",
				Unique:  false,
				Columns: []*schema.Column{BillingLedgersColumns[9], BillingLedgersColumns[10]},
			},
		},
	}
	// CapabilityDefinitionsColumns holds the columns for the "capability_definitions" table.
	CapabilityDefinitionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString},
		{Name: "version", Type: field.TypeString, Default: "v1"},
		{Name: "category", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "stable"},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "schema_json", Type: field.TypeJSON, Nullable: true},
		{Name: "replacement_key", Type: field.TypeString, Nullable: true},
	}
	// CapabilityDefinitionsTable holds the schema information for the "capability_definitions" table.
	CapabilityDefinitionsTable = &schema.Table{
		Name:       "capability_definitions",
		Columns:    CapabilityDefinitionsColumns,
		PrimaryKey: []*schema.Column{CapabilityDefinitionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "capabilitydefinition_key_version",
				Unique:  true,
				Columns: []*schema.Column{CapabilityDefinitionsColumns[3], CapabilityDefinitionsColumns[4]},
			},
			{
				Name:    "capabilitydefinition_category_status",
				Unique:  false,
				Columns: []*schema.Column{CapabilityDefinitionsColumns[5], CapabilityDefinitionsColumns[6]},
			},
		},
	}
	// DomainEventsInboxesColumns holds the columns for the "domain_events_inboxes" table.
	DomainEventsInboxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "event_id", Type: field.TypeString},
		{Name: "consumer_name", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "attempt_count", Type: field.TypeInt, Default: 0},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "processed_at", Type: field.TypeTime, Nullable: true},
	}
	// DomainEventsInboxesTable holds the schema information for the "domain_events_inboxes" table.
	DomainEventsInboxesTable = &schema.Table{
		Name:       "domain_events_inboxes",
		Columns:    DomainEventsInboxesColumns,
		PrimaryKey: []*schema.Column{DomainEventsInboxesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "domaineventsinbox_event_id_consumer_name",
				Unique:  true,
				Columns: []*schema.Column{DomainEventsInboxesColumns[3], DomainEventsInboxesColumns[4]},
			},
			{
				Name:    "domaineventsinbox_consumer_name_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{DomainEventsInboxesColumns[4], DomainEventsInboxesColumns[6], DomainEventsInboxesColumns[1]},
			},
		},
	}
	// DomainEventsOutboxesColumns holds the columns for the "domain_events_outboxes" table.
	DomainEventsOutboxesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "event_id", Type: field.TypeString},
		{Name: "event_type", Type: field.TypeString},
		{Name: "event_version", Type: field.TypeString, Default: "v1"},
		{Name: "producer_module", Type: field.TypeString},
		{Name: "aggregate_type", Type: field.TypeString, Default: ""},
		{Name: "aggregate_id", Type: field.TypeString, Default: ""},
		{Name: "correlation_id", Type: field.TypeString, Default: ""},
		{Name: "causation_id", Type: field.TypeString, Default: ""},
		{Name: "idempotency_key", Type: field.TypeString, Default: ""},
		{Name: "payload_json", Type: field.TypeJSON, Nullable: true},
		{Name: "metadata_json", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "attempt_count", Type: field.TypeInt, Default: 0},
		{Name: "next_retry_at", Type: field.TypeTime, Nullable: true},
		{Name: "last_error", Type: field.TypeString, Nullable: true},
		{Name: "published_at", Type: field.TypeTime, Nullable: true},
	}
	// DomainEventsOutboxesTable holds the schema information for the "domain_events_outboxes" table.
	DomainEventsOutboxesTable = &schema.Table{
		Name:       "domain_events_outboxes",
		Columns:    DomainEventsOutboxesColumns,
		PrimaryKey: []*schema.Column{DomainEventsOutboxesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "domaineventsoutbox_event_id",
				Unique:  true,
				Columns: []*schema.Column{DomainEventsOutboxesColumns[3]},
			},
			{
				Name:    "domaineventsoutbox_producer_module_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{DomainEventsOutboxesColumns[6], DomainEventsOutboxesColumns[11]},
			},
			{
				Name:    "domaineventsoutbox_status_next_retry_at",
				Unique:  false,
				Columns: []*schema.Column{DomainEventsOutboxesColumns[14], DomainEventsOutboxesColumns[16]},
			},
			{
				Name:    "domaineventsoutbox_event_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{DomainEventsOutboxesColumns[4], DomainEventsOutboxesColumns[1]},
			},
			{
				Name:    "domaineventsoutbox_aggregate_type_aggregate_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{DomainEventsOutboxesColumns[7], DomainEventsOutboxesColumns[8], DomainEventsOutboxesColumns[1]},
			},
			{
				Name:    "domaineventsoutbox_correlation_id",
				Unique:  false,
				Columns: []*schema.Column{DomainEventsOutboxesColumns[9]},
			},
		},
	}
	// IdempotencyRecordsColumns holds the columns for the "idempotency_records" table.
	IdempotencyRecordsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "idempotency_key", Type: field.TypeString},
		{Name: "method", Type: field.TypeString},
		{Name: "path", Type: field.TypeString},
		{Name: "request_hash", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "response_snapshot_json", Type: field.TypeJSON, Nullable: true},
		{Name: "locked_until", Type: field.TypeTime, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime},
	}
	// IdempotencyRecordsTable holds the schema information for the "idempotency_records" table.
	IdempotencyRecordsTable = &schema.Table{
		Name:       "idempotency_records",
		Columns:    IdempotencyRecordsColumns,
		PrimaryKey: []*schema.Column{IdempotencyRecordsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "idempotencyrecord_idempotency_key_method_path",
				Unique:  true,
				Columns: []*schema.Column{IdempotencyRecordsColumns[3], IdempotencyRecordsColumns[4], IdempotencyRecordsColumns[5]},
			},
			{
				Name:    "idempotencyrecord_expires_at",
				Unique:  false,
				Columns: []*schema.Column{IdempotencyRecordsColumns[10]},
			},
		},
	}
	// InviteCodesColumns holds the columns for the "invite_codes" table.
	InviteCodesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "code", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
	}
	// InviteCodesTable holds the schema information for the "invite_codes" table.
	InviteCodesTable = &schema.Table{
		Name:       "invite_codes",
		Columns:    InviteCodesColumns,
		PrimaryKey: []*schema.Column{InviteCodesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "invitecode_code",
				Unique:  true,
				Columns: []*schema.Column{InviteCodesColumns[4]},
			},
			{
				Name:    "invitecode_user_id_status",
				Unique:  false,
				Columns: []*schema.Column{InviteCodesColumns[3], InviteCodesColumns[5]},
			},
			{
				Name:    "invitecode_expires_at",
				Unique:  false,
				Columns: []*schema.Column{InviteCodesColumns[6]},
			},
		},
	}
	// InviteRelationshipsColumns holds the columns for the "invite_relationships" table.
	InviteRelationshipsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "inviter_user_id", Type: field.TypeInt},
		{Name: "invitee_user_id", Type: field.TypeInt},
		{Name: "invite_code_id", Type: field.TypeInt},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "first_paid_at", Type: field.TypeTime, Nullable: true},
	}
	// InviteRelationshipsTable holds the schema information for the "invite_relationships" table.
	InviteRelationshipsTable = &schema.Table{
		Name:       "invite_relationships",
		Columns:    InviteRelationshipsColumns,
		PrimaryKey: []*schema.Column{InviteRelationshipsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "inviterelationship_invitee_user_id",
				Unique:  true,
				Columns: []*schema.Column{InviteRelationshipsColumns[4]},
			},
			{
				Name:    "inviterelationship_inviter_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{InviteRelationshipsColumns[3], InviteRelationshipsColumns[1]},
			},
			{
				Name:    "inviterelationship_invite_code_id",
				Unique:  false,
				Columns: []*schema.Column{InviteRelationshipsColumns[5]},
			},
			{
				Name:    "inviterelationship_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{InviteRelationshipsColumns[6], InviteRelationshipsColumns[1]},
			},
		},
	}
	// ModelAliasColumns holds the columns for the "model_alias" table.
	ModelAliasColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "alias", Type: field.TypeString},
		{Name: "model_id", Type: field.TypeInt},
		{Name: "strategy_hint", Type: field.TypeString, Default: ""},
		{Name: "fallback_models_json", Type: field.TypeJSON, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
	}
	// ModelAliasTable holds the schema information for the "model_alias" table.
	ModelAliasTable = &schema.Table{
		Name:       "model_alias",
		Columns:    ModelAliasColumns,
		PrimaryKey: []*schema.Column{ModelAliasColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "modelalias_alias",
				Unique:  true,
				Columns: []*schema.Column{ModelAliasColumns[3]},
			},
			{
				Name:    "modelalias_model_id",
				Unique:  false,
				Columns: []*schema.Column{ModelAliasColumns[4]},
			},
		},
	}
	// ModelProviderMappingsColumns holds the columns for the "model_provider_mappings" table.
	ModelProviderMappingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "model_id", Type: field.TypeInt},
		{Name: "provider_id", Type: field.TypeInt},
		{Name: "upstream_model_name", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "capability_override_json", Type: field.TypeJSON, Nullable: true},
		{Name: "pricing_override_json", Type: field.TypeJSON, Nullable: true},
	}
	// ModelProviderMappingsTable holds the schema information for the "model_provider_mappings" table.
	ModelProviderMappingsTable = &schema.Table{
		Name:       "model_provider_mappings",
		Columns:    ModelProviderMappingsColumns,
		PrimaryKey: []*schema.Column{ModelProviderMappingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "modelprovidermapping_model_id_provider_id_upstream_model_name",
				Unique:  true,
				Columns: []*schema.Column{ModelProviderMappingsColumns[3], ModelProviderMappingsColumns[4], ModelProviderMappingsColumns[5]},
			},
			{
				Name:    "modelprovidermapping_provider_id_status",
				Unique:  false,
				Columns: []*schema.Column{ModelProviderMappingsColumns[4], ModelProviderMappingsColumns[6]},
			},
		},
	}
	// ModelRegistriesColumns holds the columns for the "model_registries" table.
	ModelRegistriesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "canonical_name", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "family", Type: field.TypeString, Default: ""},
		{Name: "context_window", Type: field.TypeInt, Nullable: true},
		{Name: "max_output_tokens", Type: field.TypeInt, Nullable: true},
		{Name: "quality_tier", Type: field.TypeString, Default: "standard"},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "capabilities_json", Type: field.TypeJSON, Nullable: true},
	}
	// ModelRegistriesTable holds the schema information for the "model_registries" table.
	ModelRegistriesTable = &schema.Table{
		Name:       "model_registries",
		Columns:    ModelRegistriesColumns,
		PrimaryKey: []*schema.Column{ModelRegistriesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "modelregistry_canonical_name",
				Unique:  true,
				Columns: []*schema.Column{ModelRegistriesColumns[4]},
			},
			{
				Name:    "modelregistry_family",
				Unique:  false,
				Columns: []*schema.Column{ModelRegistriesColumns[6]},
			},
			{
				Name:    "modelregistry_status",
				Unique:  false,
				Columns: []*schema.Column{ModelRegistriesColumns[10]},
			},
		},
	}
	// PaymentAuditLogsColumns holds the columns for the "payment_audit_logs" table.
	PaymentAuditLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "order_id", Type: field.TypeInt, Default: 0},
		{Name: "provider_instance_id", Type: field.TypeInt, Default: 0},
		{Name: "event_type", Type: field.TypeString},
		{Name: "idempotency_key", Type: field.TypeString},
		{Name: "payload_json", Type: field.TypeJSON, Nullable: true},
		{Name: "signature_valid", Type: field.TypeBool, Default: false},
	}
	// PaymentAuditLogsTable holds the schema information for the "payment_audit_logs" table.
	PaymentAuditLogsTable = &schema.Table{
		Name:       "payment_audit_logs",
		Columns:    PaymentAuditLogsColumns,
		PrimaryKey: []*schema.Column{PaymentAuditLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentauditlog_idempotency_key",
				Unique:  true,
				Columns: []*schema.Column{PaymentAuditLogsColumns[6]},
			},
			{
				Name:    "paymentauditlog_order_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentAuditLogsColumns[3], PaymentAuditLogsColumns[1]},
			},
			{
				Name:    "paymentauditlog_provider_instance_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentAuditLogsColumns[4], PaymentAuditLogsColumns[1]},
			},
			{
				Name:    "paymentauditlog_event_type_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentAuditLogsColumns[5], PaymentAuditLogsColumns[1]},
			},
		},
	}
	// PaymentOrdersColumns holds the columns for the "payment_orders" table.
	PaymentOrdersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "order_no", Type: field.TypeString},
		{Name: "provider_instance_id", Type: field.TypeInt},
		{Name: "amount", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "status", Type: field.TypeString, Default: "pending"},
		{Name: "product_type", Type: field.TypeString},
		{Name: "product_id", Type: field.TypeString, Default: ""},
		{Name: "provider_transaction_id", Type: field.TypeString, Nullable: true},
		{Name: "provider_snapshot_json", Type: field.TypeJSON, Nullable: true},
		{Name: "expires_at", Type: field.TypeTime, Nullable: true},
		{Name: "paid_at", Type: field.TypeTime, Nullable: true},
		{Name: "closed_at", Type: field.TypeTime, Nullable: true},
		{Name: "metadata_json", Type: field.TypeJSON, Nullable: true},
	}
	// PaymentOrdersTable holds the schema information for the "payment_orders" table.
	PaymentOrdersTable = &schema.Table{
		Name:       "payment_orders",
		Columns:    PaymentOrdersColumns,
		PrimaryKey: []*schema.Column{PaymentOrdersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentorder_order_no",
				Unique:  true,
				Columns: []*schema.Column{PaymentOrdersColumns[4]},
			},
			{
				Name:    "paymentorder_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[3], PaymentOrdersColumns[1]},
			},
			{
				Name:    "paymentorder_status_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[8], PaymentOrdersColumns[1]},
			},
			{
				Name:    "paymentorder_provider_transaction_id",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[11]},
			},
			{
				Name:    "paymentorder_provider_instance_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[5], PaymentOrdersColumns[1]},
			},
			{
				Name:    "paymentorder_expires_at",
				Unique:  false,
				Columns: []*schema.Column{PaymentOrdersColumns[13]},
			},
		},
	}
	// PaymentProviderInstancesColumns holds the columns for the "payment_provider_instances" table.
	PaymentProviderInstancesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "provider", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "config_ciphertext", Type: field.TypeBytes, Nullable: true},
		{Name: "config_version", Type: field.TypeInt, Default: 1},
		{Name: "supported_methods_json", Type: field.TypeJSON, Nullable: true},
		{Name: "limits_json", Type: field.TypeJSON, Nullable: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "metadata_json", Type: field.TypeJSON, Nullable: true},
	}
	// PaymentProviderInstancesTable holds the schema information for the "payment_provider_instances" table.
	PaymentProviderInstancesTable = &schema.Table{
		Name:       "payment_provider_instances",
		Columns:    PaymentProviderInstancesColumns,
		PrimaryKey: []*schema.Column{PaymentProviderInstancesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "paymentproviderinstance_provider_name",
				Unique:  true,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[4], PaymentProviderInstancesColumns[5]},
			},
			{
				Name:    "paymentproviderinstance_provider_status",
				Unique:  false,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[4], PaymentProviderInstancesColumns[6]},
			},
			{
				Name:    "paymentproviderinstance_status_sort_order",
				Unique:  false,
				Columns: []*schema.Column{PaymentProviderInstancesColumns[6], PaymentProviderInstancesColumns[11]},
			},
		},
	}
	// PricingRulesColumns holds the columns for the "pricing_rules" table.
	PricingRulesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "model_id", Type: field.TypeInt},
		{Name: "provider_id", Type: field.TypeInt},
		{Name: "input_price_per_million", Type: field.TypeString, Default: "0.00000000"},
		{Name: "output_price_per_million", Type: field.TypeString, Default: "0.00000000"},
		{Name: "cache_read_price_per_million", Type: field.TypeString, Default: "0.00000000"},
		{Name: "cache_write_price_per_million", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "effective_from", Type: field.TypeTime, Nullable: true},
		{Name: "effective_to", Type: field.TypeTime, Nullable: true},
	}
	// PricingRulesTable holds the schema information for the "pricing_rules" table.
	PricingRulesTable = &schema.Table{
		Name:       "pricing_rules",
		Columns:    PricingRulesColumns,
		PrimaryKey: []*schema.Column{PricingRulesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "pricingrule_model_id_provider_id",
				Unique:  false,
				Columns: []*schema.Column{PricingRulesColumns[3], PricingRulesColumns[4]},
			},
			{
				Name:    "pricingrule_effective_from_effective_to",
				Unique:  false,
				Columns: []*schema.Column{PricingRulesColumns[10], PricingRulesColumns[11]},
			},
		},
	}
	// ProvidersColumns holds the columns for the "providers" table.
	ProvidersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "display_name", Type: field.TypeString},
		{Name: "adapter_type", Type: field.TypeString},
		{Name: "protocol", Type: field.TypeString, Default: "openai-compatible"},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "capabilities_json", Type: field.TypeJSON, Nullable: true},
		{Name: "config_schema_json", Type: field.TypeJSON, Nullable: true},
	}
	// ProvidersTable holds the schema information for the "providers" table.
	ProvidersTable = &schema.Table{
		Name:       "providers",
		Columns:    ProvidersColumns,
		PrimaryKey: []*schema.Column{ProvidersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "provider_name",
				Unique:  true,
				Columns: []*schema.Column{ProvidersColumns[4]},
			},
			{
				Name:    "provider_status",
				Unique:  false,
				Columns: []*schema.Column{ProvidersColumns[8]},
			},
		},
	}
	// ProviderAccountsColumns holds the columns for the "provider_accounts" table.
	ProviderAccountsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "provider_id", Type: field.TypeInt},
		{Name: "name", Type: field.TypeString},
		{Name: "account_type", Type: field.TypeString, Default: "api_key"},
		{Name: "runtime_class", Type: field.TypeString, Default: "api_key"},
		{Name: "upstream_client", Type: field.TypeString, Nullable: true},
		{Name: "credential_ciphertext", Type: field.TypeBytes, Nullable: true},
		{Name: "credential_version", Type: field.TypeInt, Default: 1},
		{Name: "proxy_id", Type: field.TypeString, Nullable: true},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "priority", Type: field.TypeInt, Default: 0},
		{Name: "weight", Type: field.TypeFloat64, Default: 1},
		{Name: "risk_level", Type: field.TypeString, Default: "normal"},
		{Name: "metadata_json", Type: field.TypeJSON, Nullable: true},
	}
	// ProviderAccountsTable holds the schema information for the "provider_accounts" table.
	ProviderAccountsTable = &schema.Table{
		Name:       "provider_accounts",
		Columns:    ProviderAccountsColumns,
		PrimaryKey: []*schema.Column{ProviderAccountsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "provideraccount_provider_id_status",
				Unique:  false,
				Columns: []*schema.Column{ProviderAccountsColumns[4], ProviderAccountsColumns[12]},
			},
			{
				Name:    "provideraccount_status_priority",
				Unique:  false,
				Columns: []*schema.Column{ProviderAccountsColumns[12], ProviderAccountsColumns[13]},
			},
		},
	}
	// RolesColumns holds the columns for the "roles" table.
	RolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
	}
	// RolesTable holds the schema information for the "roles" table.
	RolesTable = &schema.Table{
		Name:       "roles",
		Columns:    RolesColumns,
		PrimaryKey: []*schema.Column{RolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "role_name",
				Unique:  true,
				Columns: []*schema.Column{RolesColumns[3]},
			},
		},
	}
	// SchedulerDecisionsColumns holds the columns for the "scheduler_decisions" table.
	SchedulerDecisionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "request_id", Type: field.TypeString},
		{Name: "attempt_no", Type: field.TypeInt, Default: 1},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "api_key_id", Type: field.TypeInt},
		{Name: "source_protocol", Type: field.TypeString, Default: "openai-compatible"},
		{Name: "source_endpoint", Type: field.TypeString, Default: ""},
		{Name: "target_protocol", Type: field.TypeString, Default: ""},
		{Name: "model", Type: field.TypeString, Default: ""},
		{Name: "strategy", Type: field.TypeString, Default: "balanced"},
		{Name: "strategy_version", Type: field.TypeString, Default: "v1"},
		{Name: "strategy_config_hash", Type: field.TypeString, Default: ""},
		{Name: "selected_provider_id", Type: field.TypeInt, Nullable: true},
		{Name: "selected_account_id", Type: field.TypeInt, Nullable: true},
		{Name: "candidate_count", Type: field.TypeInt, Default: 0},
		{Name: "rejected_count", Type: field.TypeInt, Default: 0},
		{Name: "scores_json", Type: field.TypeJSON, Nullable: true},
		{Name: "reject_reasons_json", Type: field.TypeJSON, Nullable: true},
		{Name: "strategy_weights_json", Type: field.TypeJSON, Nullable: true},
		{Name: "compatibility_warnings_json", Type: field.TypeJSON, Nullable: true},
		{Name: "sticky_hit", Type: field.TypeBool, Default: false},
		{Name: "cache_affinity_hit", Type: field.TypeBool, Default: false},
		{Name: "estimated_cost", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
	}
	// SchedulerDecisionsTable holds the schema information for the "scheduler_decisions" table.
	SchedulerDecisionsTable = &schema.Table{
		Name:       "scheduler_decisions",
		Columns:    SchedulerDecisionsColumns,
		PrimaryKey: []*schema.Column{SchedulerDecisionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "schedulerdecision_request_id_attempt_no",
				Unique:  true,
				Columns: []*schema.Column{SchedulerDecisionsColumns[3], SchedulerDecisionsColumns[4]},
			},
			{
				Name:    "schedulerdecision_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerDecisionsColumns[5], SchedulerDecisionsColumns[1]},
			},
			{
				Name:    "schedulerdecision_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerDecisionsColumns[6], SchedulerDecisionsColumns[1]},
			},
			{
				Name:    "schedulerdecision_selected_account_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerDecisionsColumns[15], SchedulerDecisionsColumns[1]},
			},
			{
				Name:    "schedulerdecision_strategy_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerDecisionsColumns[11], SchedulerDecisionsColumns[1]},
			},
		},
	}
	// SchedulerFeedbacksColumns holds the columns for the "scheduler_feedbacks" table.
	SchedulerFeedbacksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "request_id", Type: field.TypeString},
		{Name: "decision_id", Type: field.TypeInt},
		{Name: "attempt_no", Type: field.TypeInt, Default: 1},
		{Name: "account_id", Type: field.TypeInt},
		{Name: "provider_id", Type: field.TypeInt},
		{Name: "model", Type: field.TypeString, Default: ""},
		{Name: "success", Type: field.TypeBool, Default: false},
		{Name: "error_class", Type: field.TypeString, Nullable: true},
		{Name: "status_code", Type: field.TypeInt, Nullable: true},
		{Name: "latency_ms", Type: field.TypeInt, Default: 0},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cached_tokens", Type: field.TypeInt, Default: 0},
		{Name: "actual_cost", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
	}
	// SchedulerFeedbacksTable holds the schema information for the "scheduler_feedbacks" table.
	SchedulerFeedbacksTable = &schema.Table{
		Name:       "scheduler_feedbacks",
		Columns:    SchedulerFeedbacksColumns,
		PrimaryKey: []*schema.Column{SchedulerFeedbacksColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "schedulerfeedback_decision_id",
				Unique:  false,
				Columns: []*schema.Column{SchedulerFeedbacksColumns[4]},
			},
			{
				Name:    "schedulerfeedback_request_id_attempt_no",
				Unique:  false,
				Columns: []*schema.Column{SchedulerFeedbacksColumns[3], SchedulerFeedbacksColumns[5]},
			},
			{
				Name:    "schedulerfeedback_account_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerFeedbacksColumns[6], SchedulerFeedbacksColumns[1]},
			},
			{
				Name:    "schedulerfeedback_provider_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerFeedbacksColumns[7], SchedulerFeedbacksColumns[1]},
			},
			{
				Name:    "schedulerfeedback_error_class_created_at",
				Unique:  false,
				Columns: []*schema.Column{SchedulerFeedbacksColumns[10], SchedulerFeedbacksColumns[1]},
			},
		},
	}
	// SchedulerStrategiesColumns holds the columns for the "scheduler_strategies" table.
	SchedulerStrategiesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "name", Type: field.TypeString},
		{Name: "version", Type: field.TypeString, Default: "v1"},
		{Name: "status", Type: field.TypeString, Default: "draft"},
		{Name: "scope_type", Type: field.TypeString, Default: "global"},
		{Name: "scope_id", Type: field.TypeInt, Nullable: true},
		{Name: "config_json", Type: field.TypeJSON, Nullable: true},
		{Name: "config_hash", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "created_by", Type: field.TypeInt, Nullable: true},
		{Name: "activated_at", Type: field.TypeTime, Nullable: true},
		{Name: "deprecated_at", Type: field.TypeTime, Nullable: true},
	}
	// SchedulerStrategiesTable holds the schema information for the "scheduler_strategies" table.
	SchedulerStrategiesTable = &schema.Table{
		Name:       "scheduler_strategies",
		Columns:    SchedulerStrategiesColumns,
		PrimaryKey: []*schema.Column{SchedulerStrategiesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "schedulerstrategy_name_version_scope_type_scope_id",
				Unique:  true,
				Columns: []*schema.Column{SchedulerStrategiesColumns[3], SchedulerStrategiesColumns[4], SchedulerStrategiesColumns[6], SchedulerStrategiesColumns[7]},
			},
			{
				Name:    "schedulerstrategy_status_scope_type_scope_id",
				Unique:  false,
				Columns: []*schema.Column{SchedulerStrategiesColumns[5], SchedulerStrategiesColumns[6], SchedulerStrategiesColumns[7]},
			},
			{
				Name:    "schedulerstrategy_name_status",
				Unique:  false,
				Columns: []*schema.Column{SchedulerStrategiesColumns[3], SchedulerStrategiesColumns[5]},
			},
		},
	}
	// SettingsColumns holds the columns for the "settings" table.
	SettingsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "key", Type: field.TypeString},
		{Name: "value_json", Type: field.TypeJSON, Nullable: true},
		{Name: "value_ciphertext", Type: field.TypeBytes, Nullable: true},
		{Name: "is_secret", Type: field.TypeBool, Default: false},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "updated_by", Type: field.TypeInt, Nullable: true},
	}
	// SettingsTable holds the schema information for the "settings" table.
	SettingsTable = &schema.Table{
		Name:       "settings",
		Columns:    SettingsColumns,
		PrimaryKey: []*schema.Column{SettingsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "setting_key",
				Unique:  true,
				Columns: []*schema.Column{SettingsColumns[3]},
			},
		},
	}
	// SubscriptionPlansColumns holds the columns for the "subscription_plans" table.
	SubscriptionPlansColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString},
		{Name: "description", Type: field.TypeString, Default: ""},
		{Name: "price", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "validity_days", Type: field.TypeInt},
		{Name: "entitlements_json", Type: field.TypeJSON, Nullable: true},
		{Name: "for_sale", Type: field.TypeBool, Default: true},
		{Name: "sort_order", Type: field.TypeInt, Default: 0},
		{Name: "status", Type: field.TypeString, Default: "active"},
	}
	// SubscriptionPlansTable holds the schema information for the "subscription_plans" table.
	SubscriptionPlansTable = &schema.Table{
		Name:       "subscription_plans",
		Columns:    SubscriptionPlansColumns,
		PrimaryKey: []*schema.Column{SubscriptionPlansColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "subscriptionplan_for_sale_sort_order",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlansColumns[10], SubscriptionPlansColumns[11]},
			},
			{
				Name:    "subscriptionplan_status",
				Unique:  false,
				Columns: []*schema.Column{SubscriptionPlansColumns[12]},
			},
		},
	}
	// UsageLogsColumns holds the columns for the "usage_logs" table.
	UsageLogsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "request_id", Type: field.TypeString},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "api_key_id", Type: field.TypeInt},
		{Name: "provider_id", Type: field.TypeInt, Nullable: true},
		{Name: "account_id", Type: field.TypeInt, Nullable: true},
		{Name: "source_protocol", Type: field.TypeString, Default: "openai-compatible"},
		{Name: "source_endpoint", Type: field.TypeString, Default: ""},
		{Name: "target_protocol", Type: field.TypeString, Default: ""},
		{Name: "model", Type: field.TypeString, Default: ""},
		{Name: "input_tokens", Type: field.TypeInt, Default: 0},
		{Name: "output_tokens", Type: field.TypeInt, Default: 0},
		{Name: "cached_tokens", Type: field.TypeInt, Default: 0},
		{Name: "total_tokens", Type: field.TypeInt, Default: 0},
		{Name: "usage_estimated", Type: field.TypeBool, Default: false},
		{Name: "latency_ms", Type: field.TypeInt, Default: 0},
		{Name: "success", Type: field.TypeBool, Default: false},
		{Name: "error_class", Type: field.TypeString, Nullable: true},
		{Name: "cost", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "compatibility_warnings_json", Type: field.TypeJSON, Nullable: true},
	}
	// UsageLogsTable holds the schema information for the "usage_logs" table.
	UsageLogsTable = &schema.Table{
		Name:       "usage_logs",
		Columns:    UsageLogsColumns,
		PrimaryKey: []*schema.Column{UsageLogsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "usagelog_request_id",
				Unique:  true,
				Columns: []*schema.Column{UsageLogsColumns[3]},
			},
			{
				Name:    "usagelog_user_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[4], UsageLogsColumns[1]},
			},
			{
				Name:    "usagelog_api_key_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[5], UsageLogsColumns[1]},
			},
			{
				Name:    "usagelog_account_id_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[7], UsageLogsColumns[1]},
			},
			{
				Name:    "usagelog_source_endpoint_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[9], UsageLogsColumns[1]},
			},
			{
				Name:    "usagelog_model_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsageLogsColumns[11], UsageLogsColumns[1]},
			},
		},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "deleted_at", Type: field.TypeTime, Nullable: true},
		{Name: "email", Type: field.TypeString},
		{Name: "email_verified_at", Type: field.TypeTime, Nullable: true},
		{Name: "name", Type: field.TypeString, Default: ""},
		{Name: "password_hash", Type: field.TypeString},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "balance", Type: field.TypeString, Default: "0.00000000"},
		{Name: "currency", Type: field.TypeString, Default: "USD"},
		{Name: "last_login_at", Type: field.TypeTime, Nullable: true},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "user_email",
				Unique:  true,
				Columns: []*schema.Column{UsersColumns[4]},
			},
			{
				Name:    "user_status",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[8]},
			},
			{
				Name:    "user_created_at",
				Unique:  false,
				Columns: []*schema.Column{UsersColumns[1]},
			},
		},
	}
	// UserRolesColumns holds the columns for the "user_roles" table.
	UserRolesColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "role_id", Type: field.TypeInt},
	}
	// UserRolesTable holds the schema information for the "user_roles" table.
	UserRolesTable = &schema.Table{
		Name:       "user_roles",
		Columns:    UserRolesColumns,
		PrimaryKey: []*schema.Column{UserRolesColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "userrole_user_id_role_id",
				Unique:  true,
				Columns: []*schema.Column{UserRolesColumns[3], UserRolesColumns[4]},
			},
			{
				Name:    "userrole_role_id",
				Unique:  false,
				Columns: []*schema.Column{UserRolesColumns[4]},
			},
		},
	}
	// UserSubscriptionsColumns holds the columns for the "user_subscriptions" table.
	UserSubscriptionsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
		{Name: "user_id", Type: field.TypeInt},
		{Name: "plan_id", Type: field.TypeInt},
		{Name: "status", Type: field.TypeString, Default: "active"},
		{Name: "starts_at", Type: field.TypeTime},
		{Name: "expires_at", Type: field.TypeTime},
		{Name: "entitlements_snapshot_json", Type: field.TypeJSON, Nullable: true},
		{Name: "source_type", Type: field.TypeString, Default: ""},
		{Name: "source_id", Type: field.TypeString, Default: ""},
	}
	// UserSubscriptionsTable holds the schema information for the "user_subscriptions" table.
	UserSubscriptionsTable = &schema.Table{
		Name:       "user_subscriptions",
		Columns:    UserSubscriptionsColumns,
		PrimaryKey: []*schema.Column{UserSubscriptionsColumns[0]},
		Indexes: []*schema.Index{
			{
				Name:    "usersubscription_user_id_status",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[3], UserSubscriptionsColumns[5]},
			},
			{
				Name:    "usersubscription_expires_at",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[7]},
			},
			{
				Name:    "usersubscription_plan_id",
				Unique:  false,
				Columns: []*schema.Column{UserSubscriptionsColumns[4]},
			},
		},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		APIKeysTable,
		APIKeyGroupsTable,
		AccountGroupsTable,
		AccountGroupMembersTable,
		AccountHealthSnapshotsTable,
		AccountQuotaSnapshotsTable,
		AffiliateLedgersTable,
		AffiliateRulesTable,
		AuditLogsTable,
		BillingLedgersTable,
		CapabilityDefinitionsTable,
		DomainEventsInboxesTable,
		DomainEventsOutboxesTable,
		IdempotencyRecordsTable,
		InviteCodesTable,
		InviteRelationshipsTable,
		ModelAliasTable,
		ModelProviderMappingsTable,
		ModelRegistriesTable,
		PaymentAuditLogsTable,
		PaymentOrdersTable,
		PaymentProviderInstancesTable,
		PricingRulesTable,
		ProvidersTable,
		ProviderAccountsTable,
		RolesTable,
		SchedulerDecisionsTable,
		SchedulerFeedbacksTable,
		SchedulerStrategiesTable,
		SettingsTable,
		SubscriptionPlansTable,
		UsageLogsTable,
		UsersTable,
		UserRolesTable,
		UserSubscriptionsTable,
	}
)

func init() {
}
