// Code generated by ent, DO NOT EDIT.

package proxy

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the proxy type in the database.
	Label = "proxy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// FieldURLCiphertext holds the string denoting the url_ciphertext field in the database.
	FieldURLCiphertext = "url_ciphertext"
	// FieldURLVersion holds the string denoting the url_version field in the database.
	FieldURLVersion = "url_version"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldMetadataJSON holds the string denoting the metadata_json field in the database.
	FieldMetadataJSON = "metadata_json"
	// FieldCountryCode holds the string denoting the country_code field in the database.
	FieldCountryCode = "country_code"
	// FieldCountryName holds the string denoting the country_name field in the database.
	FieldCountryName = "country_name"
	// FieldLastProbedAt holds the string denoting the last_probed_at field in the database.
	FieldLastProbedAt = "last_probed_at"
	// FieldProbeSuccessCount holds the string denoting the probe_success_count field in the database.
	FieldProbeSuccessCount = "probe_success_count"
	// FieldProbeFailureCount holds the string denoting the probe_failure_count field in the database.
	FieldProbeFailureCount = "probe_failure_count"
	// FieldLastProbeLatencyMs holds the string denoting the last_probe_latency_ms field in the database.
	FieldLastProbeLatencyMs = "last_probe_latency_ms"
	// Table holds the table name of the proxy in the database.
	Table = "proxies"
)

// Columns holds all SQL columns for proxy fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldType,
	FieldURLCiphertext,
	FieldURLVersion,
	FieldStatus,
	FieldMetadataJSON,
	FieldCountryCode,
	FieldCountryName,
	FieldLastProbedAt,
	FieldProbeSuccessCount,
	FieldProbeFailureCount,
	FieldLastProbeLatencyMs,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// TypeValidator is a validator for the "type" field. It is called by the builders before save.
	TypeValidator func(string) error
	// DefaultURLVersion holds the default value on creation for the "url_version" field.
	DefaultURLVersion int
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultCountryCode holds the default value on creation for the "country_code" field.
	DefaultCountryCode string
	// CountryCodeValidator is a validator for the "country_code" field. It is called by the builders before save.
	CountryCodeValidator func(string) error
	// DefaultCountryName holds the default value on creation for the "country_name" field.
	DefaultCountryName string
	// CountryNameValidator is a validator for the "country_name" field. It is called by the builders before save.
	CountryNameValidator func(string) error
	// DefaultProbeSuccessCount holds the default value on creation for the "probe_success_count" field.
	DefaultProbeSuccessCount int
	// DefaultProbeFailureCount holds the default value on creation for the "probe_failure_count" field.
	DefaultProbeFailureCount int
	// DefaultLastProbeLatencyMs holds the default value on creation for the "last_probe_latency_ms" field.
	DefaultLastProbeLatencyMs int
)

// OrderOption defines the ordering options for the Proxy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}

// ByURLVersion orders the results by the url_version field.
func ByURLVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldURLVersion, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByCountryCode orders the results by the country_code field.
func ByCountryCode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountryCode, opts...).ToFunc()
}

// ByCountryName orders the results by the country_name field.
func ByCountryName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCountryName, opts...).ToFunc()
}

// ByLastProbedAt orders the results by the last_probed_at field.
func ByLastProbedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProbedAt, opts...).ToFunc()
}

// ByProbeSuccessCount orders the results by the probe_success_count field.
func ByProbeSuccessCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeSuccessCount, opts...).ToFunc()
}

// ByProbeFailureCount orders the results by the probe_failure_count field.
func ByProbeFailureCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProbeFailureCount, opts...).ToFunc()
}

// ByLastProbeLatencyMs orders the results by the last_probe_latency_ms field.
func ByLastProbeLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastProbeLatencyMs, opts...).ToFunc()
}
