// Code generated by ent, DO NOT EDIT.

package proxy

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpdatedAt, v))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldDeletedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldName, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldType, v))
}

// URLCiphertext applies equality check predicate on the "url_ciphertext" field. It's identical to URLCiphertextEQ.
func URLCiphertext(v []byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldURLCiphertext, v))
}

// URLVersion applies equality check predicate on the "url_version" field. It's identical to URLVersionEQ.
func URLVersion(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldURLVersion, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldStatus, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldUpdatedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldDeletedAt))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldName, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldType, v))
}

// URLCiphertextEQ applies the EQ predicate on the "url_ciphertext" field.
func URLCiphertextEQ(v []byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldURLCiphertext, v))
}

// URLCiphertextNEQ applies the NEQ predicate on the "url_ciphertext" field.
func URLCiphertextNEQ(v []byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldURLCiphertext, v))
}

// URLCiphertextIn applies the In predicate on the "url_ciphertext" field.
func URLCiphertextIn(vs ...[]byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldURLCiphertext, vs...))
}

// URLCiphertextNotIn applies the NotIn predicate on the "url_ciphertext" field.
func URLCiphertextNotIn(vs ...[]byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldURLCiphertext, vs...))
}

// URLCiphertextGT applies the GT predicate on the "url_ciphertext" field.
func URLCiphertextGT(v []byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldURLCiphertext, v))
}

// URLCiphertextGTE applies the GTE predicate on the "url_ciphertext" field.
func URLCiphertextGTE(v []byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldURLCiphertext, v))
}

// URLCiphertextLT applies the LT predicate on the "url_ciphertext" field.
func URLCiphertextLT(v []byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldURLCiphertext, v))
}

// URLCiphertextLTE applies the LTE predicate on the "url_ciphertext" field.
func URLCiphertextLTE(v []byte) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldURLCiphertext, v))
}

// URLCiphertextIsNil applies the IsNil predicate on the "url_ciphertext" field.
func URLCiphertextIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldURLCiphertext))
}

// URLCiphertextNotNil applies the NotNil predicate on the "url_ciphertext" field.
func URLCiphertextNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldURLCiphertext))
}

// URLVersionEQ applies the EQ predicate on the "url_version" field.
func URLVersionEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldURLVersion, v))
}

// URLVersionNEQ applies the NEQ predicate on the "url_version" field.
func URLVersionNEQ(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldURLVersion, v))
}

// URLVersionIn applies the In predicate on the "url_version" field.
func URLVersionIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldURLVersion, vs...))
}

// URLVersionNotIn applies the NotIn predicate on the "url_version" field.
func URLVersionNotIn(vs ...int) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldURLVersion, vs...))
}

// URLVersionGT applies the GT predicate on the "url_version" field.
func URLVersionGT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldURLVersion, v))
}

// URLVersionGTE applies the GTE predicate on the "url_version" field.
func URLVersionGTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldURLVersion, v))
}

// URLVersionLT applies the LT predicate on the "url_version" field.
func URLVersionLT(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldURLVersion, v))
}

// URLVersionLTE applies the LTE predicate on the "url_version" field.
func URLVersionLTE(v int) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldURLVersion, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.Proxy {
	return predicate.Proxy(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.Proxy {
	return predicate.Proxy(sql.FieldContainsFold(FieldStatus, v))
}

// MetadataJSONIsNil applies the IsNil predicate on the "metadata_json" field.
func MetadataJSONIsNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldIsNull(FieldMetadataJSON))
}

// MetadataJSONNotNil applies the NotNil predicate on the "metadata_json" field.
func MetadataJSONNotNil() predicate.Proxy {
	return predicate.Proxy(sql.FieldNotNull(FieldMetadataJSON))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Proxy) predicate.Proxy {
	return predicate.Proxy(sql.NotPredicates(p))
}
