// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/srapi/srapi/apps/api/ent/accountavailabilityrollup"
)

// AccountAvailabilityRollupCreate is the builder for creating a AccountAvailabilityRollup entity.
type AccountAvailabilityRollupCreate struct {
	config
	mutation *AccountAvailabilityRollupMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *AccountAvailabilityRollupCreate) SetCreatedAt(v time.Time) *AccountAvailabilityRollupCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *AccountAvailabilityRollupCreate) SetNillableCreatedAt(v *time.Time) *AccountAvailabilityRollupCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *AccountAvailabilityRollupCreate) SetUpdatedAt(v time.Time) *AccountAvailabilityRollupCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *AccountAvailabilityRollupCreate) SetNillableUpdatedAt(v *time.Time) *AccountAvailabilityRollupCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetAccountID sets the "account_id" field.
func (_c *AccountAvailabilityRollupCreate) SetAccountID(v int) *AccountAvailabilityRollupCreate {
	_c.mutation.SetAccountID(v)
	return _c
}

// SetProviderID sets the "provider_id" field.
func (_c *AccountAvailabilityRollupCreate) SetProviderID(v int) *AccountAvailabilityRollupCreate {
	_c.mutation.SetProviderID(v)
	return _c
}

// SetNillableProviderID sets the "provider_id" field if the given value is not nil.
func (_c *AccountAvailabilityRollupCreate) SetNillableProviderID(v *int) *AccountAvailabilityRollupCreate {
	if v != nil {
		_c.SetProviderID(*v)
	}
	return _c
}

// SetBucketDate sets the "bucket_date" field.
func (_c *AccountAvailabilityRollupCreate) SetBucketDate(v string) *AccountAvailabilityRollupCreate {
	_c.mutation.SetBucketDate(v)
	return _c
}

// SetTotalSamples sets the "total_samples" field.
func (_c *AccountAvailabilityRollupCreate) SetTotalSamples(v int) *AccountAvailabilityRollupCreate {
	_c.mutation.SetTotalSamples(v)
	return _c
}

// SetNillableTotalSamples sets the "total_samples" field if the given value is not nil.
func (_c *AccountAvailabilityRollupCreate) SetNillableTotalSamples(v *int) *AccountAvailabilityRollupCreate {
	if v != nil {
		_c.SetTotalSamples(*v)
	}
	return _c
}

// SetHealthySamples sets the "healthy_samples" field.
func (_c *AccountAvailabilityRollupCreate) SetHealthySamples(v int) *AccountAvailabilityRollupCreate {
	_c.mutation.SetHealthySamples(v)
	return _c
}

// SetNillableHealthySamples sets the "healthy_samples" field if the given value is not nil.
func (_c *AccountAvailabilityRollupCreate) SetNillableHealthySamples(v *int) *AccountAvailabilityRollupCreate {
	if v != nil {
		_c.SetHealthySamples(*v)
	}
	return _c
}

// SetAvailabilityRatio sets the "availability_ratio" field.
func (_c *AccountAvailabilityRollupCreate) SetAvailabilityRatio(v float64) *AccountAvailabilityRollupCreate {
	_c.mutation.SetAvailabilityRatio(v)
	return _c
}

// SetNillableAvailabilityRatio sets the "availability_ratio" field if the given value is not nil.
func (_c *AccountAvailabilityRollupCreate) SetNillableAvailabilityRatio(v *float64) *AccountAvailabilityRollupCreate {
	if v != nil {
		_c.SetAvailabilityRatio(*v)
	}
	return _c
}

// SetAvgSuccessRate sets the "avg_success_rate" field.
func (_c *AccountAvailabilityRollupCreate) SetAvgSuccessRate(v float64) *AccountAvailabilityRollupCreate {
	_c.mutation.SetAvgSuccessRate(v)
	return _c
}

// SetNillableAvgSuccessRate sets the "avg_success_rate" field if the given value is not nil.
func (_c *AccountAvailabilityRollupCreate) SetNillableAvgSuccessRate(v *float64) *AccountAvailabilityRollupCreate {
	if v != nil {
		_c.SetAvgSuccessRate(*v)
	}
	return _c
}

// SetComputedAt sets the "computed_at" field.
func (_c *AccountAvailabilityRollupCreate) SetComputedAt(v time.Time) *AccountAvailabilityRollupCreate {
	_c.mutation.SetComputedAt(v)
	return _c
}

// Mutation returns the AccountAvailabilityRollupMutation object of the builder.
func (_c *AccountAvailabilityRollupCreate) Mutation() *AccountAvailabilityRollupMutation {
	return _c.mutation
}

// Save creates the AccountAvailabilityRollup in the database.
func (_c *AccountAvailabilityRollupCreate) Save(ctx context.Context) (*AccountAvailabilityRollup, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *AccountAvailabilityRollupCreate) SaveX(ctx context.Context) *AccountAvailabilityRollup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountAvailabilityRollupCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountAvailabilityRollupCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *AccountAvailabilityRollupCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := accountavailabilityrollup.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := accountavailabilityrollup.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		v := accountavailabilityrollup.DefaultProviderID
		_c.mutation.SetProviderID(v)
	}
	if _, ok := _c.mutation.TotalSamples(); !ok {
		v := accountavailabilityrollup.DefaultTotalSamples
		_c.mutation.SetTotalSamples(v)
	}
	if _, ok := _c.mutation.HealthySamples(); !ok {
		v := accountavailabilityrollup.DefaultHealthySamples
		_c.mutation.SetHealthySamples(v)
	}
	if _, ok := _c.mutation.AvailabilityRatio(); !ok {
		v := accountavailabilityrollup.DefaultAvailabilityRatio
		_c.mutation.SetAvailabilityRatio(v)
	}
	if _, ok := _c.mutation.AvgSuccessRate(); !ok {
		v := accountavailabilityrollup.DefaultAvgSuccessRate
		_c.mutation.SetAvgSuccessRate(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *AccountAvailabilityRollupCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.updated_at"`)}
	}
	if _, ok := _c.mutation.AccountID(); !ok {
		return &ValidationError{Name: "account_id", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.account_id"`)}
	}
	if _, ok := _c.mutation.ProviderID(); !ok {
		return &ValidationError{Name: "provider_id", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.provider_id"`)}
	}
	if _, ok := _c.mutation.BucketDate(); !ok {
		return &ValidationError{Name: "bucket_date", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.bucket_date"`)}
	}
	if _, ok := _c.mutation.TotalSamples(); !ok {
		return &ValidationError{Name: "total_samples", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.total_samples"`)}
	}
	if _, ok := _c.mutation.HealthySamples(); !ok {
		return &ValidationError{Name: "healthy_samples", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.healthy_samples"`)}
	}
	if _, ok := _c.mutation.AvailabilityRatio(); !ok {
		return &ValidationError{Name: "availability_ratio", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.availability_ratio"`)}
	}
	if _, ok := _c.mutation.AvgSuccessRate(); !ok {
		return &ValidationError{Name: "avg_success_rate", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.avg_success_rate"`)}
	}
	if _, ok := _c.mutation.ComputedAt(); !ok {
		return &ValidationError{Name: "computed_at", err: errors.New(`ent: missing required field "AccountAvailabilityRollup.computed_at"`)}
	}
	return nil
}

func (_c *AccountAvailabilityRollupCreate) sqlSave(ctx context.Context) (*AccountAvailabilityRollup, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *AccountAvailabilityRollupCreate) createSpec() (*AccountAvailabilityRollup, *sqlgraph.CreateSpec) {
	var (
		_node = &AccountAvailabilityRollup{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(accountavailabilityrollup.Table, sqlgraph.NewFieldSpec(accountavailabilityrollup.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(accountavailabilityrollup.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(accountavailabilityrollup.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.AccountID(); ok {
		_spec.SetField(accountavailabilityrollup.FieldAccountID, field.TypeInt, value)
		_node.AccountID = value
	}
	if value, ok := _c.mutation.ProviderID(); ok {
		_spec.SetField(accountavailabilityrollup.FieldProviderID, field.TypeInt, value)
		_node.ProviderID = value
	}
	if value, ok := _c.mutation.BucketDate(); ok {
		_spec.SetField(accountavailabilityrollup.FieldBucketDate, field.TypeString, value)
		_node.BucketDate = value
	}
	if value, ok := _c.mutation.TotalSamples(); ok {
		_spec.SetField(accountavailabilityrollup.FieldTotalSamples, field.TypeInt, value)
		_node.TotalSamples = value
	}
	if value, ok := _c.mutation.HealthySamples(); ok {
		_spec.SetField(accountavailabilityrollup.FieldHealthySamples, field.TypeInt, value)
		_node.HealthySamples = value
	}
	if value, ok := _c.mutation.AvailabilityRatio(); ok {
		_spec.SetField(accountavailabilityrollup.FieldAvailabilityRatio, field.TypeFloat64, value)
		_node.AvailabilityRatio = value
	}
	if value, ok := _c.mutation.AvgSuccessRate(); ok {
		_spec.SetField(accountavailabilityrollup.FieldAvgSuccessRate, field.TypeFloat64, value)
		_node.AvgSuccessRate = value
	}
	if value, ok := _c.mutation.ComputedAt(); ok {
		_spec.SetField(accountavailabilityrollup.FieldComputedAt, field.TypeTime, value)
		_node.ComputedAt = value
	}
	return _node, _spec
}

// AccountAvailabilityRollupCreateBulk is the builder for creating many AccountAvailabilityRollup entities in bulk.
type AccountAvailabilityRollupCreateBulk struct {
	config
	err      error
	builders []*AccountAvailabilityRollupCreate
}

// Save creates the AccountAvailabilityRollup entities in the database.
func (_c *AccountAvailabilityRollupCreateBulk) Save(ctx context.Context) ([]*AccountAvailabilityRollup, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*AccountAvailabilityRollup, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*AccountAvailabilityRollupMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *AccountAvailabilityRollupCreateBulk) SaveX(ctx context.Context) []*AccountAvailabilityRollup {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *AccountAvailabilityRollupCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *AccountAvailabilityRollupCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
