// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/accountavailabilityrollup"
)

// AccountAvailabilityRollup is the model entity for the AccountAvailabilityRollup schema.
type AccountAvailabilityRollup struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int `json:"account_id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int `json:"provider_id,omitempty"`
	// BucketDate holds the value of the "bucket_date" field.
	BucketDate string `json:"bucket_date,omitempty"`
	// TotalSamples holds the value of the "total_samples" field.
	TotalSamples int `json:"total_samples,omitempty"`
	// HealthySamples holds the value of the "healthy_samples" field.
	HealthySamples int `json:"healthy_samples,omitempty"`
	// AvailabilityRatio holds the value of the "availability_ratio" field.
	AvailabilityRatio float64 `json:"availability_ratio,omitempty"`
	// AvgSuccessRate holds the value of the "avg_success_rate" field.
	AvgSuccessRate float64 `json:"avg_success_rate,omitempty"`
	// ComputedAt holds the value of the "computed_at" field.
	ComputedAt   time.Time `json:"computed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountAvailabilityRollup) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountavailabilityrollup.FieldAvailabilityRatio, accountavailabilityrollup.FieldAvgSuccessRate:
			values[i] = new(sql.NullFloat64)
		case accountavailabilityrollup.FieldID, accountavailabilityrollup.FieldAccountID, accountavailabilityrollup.FieldProviderID, accountavailabilityrollup.FieldTotalSamples, accountavailabilityrollup.FieldHealthySamples:
			values[i] = new(sql.NullInt64)
		case accountavailabilityrollup.FieldBucketDate:
			values[i] = new(sql.NullString)
		case accountavailabilityrollup.FieldCreatedAt, accountavailabilityrollup.FieldUpdatedAt, accountavailabilityrollup.FieldComputedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountAvailabilityRollup fields.
func (_m *AccountAvailabilityRollup) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountavailabilityrollup.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case accountavailabilityrollup.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountavailabilityrollup.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case accountavailabilityrollup.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = int(value.Int64)
			}
		case accountavailabilityrollup.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = int(value.Int64)
			}
		case accountavailabilityrollup.FieldBucketDate:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bucket_date", values[i])
			} else if value.Valid {
				_m.BucketDate = value.String
			}
		case accountavailabilityrollup.FieldTotalSamples:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field total_samples", values[i])
			} else if value.Valid {
				_m.TotalSamples = int(value.Int64)
			}
		case accountavailabilityrollup.FieldHealthySamples:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field healthy_samples", values[i])
			} else if value.Valid {
				_m.HealthySamples = int(value.Int64)
			}
		case accountavailabilityrollup.FieldAvailabilityRatio:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field availability_ratio", values[i])
			} else if value.Valid {
				_m.AvailabilityRatio = value.Float64
			}
		case accountavailabilityrollup.FieldAvgSuccessRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field avg_success_rate", values[i])
			} else if value.Valid {
				_m.AvgSuccessRate = value.Float64
			}
		case accountavailabilityrollup.FieldComputedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field computed_at", values[i])
			} else if value.Valid {
				_m.ComputedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountAvailabilityRollup.
// This includes values selected through modifiers, order, etc.
func (_m *AccountAvailabilityRollup) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountAvailabilityRollup.
// Note that you need to call AccountAvailabilityRollup.Unwrap() before calling this method if this AccountAvailabilityRollup
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountAvailabilityRollup) Update() *AccountAvailabilityRollupUpdateOne {
	return NewAccountAvailabilityRollupClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountAvailabilityRollup entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountAvailabilityRollup) Unwrap() *AccountAvailabilityRollup {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountAvailabilityRollup is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountAvailabilityRollup) String() string {
	var builder strings.Builder
	builder.WriteString("AccountAvailabilityRollup(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("bucket_date=")
	builder.WriteString(_m.BucketDate)
	builder.WriteString(", ")
	builder.WriteString("total_samples=")
	builder.WriteString(fmt.Sprintf("%v", _m.TotalSamples))
	builder.WriteString(", ")
	builder.WriteString("healthy_samples=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthySamples))
	builder.WriteString(", ")
	builder.WriteString("availability_ratio=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvailabilityRatio))
	builder.WriteString(", ")
	builder.WriteString("avg_success_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.AvgSuccessRate))
	builder.WriteString(", ")
	builder.WriteString("computed_at=")
	builder.WriteString(_m.ComputedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountAvailabilityRollups is a parsable slice of AccountAvailabilityRollup.
type AccountAvailabilityRollups []*AccountAvailabilityRollup
