// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/srapi/srapi/apps/api/ent/affiliaterule"
	"github.com/srapi/srapi/apps/api/ent/predicate"
)

// AffiliateRuleUpdate is the builder for updating AffiliateRule entities.
type AffiliateRuleUpdate struct {
	config
	hooks    []Hook
	mutation *AffiliateRuleMutation
}

// Where appends a list predicates to the AffiliateRuleUpdate builder.
func (_u *AffiliateRuleUpdate) Where(ps ...predicate.AffiliateRule) *AffiliateRuleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AffiliateRuleUpdate) SetUpdatedAt(v time.Time) *AffiliateRuleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AffiliateRuleUpdate) SetName(v string) *AffiliateRuleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableName(v *string) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AffiliateRuleUpdate) SetStatus(v string) *AffiliateRuleUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableStatus(v *string) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *AffiliateRuleUpdate) SetTriggerType(v string) *AffiliateRuleUpdate {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableTriggerType(v *string) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *AffiliateRuleUpdate) SetRate(v string) *AffiliateRuleUpdate {
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableRate(v *string) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// SetFixedAmount sets the "fixed_amount" field.
func (_u *AffiliateRuleUpdate) SetFixedAmount(v string) *AffiliateRuleUpdate {
	_u.mutation.SetFixedAmount(v)
	return _u
}

// SetNillableFixedAmount sets the "fixed_amount" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableFixedAmount(v *string) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetFixedAmount(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AffiliateRuleUpdate) SetCurrency(v string) *AffiliateRuleUpdate {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableCurrency(v *string) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetMaxRebateAmount sets the "max_rebate_amount" field.
func (_u *AffiliateRuleUpdate) SetMaxRebateAmount(v string) *AffiliateRuleUpdate {
	_u.mutation.SetMaxRebateAmount(v)
	return _u
}

// SetNillableMaxRebateAmount sets the "max_rebate_amount" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableMaxRebateAmount(v *string) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetMaxRebateAmount(*v)
	}
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *AffiliateRuleUpdate) SetValidFrom(v time.Time) *AffiliateRuleUpdate {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableValidFrom(v *time.Time) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (_u *AffiliateRuleUpdate) ClearValidFrom() *AffiliateRuleUpdate {
	_u.mutation.ClearValidFrom()
	return _u
}

// SetValidTo sets the "valid_to" field.
func (_u *AffiliateRuleUpdate) SetValidTo(v time.Time) *AffiliateRuleUpdate {
	_u.mutation.SetValidTo(v)
	return _u
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_u *AffiliateRuleUpdate) SetNillableValidTo(v *time.Time) *AffiliateRuleUpdate {
	if v != nil {
		_u.SetValidTo(*v)
	}
	return _u
}

// ClearValidTo clears the value of the "valid_to" field.
func (_u *AffiliateRuleUpdate) ClearValidTo() *AffiliateRuleUpdate {
	_u.mutation.ClearValidTo()
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *AffiliateRuleUpdate) SetMetadataJSON(v map[string]interface{}) *AffiliateRuleUpdate {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (_u *AffiliateRuleUpdate) ClearMetadataJSON() *AffiliateRuleUpdate {
	_u.mutation.ClearMetadataJSON()
	return _u
}

// Mutation returns the AffiliateRuleMutation object of the builder.
func (_u *AffiliateRuleUpdate) Mutation() *AffiliateRuleMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AffiliateRuleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AffiliateRuleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AffiliateRuleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AffiliateRuleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AffiliateRuleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := affiliaterule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AffiliateRuleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := affiliaterule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AffiliateRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := affiliaterule.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "AffiliateRule.trigger_type": %w`, err)}
		}
	}
	return nil
}

func (_u *AffiliateRuleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(affiliaterule.Table, affiliaterule.Columns, sqlgraph.NewFieldSpec(affiliaterule.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(affiliaterule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(affiliaterule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(affiliaterule.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(affiliaterule.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(affiliaterule.FieldRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.FixedAmount(); ok {
		_spec.SetField(affiliaterule.FieldFixedAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(affiliaterule.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxRebateAmount(); ok {
		_spec.SetField(affiliaterule.FieldMaxRebateAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(affiliaterule.FieldValidFrom, field.TypeTime, value)
	}
	if _u.mutation.ValidFromCleared() {
		_spec.ClearField(affiliaterule.FieldValidFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.ValidTo(); ok {
		_spec.SetField(affiliaterule.FieldValidTo, field.TypeTime, value)
	}
	if _u.mutation.ValidToCleared() {
		_spec.ClearField(affiliaterule.FieldValidTo, field.TypeTime)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(affiliaterule.FieldMetadataJSON, field.TypeJSON, value)
	}
	if _u.mutation.MetadataJSONCleared() {
		_spec.ClearField(affiliaterule.FieldMetadataJSON, field.TypeJSON)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{affiliaterule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AffiliateRuleUpdateOne is the builder for updating a single AffiliateRule entity.
type AffiliateRuleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AffiliateRuleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AffiliateRuleUpdateOne) SetUpdatedAt(v time.Time) *AffiliateRuleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetName sets the "name" field.
func (_u *AffiliateRuleUpdateOne) SetName(v string) *AffiliateRuleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableName(v *string) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AffiliateRuleUpdateOne) SetStatus(v string) *AffiliateRuleUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableStatus(v *string) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetTriggerType sets the "trigger_type" field.
func (_u *AffiliateRuleUpdateOne) SetTriggerType(v string) *AffiliateRuleUpdateOne {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "trigger_type" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableTriggerType(v *string) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetRate sets the "rate" field.
func (_u *AffiliateRuleUpdateOne) SetRate(v string) *AffiliateRuleUpdateOne {
	_u.mutation.SetRate(v)
	return _u
}

// SetNillableRate sets the "rate" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableRate(v *string) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetRate(*v)
	}
	return _u
}

// SetFixedAmount sets the "fixed_amount" field.
func (_u *AffiliateRuleUpdateOne) SetFixedAmount(v string) *AffiliateRuleUpdateOne {
	_u.mutation.SetFixedAmount(v)
	return _u
}

// SetNillableFixedAmount sets the "fixed_amount" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableFixedAmount(v *string) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetFixedAmount(*v)
	}
	return _u
}

// SetCurrency sets the "currency" field.
func (_u *AffiliateRuleUpdateOne) SetCurrency(v string) *AffiliateRuleUpdateOne {
	_u.mutation.SetCurrency(v)
	return _u
}

// SetNillableCurrency sets the "currency" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableCurrency(v *string) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetCurrency(*v)
	}
	return _u
}

// SetMaxRebateAmount sets the "max_rebate_amount" field.
func (_u *AffiliateRuleUpdateOne) SetMaxRebateAmount(v string) *AffiliateRuleUpdateOne {
	_u.mutation.SetMaxRebateAmount(v)
	return _u
}

// SetNillableMaxRebateAmount sets the "max_rebate_amount" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableMaxRebateAmount(v *string) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetMaxRebateAmount(*v)
	}
	return _u
}

// SetValidFrom sets the "valid_from" field.
func (_u *AffiliateRuleUpdateOne) SetValidFrom(v time.Time) *AffiliateRuleUpdateOne {
	_u.mutation.SetValidFrom(v)
	return _u
}

// SetNillableValidFrom sets the "valid_from" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableValidFrom(v *time.Time) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetValidFrom(*v)
	}
	return _u
}

// ClearValidFrom clears the value of the "valid_from" field.
func (_u *AffiliateRuleUpdateOne) ClearValidFrom() *AffiliateRuleUpdateOne {
	_u.mutation.ClearValidFrom()
	return _u
}

// SetValidTo sets the "valid_to" field.
func (_u *AffiliateRuleUpdateOne) SetValidTo(v time.Time) *AffiliateRuleUpdateOne {
	_u.mutation.SetValidTo(v)
	return _u
}

// SetNillableValidTo sets the "valid_to" field if the given value is not nil.
func (_u *AffiliateRuleUpdateOne) SetNillableValidTo(v *time.Time) *AffiliateRuleUpdateOne {
	if v != nil {
		_u.SetValidTo(*v)
	}
	return _u
}

// ClearValidTo clears the value of the "valid_to" field.
func (_u *AffiliateRuleUpdateOne) ClearValidTo() *AffiliateRuleUpdateOne {
	_u.mutation.ClearValidTo()
	return _u
}

// SetMetadataJSON sets the "metadata_json" field.
func (_u *AffiliateRuleUpdateOne) SetMetadataJSON(v map[string]interface{}) *AffiliateRuleUpdateOne {
	_u.mutation.SetMetadataJSON(v)
	return _u
}

// ClearMetadataJSON clears the value of the "metadata_json" field.
func (_u *AffiliateRuleUpdateOne) ClearMetadataJSON() *AffiliateRuleUpdateOne {
	_u.mutation.ClearMetadataJSON()
	return _u
}

// Mutation returns the AffiliateRuleMutation object of the builder.
func (_u *AffiliateRuleUpdateOne) Mutation() *AffiliateRuleMutation {
	return _u.mutation
}

// Where appends a list predicates to the AffiliateRuleUpdate builder.
func (_u *AffiliateRuleUpdateOne) Where(ps ...predicate.AffiliateRule) *AffiliateRuleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AffiliateRuleUpdateOne) Select(field string, fields ...string) *AffiliateRuleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AffiliateRule entity.
func (_u *AffiliateRuleUpdateOne) Save(ctx context.Context) (*AffiliateRule, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AffiliateRuleUpdateOne) SaveX(ctx context.Context) *AffiliateRule {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AffiliateRuleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AffiliateRuleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AffiliateRuleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := affiliaterule.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AffiliateRuleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := affiliaterule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "AffiliateRule.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.TriggerType(); ok {
		if err := affiliaterule.TriggerTypeValidator(v); err != nil {
			return &ValidationError{Name: "trigger_type", err: fmt.Errorf(`ent: validator failed for field "AffiliateRule.trigger_type": %w`, err)}
		}
	}
	return nil
}

func (_u *AffiliateRuleUpdateOne) sqlSave(ctx context.Context) (_node *AffiliateRule, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(affiliaterule.Table, affiliaterule.Columns, sqlgraph.NewFieldSpec(affiliaterule.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AffiliateRule.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, affiliaterule.FieldID)
		for _, f := range fields {
			if !affiliaterule.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != affiliaterule.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(affiliaterule.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(affiliaterule.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(affiliaterule.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(affiliaterule.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Rate(); ok {
		_spec.SetField(affiliaterule.FieldRate, field.TypeString, value)
	}
	if value, ok := _u.mutation.FixedAmount(); ok {
		_spec.SetField(affiliaterule.FieldFixedAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.Currency(); ok {
		_spec.SetField(affiliaterule.FieldCurrency, field.TypeString, value)
	}
	if value, ok := _u.mutation.MaxRebateAmount(); ok {
		_spec.SetField(affiliaterule.FieldMaxRebateAmount, field.TypeString, value)
	}
	if value, ok := _u.mutation.ValidFrom(); ok {
		_spec.SetField(affiliaterule.FieldValidFrom, field.TypeTime, value)
	}
	if _u.mutation.ValidFromCleared() {
		_spec.ClearField(affiliaterule.FieldValidFrom, field.TypeTime)
	}
	if value, ok := _u.mutation.ValidTo(); ok {
		_spec.SetField(affiliaterule.FieldValidTo, field.TypeTime, value)
	}
	if _u.mutation.ValidToCleared() {
		_spec.ClearField(affiliaterule.FieldValidTo, field.TypeTime)
	}
	if value, ok := _u.mutation.MetadataJSON(); ok {
		_spec.SetField(affiliaterule.FieldMetadataJSON, field.TypeJSON, value)
	}
	if _u.mutation.MetadataJSONCleared() {
		_spec.ClearField(affiliaterule.FieldMetadataJSON, field.TypeJSON)
	}
	_node = &AffiliateRule{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{affiliaterule.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
