// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/srapi/srapi/apps/api/ent/capabilitydefinition"
	"github.com/srapi/srapi/apps/api/ent/predicate"
)

// CapabilityDefinitionUpdate is the builder for updating CapabilityDefinition entities.
type CapabilityDefinitionUpdate struct {
	config
	hooks    []Hook
	mutation *CapabilityDefinitionMutation
}

// Where appends a list predicates to the CapabilityDefinitionUpdate builder.
func (_u *CapabilityDefinitionUpdate) Where(ps ...predicate.CapabilityDefinition) *CapabilityDefinitionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CapabilityDefinitionUpdate) SetUpdatedAt(v time.Time) *CapabilityDefinitionUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *CapabilityDefinitionUpdate) SetKey(v string) *CapabilityDefinitionUpdate {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdate) SetNillableKey(v *string) *CapabilityDefinitionUpdate {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CapabilityDefinitionUpdate) SetVersion(v string) *CapabilityDefinitionUpdate {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdate) SetNillableVersion(v *string) *CapabilityDefinitionUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *CapabilityDefinitionUpdate) SetCategory(v string) *CapabilityDefinitionUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdate) SetNillableCategory(v *string) *CapabilityDefinitionUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CapabilityDefinitionUpdate) SetStatus(v string) *CapabilityDefinitionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdate) SetNillableStatus(v *string) *CapabilityDefinitionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CapabilityDefinitionUpdate) SetDescription(v string) *CapabilityDefinitionUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdate) SetNillableDescription(v *string) *CapabilityDefinitionUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSchemaJSON sets the "schema_json" field.
func (_u *CapabilityDefinitionUpdate) SetSchemaJSON(v map[string]interface{}) *CapabilityDefinitionUpdate {
	_u.mutation.SetSchemaJSON(v)
	return _u
}

// ClearSchemaJSON clears the value of the "schema_json" field.
func (_u *CapabilityDefinitionUpdate) ClearSchemaJSON() *CapabilityDefinitionUpdate {
	_u.mutation.ClearSchemaJSON()
	return _u
}

// SetReplacementKey sets the "replacement_key" field.
func (_u *CapabilityDefinitionUpdate) SetReplacementKey(v string) *CapabilityDefinitionUpdate {
	_u.mutation.SetReplacementKey(v)
	return _u
}

// SetNillableReplacementKey sets the "replacement_key" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdate) SetNillableReplacementKey(v *string) *CapabilityDefinitionUpdate {
	if v != nil {
		_u.SetReplacementKey(*v)
	}
	return _u
}

// ClearReplacementKey clears the value of the "replacement_key" field.
func (_u *CapabilityDefinitionUpdate) ClearReplacementKey() *CapabilityDefinitionUpdate {
	_u.mutation.ClearReplacementKey()
	return _u
}

// Mutation returns the CapabilityDefinitionMutation object of the builder.
func (_u *CapabilityDefinitionUpdate) Mutation() *CapabilityDefinitionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *CapabilityDefinitionUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CapabilityDefinitionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *CapabilityDefinitionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CapabilityDefinitionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CapabilityDefinitionUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := capabilitydefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CapabilityDefinitionUpdate) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := capabilitydefinition.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "CapabilityDefinition.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := capabilitydefinition.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "CapabilityDefinition.category": %w`, err)}
		}
	}
	return nil
}

func (_u *CapabilityDefinitionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(capabilitydefinition.Table, capabilitydefinition.Columns, sqlgraph.NewFieldSpec(capabilitydefinition.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(capabilitydefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(capabilitydefinition.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(capabilitydefinition.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(capabilitydefinition.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(capabilitydefinition.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(capabilitydefinition.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SchemaJSON(); ok {
		_spec.SetField(capabilitydefinition.FieldSchemaJSON, field.TypeJSON, value)
	}
	if _u.mutation.SchemaJSONCleared() {
		_spec.ClearField(capabilitydefinition.FieldSchemaJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.ReplacementKey(); ok {
		_spec.SetField(capabilitydefinition.FieldReplacementKey, field.TypeString, value)
	}
	if _u.mutation.ReplacementKeyCleared() {
		_spec.ClearField(capabilitydefinition.FieldReplacementKey, field.TypeString)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{capabilitydefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// CapabilityDefinitionUpdateOne is the builder for updating a single CapabilityDefinition entity.
type CapabilityDefinitionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CapabilityDefinitionMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *CapabilityDefinitionUpdateOne) SetUpdatedAt(v time.Time) *CapabilityDefinitionUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetKey sets the "key" field.
func (_u *CapabilityDefinitionUpdateOne) SetKey(v string) *CapabilityDefinitionUpdateOne {
	_u.mutation.SetKey(v)
	return _u
}

// SetNillableKey sets the "key" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdateOne) SetNillableKey(v *string) *CapabilityDefinitionUpdateOne {
	if v != nil {
		_u.SetKey(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *CapabilityDefinitionUpdateOne) SetVersion(v string) *CapabilityDefinitionUpdateOne {
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdateOne) SetNillableVersion(v *string) *CapabilityDefinitionUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *CapabilityDefinitionUpdateOne) SetCategory(v string) *CapabilityDefinitionUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdateOne) SetNillableCategory(v *string) *CapabilityDefinitionUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *CapabilityDefinitionUpdateOne) SetStatus(v string) *CapabilityDefinitionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdateOne) SetNillableStatus(v *string) *CapabilityDefinitionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *CapabilityDefinitionUpdateOne) SetDescription(v string) *CapabilityDefinitionUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdateOne) SetNillableDescription(v *string) *CapabilityDefinitionUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetSchemaJSON sets the "schema_json" field.
func (_u *CapabilityDefinitionUpdateOne) SetSchemaJSON(v map[string]interface{}) *CapabilityDefinitionUpdateOne {
	_u.mutation.SetSchemaJSON(v)
	return _u
}

// ClearSchemaJSON clears the value of the "schema_json" field.
func (_u *CapabilityDefinitionUpdateOne) ClearSchemaJSON() *CapabilityDefinitionUpdateOne {
	_u.mutation.ClearSchemaJSON()
	return _u
}

// SetReplacementKey sets the "replacement_key" field.
func (_u *CapabilityDefinitionUpdateOne) SetReplacementKey(v string) *CapabilityDefinitionUpdateOne {
	_u.mutation.SetReplacementKey(v)
	return _u
}

// SetNillableReplacementKey sets the "replacement_key" field if the given value is not nil.
func (_u *CapabilityDefinitionUpdateOne) SetNillableReplacementKey(v *string) *CapabilityDefinitionUpdateOne {
	if v != nil {
		_u.SetReplacementKey(*v)
	}
	return _u
}

// ClearReplacementKey clears the value of the "replacement_key" field.
func (_u *CapabilityDefinitionUpdateOne) ClearReplacementKey() *CapabilityDefinitionUpdateOne {
	_u.mutation.ClearReplacementKey()
	return _u
}

// Mutation returns the CapabilityDefinitionMutation object of the builder.
func (_u *CapabilityDefinitionUpdateOne) Mutation() *CapabilityDefinitionMutation {
	return _u.mutation
}

// Where appends a list predicates to the CapabilityDefinitionUpdate builder.
func (_u *CapabilityDefinitionUpdateOne) Where(ps ...predicate.CapabilityDefinition) *CapabilityDefinitionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *CapabilityDefinitionUpdateOne) Select(field string, fields ...string) *CapabilityDefinitionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated CapabilityDefinition entity.
func (_u *CapabilityDefinitionUpdateOne) Save(ctx context.Context) (*CapabilityDefinition, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *CapabilityDefinitionUpdateOne) SaveX(ctx context.Context) *CapabilityDefinition {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *CapabilityDefinitionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *CapabilityDefinitionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *CapabilityDefinitionUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := capabilitydefinition.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *CapabilityDefinitionUpdateOne) check() error {
	if v, ok := _u.mutation.Key(); ok {
		if err := capabilitydefinition.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "CapabilityDefinition.key": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Category(); ok {
		if err := capabilitydefinition.CategoryValidator(v); err != nil {
			return &ValidationError{Name: "category", err: fmt.Errorf(`ent: validator failed for field "CapabilityDefinition.category": %w`, err)}
		}
	}
	return nil
}

func (_u *CapabilityDefinitionUpdateOne) sqlSave(ctx context.Context) (_node *CapabilityDefinition, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(capabilitydefinition.Table, capabilitydefinition.Columns, sqlgraph.NewFieldSpec(capabilitydefinition.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "CapabilityDefinition.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, capabilitydefinition.FieldID)
		for _, f := range fields {
			if !capabilitydefinition.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != capabilitydefinition.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(capabilitydefinition.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Key(); ok {
		_spec.SetField(capabilitydefinition.FieldKey, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(capabilitydefinition.FieldVersion, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(capabilitydefinition.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(capabilitydefinition.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(capabilitydefinition.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.SchemaJSON(); ok {
		_spec.SetField(capabilitydefinition.FieldSchemaJSON, field.TypeJSON, value)
	}
	if _u.mutation.SchemaJSONCleared() {
		_spec.ClearField(capabilitydefinition.FieldSchemaJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.ReplacementKey(); ok {
		_spec.SetField(capabilitydefinition.FieldReplacementKey, field.TypeString, value)
	}
	if _u.mutation.ReplacementKeyCleared() {
		_spec.ClearField(capabilitydefinition.FieldReplacementKey, field.TypeString)
	}
	_node = &CapabilityDefinition{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{capabilitydefinition.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
