// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/srapi/srapi/apps/api/ent/obsalertsilence"
	"github.com/srapi/srapi/apps/api/ent/predicate"
)

// ObsAlertSilenceUpdate is the builder for updating ObsAlertSilence entities.
type ObsAlertSilenceUpdate struct {
	config
	hooks    []Hook
	mutation *ObsAlertSilenceMutation
}

// Where appends a list predicates to the ObsAlertSilenceUpdate builder.
func (_u *ObsAlertSilenceUpdate) Where(ps ...predicate.ObsAlertSilence) *ObsAlertSilenceUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObsAlertSilenceUpdate) SetUpdatedAt(v time.Time) *ObsAlertSilenceUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetComment sets the "comment" field.
func (_u *ObsAlertSilenceUpdate) SetComment(v string) *ObsAlertSilenceUpdate {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *ObsAlertSilenceUpdate) SetNillableComment(v *string) *ObsAlertSilenceUpdate {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *ObsAlertSilenceUpdate) ClearComment() *ObsAlertSilenceUpdate {
	_u.mutation.ClearComment()
	return _u
}

// SetMatcherJSON sets the "matcher_json" field.
func (_u *ObsAlertSilenceUpdate) SetMatcherJSON(v map[string]interface{}) *ObsAlertSilenceUpdate {
	_u.mutation.SetMatcherJSON(v)
	return _u
}

// ClearMatcherJSON clears the value of the "matcher_json" field.
func (_u *ObsAlertSilenceUpdate) ClearMatcherJSON() *ObsAlertSilenceUpdate {
	_u.mutation.ClearMatcherJSON()
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *ObsAlertSilenceUpdate) SetStartsAt(v time.Time) *ObsAlertSilenceUpdate {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *ObsAlertSilenceUpdate) SetNillableStartsAt(v *time.Time) *ObsAlertSilenceUpdate {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *ObsAlertSilenceUpdate) SetEndsAt(v time.Time) *ObsAlertSilenceUpdate {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *ObsAlertSilenceUpdate) SetNillableEndsAt(v *time.Time) *ObsAlertSilenceUpdate {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ObsAlertSilenceUpdate) SetCreatedBy(v int) *ObsAlertSilenceUpdate {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ObsAlertSilenceUpdate) SetNillableCreatedBy(v *int) *ObsAlertSilenceUpdate {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ObsAlertSilenceUpdate) AddCreatedBy(v int) *ObsAlertSilenceUpdate {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ObsAlertSilenceUpdate) ClearCreatedBy() *ObsAlertSilenceUpdate {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Mutation returns the ObsAlertSilenceMutation object of the builder.
func (_u *ObsAlertSilenceUpdate) Mutation() *ObsAlertSilenceMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ObsAlertSilenceUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObsAlertSilenceUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ObsAlertSilenceUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObsAlertSilenceUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObsAlertSilenceUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := obsalertsilence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ObsAlertSilenceUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(obsalertsilence.Table, obsalertsilence.Columns, sqlgraph.NewFieldSpec(obsalertsilence.FieldID, field.TypeInt))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(obsalertsilence.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(obsalertsilence.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(obsalertsilence.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.MatcherJSON(); ok {
		_spec.SetField(obsalertsilence.FieldMatcherJSON, field.TypeJSON, value)
	}
	if _u.mutation.MatcherJSONCleared() {
		_spec.ClearField(obsalertsilence.FieldMatcherJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(obsalertsilence.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(obsalertsilence.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(obsalertsilence.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(obsalertsilence.FieldCreatedBy, field.TypeInt, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(obsalertsilence.FieldCreatedBy, field.TypeInt)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{obsalertsilence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ObsAlertSilenceUpdateOne is the builder for updating a single ObsAlertSilence entity.
type ObsAlertSilenceUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ObsAlertSilenceMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ObsAlertSilenceUpdateOne) SetUpdatedAt(v time.Time) *ObsAlertSilenceUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetComment sets the "comment" field.
func (_u *ObsAlertSilenceUpdateOne) SetComment(v string) *ObsAlertSilenceUpdateOne {
	_u.mutation.SetComment(v)
	return _u
}

// SetNillableComment sets the "comment" field if the given value is not nil.
func (_u *ObsAlertSilenceUpdateOne) SetNillableComment(v *string) *ObsAlertSilenceUpdateOne {
	if v != nil {
		_u.SetComment(*v)
	}
	return _u
}

// ClearComment clears the value of the "comment" field.
func (_u *ObsAlertSilenceUpdateOne) ClearComment() *ObsAlertSilenceUpdateOne {
	_u.mutation.ClearComment()
	return _u
}

// SetMatcherJSON sets the "matcher_json" field.
func (_u *ObsAlertSilenceUpdateOne) SetMatcherJSON(v map[string]interface{}) *ObsAlertSilenceUpdateOne {
	_u.mutation.SetMatcherJSON(v)
	return _u
}

// ClearMatcherJSON clears the value of the "matcher_json" field.
func (_u *ObsAlertSilenceUpdateOne) ClearMatcherJSON() *ObsAlertSilenceUpdateOne {
	_u.mutation.ClearMatcherJSON()
	return _u
}

// SetStartsAt sets the "starts_at" field.
func (_u *ObsAlertSilenceUpdateOne) SetStartsAt(v time.Time) *ObsAlertSilenceUpdateOne {
	_u.mutation.SetStartsAt(v)
	return _u
}

// SetNillableStartsAt sets the "starts_at" field if the given value is not nil.
func (_u *ObsAlertSilenceUpdateOne) SetNillableStartsAt(v *time.Time) *ObsAlertSilenceUpdateOne {
	if v != nil {
		_u.SetStartsAt(*v)
	}
	return _u
}

// SetEndsAt sets the "ends_at" field.
func (_u *ObsAlertSilenceUpdateOne) SetEndsAt(v time.Time) *ObsAlertSilenceUpdateOne {
	_u.mutation.SetEndsAt(v)
	return _u
}

// SetNillableEndsAt sets the "ends_at" field if the given value is not nil.
func (_u *ObsAlertSilenceUpdateOne) SetNillableEndsAt(v *time.Time) *ObsAlertSilenceUpdateOne {
	if v != nil {
		_u.SetEndsAt(*v)
	}
	return _u
}

// SetCreatedBy sets the "created_by" field.
func (_u *ObsAlertSilenceUpdateOne) SetCreatedBy(v int) *ObsAlertSilenceUpdateOne {
	_u.mutation.ResetCreatedBy()
	_u.mutation.SetCreatedBy(v)
	return _u
}

// SetNillableCreatedBy sets the "created_by" field if the given value is not nil.
func (_u *ObsAlertSilenceUpdateOne) SetNillableCreatedBy(v *int) *ObsAlertSilenceUpdateOne {
	if v != nil {
		_u.SetCreatedBy(*v)
	}
	return _u
}

// AddCreatedBy adds value to the "created_by" field.
func (_u *ObsAlertSilenceUpdateOne) AddCreatedBy(v int) *ObsAlertSilenceUpdateOne {
	_u.mutation.AddCreatedBy(v)
	return _u
}

// ClearCreatedBy clears the value of the "created_by" field.
func (_u *ObsAlertSilenceUpdateOne) ClearCreatedBy() *ObsAlertSilenceUpdateOne {
	_u.mutation.ClearCreatedBy()
	return _u
}

// Mutation returns the ObsAlertSilenceMutation object of the builder.
func (_u *ObsAlertSilenceUpdateOne) Mutation() *ObsAlertSilenceMutation {
	return _u.mutation
}

// Where appends a list predicates to the ObsAlertSilenceUpdate builder.
func (_u *ObsAlertSilenceUpdateOne) Where(ps ...predicate.ObsAlertSilence) *ObsAlertSilenceUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ObsAlertSilenceUpdateOne) Select(field string, fields ...string) *ObsAlertSilenceUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ObsAlertSilence entity.
func (_u *ObsAlertSilenceUpdateOne) Save(ctx context.Context) (*ObsAlertSilence, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ObsAlertSilenceUpdateOne) SaveX(ctx context.Context) *ObsAlertSilence {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ObsAlertSilenceUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ObsAlertSilenceUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ObsAlertSilenceUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := obsalertsilence.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *ObsAlertSilenceUpdateOne) sqlSave(ctx context.Context) (_node *ObsAlertSilence, err error) {
	_spec := sqlgraph.NewUpdateSpec(obsalertsilence.Table, obsalertsilence.Columns, sqlgraph.NewFieldSpec(obsalertsilence.FieldID, field.TypeInt))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ObsAlertSilence.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, obsalertsilence.FieldID)
		for _, f := range fields {
			if !obsalertsilence.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != obsalertsilence.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(obsalertsilence.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Comment(); ok {
		_spec.SetField(obsalertsilence.FieldComment, field.TypeString, value)
	}
	if _u.mutation.CommentCleared() {
		_spec.ClearField(obsalertsilence.FieldComment, field.TypeString)
	}
	if value, ok := _u.mutation.MatcherJSON(); ok {
		_spec.SetField(obsalertsilence.FieldMatcherJSON, field.TypeJSON, value)
	}
	if _u.mutation.MatcherJSONCleared() {
		_spec.ClearField(obsalertsilence.FieldMatcherJSON, field.TypeJSON)
	}
	if value, ok := _u.mutation.StartsAt(); ok {
		_spec.SetField(obsalertsilence.FieldStartsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.EndsAt(); ok {
		_spec.SetField(obsalertsilence.FieldEndsAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.CreatedBy(); ok {
		_spec.SetField(obsalertsilence.FieldCreatedBy, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedCreatedBy(); ok {
		_spec.AddField(obsalertsilence.FieldCreatedBy, field.TypeInt, value)
	}
	if _u.mutation.CreatedByCleared() {
		_spec.ClearField(obsalertsilence.FieldCreatedBy, field.TypeInt)
	}
	_node = &ObsAlertSilence{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{obsalertsilence.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
