// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/pendingoauthsession"
)

// PendingOAuthSession is the model entity for the PendingOAuthSession schema.
type PendingOAuthSession struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// SessionTokenHash holds the value of the "session_token_hash" field.
	SessionTokenHash string `json:"-"`
	// Intent holds the value of the "intent" field.
	Intent string `json:"intent,omitempty"`
	// Provider holds the value of the "provider" field.
	Provider string `json:"provider,omitempty"`
	// ProviderKey holds the value of the "provider_key" field.
	ProviderKey string `json:"provider_key,omitempty"`
	// ProviderSubjectHash holds the value of the "provider_subject_hash" field.
	ProviderSubjectHash string `json:"-"`
	// SubjectHint holds the value of the "subject_hint" field.
	SubjectHint string `json:"subject_hint,omitempty"`
	// TargetUserID holds the value of the "target_user_id" field.
	TargetUserID *int `json:"target_user_id,omitempty"`
	// RedirectTo holds the value of the "redirect_to" field.
	RedirectTo string `json:"redirect_to,omitempty"`
	// ResolvedEmail holds the value of the "resolved_email" field.
	ResolvedEmail string `json:"resolved_email,omitempty"`
	// DisplayName holds the value of the "display_name" field.
	DisplayName string `json:"display_name,omitempty"`
	// EmailVerified holds the value of the "email_verified" field.
	EmailVerified bool `json:"email_verified,omitempty"`
	// AvatarURL holds the value of the "avatar_url" field.
	AvatarURL string `json:"avatar_url,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// ConsumedAt holds the value of the "consumed_at" field.
	ConsumedAt   *time.Time `json:"consumed_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PendingOAuthSession) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pendingoauthsession.FieldEmailVerified:
			values[i] = new(sql.NullBool)
		case pendingoauthsession.FieldID, pendingoauthsession.FieldTargetUserID:
			values[i] = new(sql.NullInt64)
		case pendingoauthsession.FieldSessionTokenHash, pendingoauthsession.FieldIntent, pendingoauthsession.FieldProvider, pendingoauthsession.FieldProviderKey, pendingoauthsession.FieldProviderSubjectHash, pendingoauthsession.FieldSubjectHint, pendingoauthsession.FieldRedirectTo, pendingoauthsession.FieldResolvedEmail, pendingoauthsession.FieldDisplayName, pendingoauthsession.FieldAvatarURL:
			values[i] = new(sql.NullString)
		case pendingoauthsession.FieldCreatedAt, pendingoauthsession.FieldUpdatedAt, pendingoauthsession.FieldExpiresAt, pendingoauthsession.FieldConsumedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PendingOAuthSession fields.
func (_m *PendingOAuthSession) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pendingoauthsession.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case pendingoauthsession.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case pendingoauthsession.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case pendingoauthsession.FieldSessionTokenHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field session_token_hash", values[i])
			} else if value.Valid {
				_m.SessionTokenHash = value.String
			}
		case pendingoauthsession.FieldIntent:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field intent", values[i])
			} else if value.Valid {
				_m.Intent = value.String
			}
		case pendingoauthsession.FieldProvider:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider", values[i])
			} else if value.Valid {
				_m.Provider = value.String
			}
		case pendingoauthsession.FieldProviderKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_key", values[i])
			} else if value.Valid {
				_m.ProviderKey = value.String
			}
		case pendingoauthsession.FieldProviderSubjectHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provider_subject_hash", values[i])
			} else if value.Valid {
				_m.ProviderSubjectHash = value.String
			}
		case pendingoauthsession.FieldSubjectHint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field subject_hint", values[i])
			} else if value.Valid {
				_m.SubjectHint = value.String
			}
		case pendingoauthsession.FieldTargetUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field target_user_id", values[i])
			} else if value.Valid {
				_m.TargetUserID = new(int)
				*_m.TargetUserID = int(value.Int64)
			}
		case pendingoauthsession.FieldRedirectTo:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field redirect_to", values[i])
			} else if value.Valid {
				_m.RedirectTo = value.String
			}
		case pendingoauthsession.FieldResolvedEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field resolved_email", values[i])
			} else if value.Valid {
				_m.ResolvedEmail = value.String
			}
		case pendingoauthsession.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field display_name", values[i])
			} else if value.Valid {
				_m.DisplayName = value.String
			}
		case pendingoauthsession.FieldEmailVerified:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field email_verified", values[i])
			} else if value.Valid {
				_m.EmailVerified = value.Bool
			}
		case pendingoauthsession.FieldAvatarURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatar_url", values[i])
			} else if value.Valid {
				_m.AvatarURL = value.String
			}
		case pendingoauthsession.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		case pendingoauthsession.FieldConsumedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field consumed_at", values[i])
			} else if value.Valid {
				_m.ConsumedAt = new(time.Time)
				*_m.ConsumedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PendingOAuthSession.
// This includes values selected through modifiers, order, etc.
func (_m *PendingOAuthSession) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this PendingOAuthSession.
// Note that you need to call PendingOAuthSession.Unwrap() before calling this method if this PendingOAuthSession
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PendingOAuthSession) Update() *PendingOAuthSessionUpdateOne {
	return NewPendingOAuthSessionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PendingOAuthSession entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PendingOAuthSession) Unwrap() *PendingOAuthSession {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PendingOAuthSession is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PendingOAuthSession) String() string {
	var builder strings.Builder
	builder.WriteString("PendingOAuthSession(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("session_token_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("intent=")
	builder.WriteString(_m.Intent)
	builder.WriteString(", ")
	builder.WriteString("provider=")
	builder.WriteString(_m.Provider)
	builder.WriteString(", ")
	builder.WriteString("provider_key=")
	builder.WriteString(_m.ProviderKey)
	builder.WriteString(", ")
	builder.WriteString("provider_subject_hash=<sensitive>")
	builder.WriteString(", ")
	builder.WriteString("subject_hint=")
	builder.WriteString(_m.SubjectHint)
	builder.WriteString(", ")
	if v := _m.TargetUserID; v != nil {
		builder.WriteString("target_user_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("redirect_to=")
	builder.WriteString(_m.RedirectTo)
	builder.WriteString(", ")
	builder.WriteString("resolved_email=")
	builder.WriteString(_m.ResolvedEmail)
	builder.WriteString(", ")
	builder.WriteString("display_name=")
	builder.WriteString(_m.DisplayName)
	builder.WriteString(", ")
	builder.WriteString("email_verified=")
	builder.WriteString(fmt.Sprintf("%v", _m.EmailVerified))
	builder.WriteString(", ")
	builder.WriteString("avatar_url=")
	builder.WriteString(_m.AvatarURL)
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.ConsumedAt; v != nil {
		builder.WriteString("consumed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// PendingOAuthSessions is a parsable slice of PendingOAuthSession.
type PendingOAuthSessions []*PendingOAuthSession
