// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/qualityevaluation"
)

// QualityEvaluation is the model entity for the QualityEvaluation schema.
type QualityEvaluation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FeedbackID holds the value of the "feedback_id" field.
	FeedbackID int `json:"feedback_id,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// DecisionID holds the value of the "decision_id" field.
	DecisionID int `json:"decision_id,omitempty"`
	// AttemptNo holds the value of the "attempt_no" field.
	AttemptNo int `json:"attempt_no,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int `json:"account_id,omitempty"`
	// ProviderID holds the value of the "provider_id" field.
	ProviderID int `json:"provider_id,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// SourceEndpoint holds the value of the "source_endpoint" field.
	SourceEndpoint string `json:"source_endpoint,omitempty"`
	// SampleRequestHash holds the value of the "sample_request_hash" field.
	SampleRequestHash string `json:"sample_request_hash,omitempty"`
	// JudgeModel holds the value of the "judge_model" field.
	JudgeModel string `json:"judge_model,omitempty"`
	// Score holds the value of the "score" field.
	Score float64 `json:"score,omitempty"`
	// RubricJSON holds the value of the "rubric_json" field.
	RubricJSON map[string]interface{} `json:"rubric_json,omitempty"`
	// JudgedAt holds the value of the "judged_at" field.
	JudgedAt     time.Time `json:"judged_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*QualityEvaluation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case qualityevaluation.FieldRubricJSON:
			values[i] = new([]byte)
		case qualityevaluation.FieldScore:
			values[i] = new(sql.NullFloat64)
		case qualityevaluation.FieldID, qualityevaluation.FieldFeedbackID, qualityevaluation.FieldDecisionID, qualityevaluation.FieldAttemptNo, qualityevaluation.FieldAccountID, qualityevaluation.FieldProviderID:
			values[i] = new(sql.NullInt64)
		case qualityevaluation.FieldRequestID, qualityevaluation.FieldModel, qualityevaluation.FieldSourceEndpoint, qualityevaluation.FieldSampleRequestHash, qualityevaluation.FieldJudgeModel:
			values[i] = new(sql.NullString)
		case qualityevaluation.FieldCreatedAt, qualityevaluation.FieldUpdatedAt, qualityevaluation.FieldJudgedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the QualityEvaluation fields.
func (_m *QualityEvaluation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case qualityevaluation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case qualityevaluation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case qualityevaluation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case qualityevaluation.FieldFeedbackID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field feedback_id", values[i])
			} else if value.Valid {
				_m.FeedbackID = int(value.Int64)
			}
		case qualityevaluation.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case qualityevaluation.FieldDecisionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field decision_id", values[i])
			} else if value.Valid {
				_m.DecisionID = int(value.Int64)
			}
		case qualityevaluation.FieldAttemptNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_no", values[i])
			} else if value.Valid {
				_m.AttemptNo = int(value.Int64)
			}
		case qualityevaluation.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = int(value.Int64)
			}
		case qualityevaluation.FieldProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field provider_id", values[i])
			} else if value.Valid {
				_m.ProviderID = int(value.Int64)
			}
		case qualityevaluation.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case qualityevaluation.FieldSourceEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_endpoint", values[i])
			} else if value.Valid {
				_m.SourceEndpoint = value.String
			}
		case qualityevaluation.FieldSampleRequestHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field sample_request_hash", values[i])
			} else if value.Valid {
				_m.SampleRequestHash = value.String
			}
		case qualityevaluation.FieldJudgeModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field judge_model", values[i])
			} else if value.Valid {
				_m.JudgeModel = value.String
			}
		case qualityevaluation.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = value.Float64
			}
		case qualityevaluation.FieldRubricJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field rubric_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RubricJSON); err != nil {
					return fmt.Errorf("unmarshal field rubric_json: %w", err)
				}
			}
		case qualityevaluation.FieldJudgedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field judged_at", values[i])
			} else if value.Valid {
				_m.JudgedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the QualityEvaluation.
// This includes values selected through modifiers, order, etc.
func (_m *QualityEvaluation) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this QualityEvaluation.
// Note that you need to call QualityEvaluation.Unwrap() before calling this method if this QualityEvaluation
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *QualityEvaluation) Update() *QualityEvaluationUpdateOne {
	return NewQualityEvaluationClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the QualityEvaluation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *QualityEvaluation) Unwrap() *QualityEvaluation {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: QualityEvaluation is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *QualityEvaluation) String() string {
	var builder strings.Builder
	builder.WriteString("QualityEvaluation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("feedback_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeedbackID))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("decision_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.DecisionID))
	builder.WriteString(", ")
	builder.WriteString("attempt_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNo))
	builder.WriteString(", ")
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("provider_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ProviderID))
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("source_endpoint=")
	builder.WriteString(_m.SourceEndpoint)
	builder.WriteString(", ")
	builder.WriteString("sample_request_hash=")
	builder.WriteString(_m.SampleRequestHash)
	builder.WriteString(", ")
	builder.WriteString("judge_model=")
	builder.WriteString(_m.JudgeModel)
	builder.WriteString(", ")
	builder.WriteString("score=")
	builder.WriteString(fmt.Sprintf("%v", _m.Score))
	builder.WriteString(", ")
	builder.WriteString("rubric_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.RubricJSON))
	builder.WriteString(", ")
	builder.WriteString("judged_at=")
	builder.WriteString(_m.JudgedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// QualityEvaluations is a parsable slice of QualityEvaluation.
type QualityEvaluations []*QualityEvaluation
