// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/schedulerdecision"
)

// SchedulerDecision is the model entity for the SchedulerDecision schema.
type SchedulerDecision struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// AttemptNo holds the value of the "attempt_no" field.
	AttemptNo int `json:"attempt_no,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int `json:"user_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int `json:"api_key_id,omitempty"`
	// SourceProtocol holds the value of the "source_protocol" field.
	SourceProtocol string `json:"source_protocol,omitempty"`
	// SourceEndpoint holds the value of the "source_endpoint" field.
	SourceEndpoint string `json:"source_endpoint,omitempty"`
	// TargetProtocol holds the value of the "target_protocol" field.
	TargetProtocol string `json:"target_protocol,omitempty"`
	// Model holds the value of the "model" field.
	Model string `json:"model,omitempty"`
	// Strategy holds the value of the "strategy" field.
	Strategy string `json:"strategy,omitempty"`
	// StrategyVersion holds the value of the "strategy_version" field.
	StrategyVersion string `json:"strategy_version,omitempty"`
	// StrategyConfigHash holds the value of the "strategy_config_hash" field.
	StrategyConfigHash string `json:"strategy_config_hash,omitempty"`
	// FallbackFromDecisionID holds the value of the "fallback_from_decision_id" field.
	FallbackFromDecisionID *int `json:"fallback_from_decision_id,omitempty"`
	// SelectedProviderID holds the value of the "selected_provider_id" field.
	SelectedProviderID *int `json:"selected_provider_id,omitempty"`
	// SelectedAccountID holds the value of the "selected_account_id" field.
	SelectedAccountID *int `json:"selected_account_id,omitempty"`
	// CandidateCount holds the value of the "candidate_count" field.
	CandidateCount int `json:"candidate_count,omitempty"`
	// RejectedCount holds the value of the "rejected_count" field.
	RejectedCount int `json:"rejected_count,omitempty"`
	// ScoresJSON holds the value of the "scores_json" field.
	ScoresJSON map[string]interface{} `json:"scores_json,omitempty"`
	// RejectReasonsJSON holds the value of the "reject_reasons_json" field.
	RejectReasonsJSON map[string]interface{} `json:"reject_reasons_json,omitempty"`
	// StrategyWeightsJSON holds the value of the "strategy_weights_json" field.
	StrategyWeightsJSON map[string]interface{} `json:"strategy_weights_json,omitempty"`
	// CompatibilityWarningsJSON holds the value of the "compatibility_warnings_json" field.
	CompatibilityWarningsJSON []string `json:"compatibility_warnings_json,omitempty"`
	// StickyHit holds the value of the "sticky_hit" field.
	StickyHit bool `json:"sticky_hit,omitempty"`
	// CacheAffinityHit holds the value of the "cache_affinity_hit" field.
	CacheAffinityHit bool `json:"cache_affinity_hit,omitempty"`
	// EstimatedCost holds the value of the "estimated_cost" field.
	EstimatedCost string `json:"estimated_cost,omitempty"`
	// Currency holds the value of the "currency" field.
	Currency     string `json:"currency,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SchedulerDecision) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case schedulerdecision.FieldScoresJSON, schedulerdecision.FieldRejectReasonsJSON, schedulerdecision.FieldStrategyWeightsJSON, schedulerdecision.FieldCompatibilityWarningsJSON:
			values[i] = new([]byte)
		case schedulerdecision.FieldStickyHit, schedulerdecision.FieldCacheAffinityHit:
			values[i] = new(sql.NullBool)
		case schedulerdecision.FieldID, schedulerdecision.FieldAttemptNo, schedulerdecision.FieldUserID, schedulerdecision.FieldAPIKeyID, schedulerdecision.FieldFallbackFromDecisionID, schedulerdecision.FieldSelectedProviderID, schedulerdecision.FieldSelectedAccountID, schedulerdecision.FieldCandidateCount, schedulerdecision.FieldRejectedCount:
			values[i] = new(sql.NullInt64)
		case schedulerdecision.FieldRequestID, schedulerdecision.FieldSourceProtocol, schedulerdecision.FieldSourceEndpoint, schedulerdecision.FieldTargetProtocol, schedulerdecision.FieldModel, schedulerdecision.FieldStrategy, schedulerdecision.FieldStrategyVersion, schedulerdecision.FieldStrategyConfigHash, schedulerdecision.FieldEstimatedCost, schedulerdecision.FieldCurrency:
			values[i] = new(sql.NullString)
		case schedulerdecision.FieldCreatedAt, schedulerdecision.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SchedulerDecision fields.
func (_m *SchedulerDecision) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case schedulerdecision.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case schedulerdecision.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case schedulerdecision.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case schedulerdecision.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case schedulerdecision.FieldAttemptNo:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field attempt_no", values[i])
			} else if value.Valid {
				_m.AttemptNo = int(value.Int64)
			}
		case schedulerdecision.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = int(value.Int64)
			}
		case schedulerdecision.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = int(value.Int64)
			}
		case schedulerdecision.FieldSourceProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_protocol", values[i])
			} else if value.Valid {
				_m.SourceProtocol = value.String
			}
		case schedulerdecision.FieldSourceEndpoint:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source_endpoint", values[i])
			} else if value.Valid {
				_m.SourceEndpoint = value.String
			}
		case schedulerdecision.FieldTargetProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field target_protocol", values[i])
			} else if value.Valid {
				_m.TargetProtocol = value.String
			}
		case schedulerdecision.FieldModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field model", values[i])
			} else if value.Valid {
				_m.Model = value.String
			}
		case schedulerdecision.FieldStrategy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strategy", values[i])
			} else if value.Valid {
				_m.Strategy = value.String
			}
		case schedulerdecision.FieldStrategyVersion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_version", values[i])
			} else if value.Valid {
				_m.StrategyVersion = value.String
			}
		case schedulerdecision.FieldStrategyConfigHash:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_config_hash", values[i])
			} else if value.Valid {
				_m.StrategyConfigHash = value.String
			}
		case schedulerdecision.FieldFallbackFromDecisionID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field fallback_from_decision_id", values[i])
			} else if value.Valid {
				_m.FallbackFromDecisionID = new(int)
				*_m.FallbackFromDecisionID = int(value.Int64)
			}
		case schedulerdecision.FieldSelectedProviderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field selected_provider_id", values[i])
			} else if value.Valid {
				_m.SelectedProviderID = new(int)
				*_m.SelectedProviderID = int(value.Int64)
			}
		case schedulerdecision.FieldSelectedAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field selected_account_id", values[i])
			} else if value.Valid {
				_m.SelectedAccountID = new(int)
				*_m.SelectedAccountID = int(value.Int64)
			}
		case schedulerdecision.FieldCandidateCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field candidate_count", values[i])
			} else if value.Valid {
				_m.CandidateCount = int(value.Int64)
			}
		case schedulerdecision.FieldRejectedCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field rejected_count", values[i])
			} else if value.Valid {
				_m.RejectedCount = int(value.Int64)
			}
		case schedulerdecision.FieldScoresJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field scores_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ScoresJSON); err != nil {
					return fmt.Errorf("unmarshal field scores_json: %w", err)
				}
			}
		case schedulerdecision.FieldRejectReasonsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field reject_reasons_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.RejectReasonsJSON); err != nil {
					return fmt.Errorf("unmarshal field reject_reasons_json: %w", err)
				}
			}
		case schedulerdecision.FieldStrategyWeightsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field strategy_weights_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.StrategyWeightsJSON); err != nil {
					return fmt.Errorf("unmarshal field strategy_weights_json: %w", err)
				}
			}
		case schedulerdecision.FieldCompatibilityWarningsJSON:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field compatibility_warnings_json", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.CompatibilityWarningsJSON); err != nil {
					return fmt.Errorf("unmarshal field compatibility_warnings_json: %w", err)
				}
			}
		case schedulerdecision.FieldStickyHit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sticky_hit", values[i])
			} else if value.Valid {
				_m.StickyHit = value.Bool
			}
		case schedulerdecision.FieldCacheAffinityHit:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field cache_affinity_hit", values[i])
			} else if value.Valid {
				_m.CacheAffinityHit = value.Bool
			}
		case schedulerdecision.FieldEstimatedCost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field estimated_cost", values[i])
			} else if value.Valid {
				_m.EstimatedCost = value.String
			}
		case schedulerdecision.FieldCurrency:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field currency", values[i])
			} else if value.Valid {
				_m.Currency = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SchedulerDecision.
// This includes values selected through modifiers, order, etc.
func (_m *SchedulerDecision) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SchedulerDecision.
// Note that you need to call SchedulerDecision.Unwrap() before calling this method if this SchedulerDecision
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SchedulerDecision) Update() *SchedulerDecisionUpdateOne {
	return NewSchedulerDecisionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SchedulerDecision entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SchedulerDecision) Unwrap() *SchedulerDecision {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SchedulerDecision is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SchedulerDecision) String() string {
	var builder strings.Builder
	builder.WriteString("SchedulerDecision(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("attempt_no=")
	builder.WriteString(fmt.Sprintf("%v", _m.AttemptNo))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("source_protocol=")
	builder.WriteString(_m.SourceProtocol)
	builder.WriteString(", ")
	builder.WriteString("source_endpoint=")
	builder.WriteString(_m.SourceEndpoint)
	builder.WriteString(", ")
	builder.WriteString("target_protocol=")
	builder.WriteString(_m.TargetProtocol)
	builder.WriteString(", ")
	builder.WriteString("model=")
	builder.WriteString(_m.Model)
	builder.WriteString(", ")
	builder.WriteString("strategy=")
	builder.WriteString(_m.Strategy)
	builder.WriteString(", ")
	builder.WriteString("strategy_version=")
	builder.WriteString(_m.StrategyVersion)
	builder.WriteString(", ")
	builder.WriteString("strategy_config_hash=")
	builder.WriteString(_m.StrategyConfigHash)
	builder.WriteString(", ")
	if v := _m.FallbackFromDecisionID; v != nil {
		builder.WriteString("fallback_from_decision_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SelectedProviderID; v != nil {
		builder.WriteString("selected_provider_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SelectedAccountID; v != nil {
		builder.WriteString("selected_account_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("candidate_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.CandidateCount))
	builder.WriteString(", ")
	builder.WriteString("rejected_count=")
	builder.WriteString(fmt.Sprintf("%v", _m.RejectedCount))
	builder.WriteString(", ")
	builder.WriteString("scores_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.ScoresJSON))
	builder.WriteString(", ")
	builder.WriteString("reject_reasons_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.RejectReasonsJSON))
	builder.WriteString(", ")
	builder.WriteString("strategy_weights_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.StrategyWeightsJSON))
	builder.WriteString(", ")
	builder.WriteString("compatibility_warnings_json=")
	builder.WriteString(fmt.Sprintf("%v", _m.CompatibilityWarningsJSON))
	builder.WriteString(", ")
	builder.WriteString("sticky_hit=")
	builder.WriteString(fmt.Sprintf("%v", _m.StickyHit))
	builder.WriteString(", ")
	builder.WriteString("cache_affinity_hit=")
	builder.WriteString(fmt.Sprintf("%v", _m.CacheAffinityHit))
	builder.WriteString(", ")
	builder.WriteString("estimated_cost=")
	builder.WriteString(_m.EstimatedCost)
	builder.WriteString(", ")
	builder.WriteString("currency=")
	builder.WriteString(_m.Currency)
	builder.WriteByte(')')
	return builder.String()
}

// SchedulerDecisions is a parsable slice of SchedulerDecision.
type SchedulerDecisions []*SchedulerDecision
