// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/scheduledtestplan"
)

// ScheduledTestPlan is the model entity for the ScheduledTestPlan schema.
type ScheduledTestPlan struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Enabled holds the value of the "enabled" field.
	Enabled bool `json:"enabled,omitempty"`
	// ScopeType holds the value of the "scope_type" field.
	ScopeType string `json:"scope_type,omitempty"`
	// ScopeID holds the value of the "scope_id" field.
	ScopeID *int `json:"scope_id,omitempty"`
	// IntervalSeconds holds the value of the "interval_seconds" field.
	IntervalSeconds int `json:"interval_seconds,omitempty"`
	// CronExpression holds the value of the "cron_expression" field.
	CronExpression string `json:"cron_expression,omitempty"`
	// MaxResults holds the value of the "max_results" field.
	MaxResults int `json:"max_results,omitempty"`
	// AutoRecover holds the value of the "auto_recover" field.
	AutoRecover bool `json:"auto_recover,omitempty"`
	// LastRunAt holds the value of the "last_run_at" field.
	LastRunAt *time.Time `json:"last_run_at,omitempty"`
	// LastStatus holds the value of the "last_status" field.
	LastStatus string `json:"last_status,omitempty"`
	// LastSummary holds the value of the "last_summary" field.
	LastSummary  string `json:"last_summary,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ScheduledTestPlan) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case scheduledtestplan.FieldEnabled, scheduledtestplan.FieldAutoRecover:
			values[i] = new(sql.NullBool)
		case scheduledtestplan.FieldID, scheduledtestplan.FieldScopeID, scheduledtestplan.FieldIntervalSeconds, scheduledtestplan.FieldMaxResults:
			values[i] = new(sql.NullInt64)
		case scheduledtestplan.FieldName, scheduledtestplan.FieldScopeType, scheduledtestplan.FieldCronExpression, scheduledtestplan.FieldLastStatus, scheduledtestplan.FieldLastSummary:
			values[i] = new(sql.NullString)
		case scheduledtestplan.FieldCreatedAt, scheduledtestplan.FieldUpdatedAt, scheduledtestplan.FieldLastRunAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ScheduledTestPlan fields.
func (_m *ScheduledTestPlan) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case scheduledtestplan.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case scheduledtestplan.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case scheduledtestplan.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case scheduledtestplan.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case scheduledtestplan.FieldEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field enabled", values[i])
			} else if value.Valid {
				_m.Enabled = value.Bool
			}
		case scheduledtestplan.FieldScopeType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope_type", values[i])
			} else if value.Valid {
				_m.ScopeType = value.String
			}
		case scheduledtestplan.FieldScopeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field scope_id", values[i])
			} else if value.Valid {
				_m.ScopeID = new(int)
				*_m.ScopeID = int(value.Int64)
			}
		case scheduledtestplan.FieldIntervalSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field interval_seconds", values[i])
			} else if value.Valid {
				_m.IntervalSeconds = int(value.Int64)
			}
		case scheduledtestplan.FieldCronExpression:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cron_expression", values[i])
			} else if value.Valid {
				_m.CronExpression = value.String
			}
		case scheduledtestplan.FieldMaxResults:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field max_results", values[i])
			} else if value.Valid {
				_m.MaxResults = int(value.Int64)
			}
		case scheduledtestplan.FieldAutoRecover:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_recover", values[i])
			} else if value.Valid {
				_m.AutoRecover = value.Bool
			}
		case scheduledtestplan.FieldLastRunAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_run_at", values[i])
			} else if value.Valid {
				_m.LastRunAt = new(time.Time)
				*_m.LastRunAt = value.Time
			}
		case scheduledtestplan.FieldLastStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_status", values[i])
			} else if value.Valid {
				_m.LastStatus = value.String
			}
		case scheduledtestplan.FieldLastSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_summary", values[i])
			} else if value.Valid {
				_m.LastSummary = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ScheduledTestPlan.
// This includes values selected through modifiers, order, etc.
func (_m *ScheduledTestPlan) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ScheduledTestPlan.
// Note that you need to call ScheduledTestPlan.Unwrap() before calling this method if this ScheduledTestPlan
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ScheduledTestPlan) Update() *ScheduledTestPlanUpdateOne {
	return NewScheduledTestPlanClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ScheduledTestPlan entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ScheduledTestPlan) Unwrap() *ScheduledTestPlan {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ScheduledTestPlan is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ScheduledTestPlan) String() string {
	var builder strings.Builder
	builder.WriteString("ScheduledTestPlan(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.Enabled))
	builder.WriteString(", ")
	builder.WriteString("scope_type=")
	builder.WriteString(_m.ScopeType)
	builder.WriteString(", ")
	if v := _m.ScopeID; v != nil {
		builder.WriteString("scope_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("interval_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.IntervalSeconds))
	builder.WriteString(", ")
	builder.WriteString("cron_expression=")
	builder.WriteString(_m.CronExpression)
	builder.WriteString(", ")
	builder.WriteString("max_results=")
	builder.WriteString(fmt.Sprintf("%v", _m.MaxResults))
	builder.WriteString(", ")
	builder.WriteString("auto_recover=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoRecover))
	builder.WriteString(", ")
	if v := _m.LastRunAt; v != nil {
		builder.WriteString("last_run_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("last_status=")
	builder.WriteString(_m.LastStatus)
	builder.WriteString(", ")
	builder.WriteString("last_summary=")
	builder.WriteString(_m.LastSummary)
	builder.WriteByte(')')
	return builder.String()
}

// ScheduledTestPlans is a parsable slice of ScheduledTestPlan.
type ScheduledTestPlans []*ScheduledTestPlan
