// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/srapi/srapi/apps/api/ent/setting"
)

// SettingCreate is the builder for creating a Setting entity.
type SettingCreate struct {
	config
	mutation *SettingMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *SettingCreate) SetCreatedAt(v time.Time) *SettingCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SettingCreate) SetNillableCreatedAt(v *time.Time) *SettingCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SettingCreate) SetUpdatedAt(v time.Time) *SettingCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SettingCreate) SetNillableUpdatedAt(v *time.Time) *SettingCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetKey sets the "key" field.
func (_c *SettingCreate) SetKey(v string) *SettingCreate {
	_c.mutation.SetKey(v)
	return _c
}

// SetValueJSON sets the "value_json" field.
func (_c *SettingCreate) SetValueJSON(v map[string]interface{}) *SettingCreate {
	_c.mutation.SetValueJSON(v)
	return _c
}

// SetValueCiphertext sets the "value_ciphertext" field.
func (_c *SettingCreate) SetValueCiphertext(v []byte) *SettingCreate {
	_c.mutation.SetValueCiphertext(v)
	return _c
}

// SetIsSecret sets the "is_secret" field.
func (_c *SettingCreate) SetIsSecret(v bool) *SettingCreate {
	_c.mutation.SetIsSecret(v)
	return _c
}

// SetNillableIsSecret sets the "is_secret" field if the given value is not nil.
func (_c *SettingCreate) SetNillableIsSecret(v *bool) *SettingCreate {
	if v != nil {
		_c.SetIsSecret(*v)
	}
	return _c
}

// SetDescription sets the "description" field.
func (_c *SettingCreate) SetDescription(v string) *SettingCreate {
	_c.mutation.SetDescription(v)
	return _c
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_c *SettingCreate) SetNillableDescription(v *string) *SettingCreate {
	if v != nil {
		_c.SetDescription(*v)
	}
	return _c
}

// SetUpdatedBy sets the "updated_by" field.
func (_c *SettingCreate) SetUpdatedBy(v int) *SettingCreate {
	_c.mutation.SetUpdatedBy(v)
	return _c
}

// SetNillableUpdatedBy sets the "updated_by" field if the given value is not nil.
func (_c *SettingCreate) SetNillableUpdatedBy(v *int) *SettingCreate {
	if v != nil {
		_c.SetUpdatedBy(*v)
	}
	return _c
}

// Mutation returns the SettingMutation object of the builder.
func (_c *SettingCreate) Mutation() *SettingMutation {
	return _c.mutation
}

// Save creates the Setting in the database.
func (_c *SettingCreate) Save(ctx context.Context) (*Setting, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SettingCreate) SaveX(ctx context.Context) *Setting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SettingCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := setting.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := setting.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.IsSecret(); !ok {
		v := setting.DefaultIsSecret
		_c.mutation.SetIsSecret(v)
	}
	if _, ok := _c.mutation.Description(); !ok {
		v := setting.DefaultDescription
		_c.mutation.SetDescription(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SettingCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Setting.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Setting.updated_at"`)}
	}
	if _, ok := _c.mutation.Key(); !ok {
		return &ValidationError{Name: "key", err: errors.New(`ent: missing required field "Setting.key"`)}
	}
	if v, ok := _c.mutation.Key(); ok {
		if err := setting.KeyValidator(v); err != nil {
			return &ValidationError{Name: "key", err: fmt.Errorf(`ent: validator failed for field "Setting.key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsSecret(); !ok {
		return &ValidationError{Name: "is_secret", err: errors.New(`ent: missing required field "Setting.is_secret"`)}
	}
	if _, ok := _c.mutation.Description(); !ok {
		return &ValidationError{Name: "description", err: errors.New(`ent: missing required field "Setting.description"`)}
	}
	return nil
}

func (_c *SettingCreate) sqlSave(ctx context.Context) (*Setting, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SettingCreate) createSpec() (*Setting, *sqlgraph.CreateSpec) {
	var (
		_node = &Setting{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(setting.Table, sqlgraph.NewFieldSpec(setting.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(setting.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(setting.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Key(); ok {
		_spec.SetField(setting.FieldKey, field.TypeString, value)
		_node.Key = value
	}
	if value, ok := _c.mutation.ValueJSON(); ok {
		_spec.SetField(setting.FieldValueJSON, field.TypeJSON, value)
		_node.ValueJSON = value
	}
	if value, ok := _c.mutation.ValueCiphertext(); ok {
		_spec.SetField(setting.FieldValueCiphertext, field.TypeBytes, value)
		_node.ValueCiphertext = value
	}
	if value, ok := _c.mutation.IsSecret(); ok {
		_spec.SetField(setting.FieldIsSecret, field.TypeBool, value)
		_node.IsSecret = value
	}
	if value, ok := _c.mutation.Description(); ok {
		_spec.SetField(setting.FieldDescription, field.TypeString, value)
		_node.Description = value
	}
	if value, ok := _c.mutation.UpdatedBy(); ok {
		_spec.SetField(setting.FieldUpdatedBy, field.TypeInt, value)
		_node.UpdatedBy = &value
	}
	return _node, _spec
}

// SettingCreateBulk is the builder for creating many Setting entities in bulk.
type SettingCreateBulk struct {
	config
	err      error
	builders []*SettingCreate
}

// Save creates the Setting entities in the database.
func (_c *SettingCreateBulk) Save(ctx context.Context) ([]*Setting, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Setting, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SettingMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SettingCreateBulk) SaveX(ctx context.Context) []*Setting {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SettingCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SettingCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
