// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/srapi/srapi/apps/api/ent/userauthidentity"
)

// UserAuthIdentityCreate is the builder for creating a UserAuthIdentity entity.
type UserAuthIdentityCreate struct {
	config
	mutation *UserAuthIdentityMutation
	hooks    []Hook
}

// SetCreatedAt sets the "created_at" field.
func (_c *UserAuthIdentityCreate) SetCreatedAt(v time.Time) *UserAuthIdentityCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableCreatedAt(v *time.Time) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *UserAuthIdentityCreate) SetUpdatedAt(v time.Time) *UserAuthIdentityCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableUpdatedAt(v *time.Time) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *UserAuthIdentityCreate) SetDeletedAt(v time.Time) *UserAuthIdentityCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableDeletedAt(v *time.Time) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *UserAuthIdentityCreate) SetUserID(v int) *UserAuthIdentityCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetProvider sets the "provider" field.
func (_c *UserAuthIdentityCreate) SetProvider(v string) *UserAuthIdentityCreate {
	_c.mutation.SetProvider(v)
	return _c
}

// SetProviderKey sets the "provider_key" field.
func (_c *UserAuthIdentityCreate) SetProviderKey(v string) *UserAuthIdentityCreate {
	_c.mutation.SetProviderKey(v)
	return _c
}

// SetProviderSubjectHash sets the "provider_subject_hash" field.
func (_c *UserAuthIdentityCreate) SetProviderSubjectHash(v string) *UserAuthIdentityCreate {
	_c.mutation.SetProviderSubjectHash(v)
	return _c
}

// SetSubjectHint sets the "subject_hint" field.
func (_c *UserAuthIdentityCreate) SetSubjectHint(v string) *UserAuthIdentityCreate {
	_c.mutation.SetSubjectHint(v)
	return _c
}

// SetNillableSubjectHint sets the "subject_hint" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableSubjectHint(v *string) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetSubjectHint(*v)
	}
	return _c
}

// SetDisplayName sets the "display_name" field.
func (_c *UserAuthIdentityCreate) SetDisplayName(v string) *UserAuthIdentityCreate {
	_c.mutation.SetDisplayName(v)
	return _c
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableDisplayName(v *string) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetDisplayName(*v)
	}
	return _c
}

// SetEmail sets the "email" field.
func (_c *UserAuthIdentityCreate) SetEmail(v string) *UserAuthIdentityCreate {
	_c.mutation.SetEmail(v)
	return _c
}

// SetNillableEmail sets the "email" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableEmail(v *string) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetEmail(*v)
	}
	return _c
}

// SetEmailVerified sets the "email_verified" field.
func (_c *UserAuthIdentityCreate) SetEmailVerified(v bool) *UserAuthIdentityCreate {
	_c.mutation.SetEmailVerified(v)
	return _c
}

// SetNillableEmailVerified sets the "email_verified" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableEmailVerified(v *bool) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetEmailVerified(*v)
	}
	return _c
}

// SetAvatarURL sets the "avatar_url" field.
func (_c *UserAuthIdentityCreate) SetAvatarURL(v string) *UserAuthIdentityCreate {
	_c.mutation.SetAvatarURL(v)
	return _c
}

// SetNillableAvatarURL sets the "avatar_url" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableAvatarURL(v *string) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetAvatarURL(*v)
	}
	return _c
}

// SetVerifiedAt sets the "verified_at" field.
func (_c *UserAuthIdentityCreate) SetVerifiedAt(v time.Time) *UserAuthIdentityCreate {
	_c.mutation.SetVerifiedAt(v)
	return _c
}

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableVerifiedAt(v *time.Time) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetVerifiedAt(*v)
	}
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *UserAuthIdentityCreate) SetLastUsedAt(v time.Time) *UserAuthIdentityCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *UserAuthIdentityCreate) SetNillableLastUsedAt(v *time.Time) *UserAuthIdentityCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// Mutation returns the UserAuthIdentityMutation object of the builder.
func (_c *UserAuthIdentityCreate) Mutation() *UserAuthIdentityMutation {
	return _c.mutation
}

// Save creates the UserAuthIdentity in the database.
func (_c *UserAuthIdentityCreate) Save(ctx context.Context) (*UserAuthIdentity, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *UserAuthIdentityCreate) SaveX(ctx context.Context) *UserAuthIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAuthIdentityCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAuthIdentityCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *UserAuthIdentityCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := userauthidentity.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := userauthidentity.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.SubjectHint(); !ok {
		v := userauthidentity.DefaultSubjectHint
		_c.mutation.SetSubjectHint(v)
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		v := userauthidentity.DefaultDisplayName
		_c.mutation.SetDisplayName(v)
	}
	if _, ok := _c.mutation.Email(); !ok {
		v := userauthidentity.DefaultEmail
		_c.mutation.SetEmail(v)
	}
	if _, ok := _c.mutation.EmailVerified(); !ok {
		v := userauthidentity.DefaultEmailVerified
		_c.mutation.SetEmailVerified(v)
	}
	if _, ok := _c.mutation.AvatarURL(); !ok {
		v := userauthidentity.DefaultAvatarURL
		_c.mutation.SetAvatarURL(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *UserAuthIdentityCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "UserAuthIdentity.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "UserAuthIdentity.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "UserAuthIdentity.user_id"`)}
	}
	if _, ok := _c.mutation.Provider(); !ok {
		return &ValidationError{Name: "provider", err: errors.New(`ent: missing required field "UserAuthIdentity.provider"`)}
	}
	if v, ok := _c.mutation.Provider(); ok {
		if err := userauthidentity.ProviderValidator(v); err != nil {
			return &ValidationError{Name: "provider", err: fmt.Errorf(`ent: validator failed for field "UserAuthIdentity.provider": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderKey(); !ok {
		return &ValidationError{Name: "provider_key", err: errors.New(`ent: missing required field "UserAuthIdentity.provider_key"`)}
	}
	if v, ok := _c.mutation.ProviderKey(); ok {
		if err := userauthidentity.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "UserAuthIdentity.provider_key": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ProviderSubjectHash(); !ok {
		return &ValidationError{Name: "provider_subject_hash", err: errors.New(`ent: missing required field "UserAuthIdentity.provider_subject_hash"`)}
	}
	if v, ok := _c.mutation.ProviderSubjectHash(); ok {
		if err := userauthidentity.ProviderSubjectHashValidator(v); err != nil {
			return &ValidationError{Name: "provider_subject_hash", err: fmt.Errorf(`ent: validator failed for field "UserAuthIdentity.provider_subject_hash": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SubjectHint(); !ok {
		return &ValidationError{Name: "subject_hint", err: errors.New(`ent: missing required field "UserAuthIdentity.subject_hint"`)}
	}
	if _, ok := _c.mutation.DisplayName(); !ok {
		return &ValidationError{Name: "display_name", err: errors.New(`ent: missing required field "UserAuthIdentity.display_name"`)}
	}
	if _, ok := _c.mutation.Email(); !ok {
		return &ValidationError{Name: "email", err: errors.New(`ent: missing required field "UserAuthIdentity.email"`)}
	}
	if _, ok := _c.mutation.EmailVerified(); !ok {
		return &ValidationError{Name: "email_verified", err: errors.New(`ent: missing required field "UserAuthIdentity.email_verified"`)}
	}
	if _, ok := _c.mutation.AvatarURL(); !ok {
		return &ValidationError{Name: "avatar_url", err: errors.New(`ent: missing required field "UserAuthIdentity.avatar_url"`)}
	}
	return nil
}

func (_c *UserAuthIdentityCreate) sqlSave(ctx context.Context) (*UserAuthIdentity, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *UserAuthIdentityCreate) createSpec() (*UserAuthIdentity, *sqlgraph.CreateSpec) {
	var (
		_node = &UserAuthIdentity{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(userauthidentity.Table, sqlgraph.NewFieldSpec(userauthidentity.FieldID, field.TypeInt))
	)
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(userauthidentity.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(userauthidentity.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(userauthidentity.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	if value, ok := _c.mutation.UserID(); ok {
		_spec.SetField(userauthidentity.FieldUserID, field.TypeInt, value)
		_node.UserID = value
	}
	if value, ok := _c.mutation.Provider(); ok {
		_spec.SetField(userauthidentity.FieldProvider, field.TypeString, value)
		_node.Provider = value
	}
	if value, ok := _c.mutation.ProviderKey(); ok {
		_spec.SetField(userauthidentity.FieldProviderKey, field.TypeString, value)
		_node.ProviderKey = value
	}
	if value, ok := _c.mutation.ProviderSubjectHash(); ok {
		_spec.SetField(userauthidentity.FieldProviderSubjectHash, field.TypeString, value)
		_node.ProviderSubjectHash = value
	}
	if value, ok := _c.mutation.SubjectHint(); ok {
		_spec.SetField(userauthidentity.FieldSubjectHint, field.TypeString, value)
		_node.SubjectHint = value
	}
	if value, ok := _c.mutation.DisplayName(); ok {
		_spec.SetField(userauthidentity.FieldDisplayName, field.TypeString, value)
		_node.DisplayName = value
	}
	if value, ok := _c.mutation.Email(); ok {
		_spec.SetField(userauthidentity.FieldEmail, field.TypeString, value)
		_node.Email = value
	}
	if value, ok := _c.mutation.EmailVerified(); ok {
		_spec.SetField(userauthidentity.FieldEmailVerified, field.TypeBool, value)
		_node.EmailVerified = value
	}
	if value, ok := _c.mutation.AvatarURL(); ok {
		_spec.SetField(userauthidentity.FieldAvatarURL, field.TypeString, value)
		_node.AvatarURL = value
	}
	if value, ok := _c.mutation.VerifiedAt(); ok {
		_spec.SetField(userauthidentity.FieldVerifiedAt, field.TypeTime, value)
		_node.VerifiedAt = &value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(userauthidentity.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	return _node, _spec
}

// UserAuthIdentityCreateBulk is the builder for creating many UserAuthIdentity entities in bulk.
type UserAuthIdentityCreateBulk struct {
	config
	err      error
	builders []*UserAuthIdentityCreate
}

// Save creates the UserAuthIdentity entities in the database.
func (_c *UserAuthIdentityCreateBulk) Save(ctx context.Context) ([]*UserAuthIdentity, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*UserAuthIdentity, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*UserAuthIdentityMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *UserAuthIdentityCreateBulk) SaveX(ctx context.Context) []*UserAuthIdentity {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *UserAuthIdentityCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *UserAuthIdentityCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
