// Code generated by ent, DO NOT EDIT.

package tlsfingerprintprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldName, v))
}

// TLSTemplate applies equality check predicate on the "tls_template" field. It's identical to TLSTemplateEQ.
func TLSTemplate(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldTLSTemplate, v))
}

// HTTPVersionPolicy applies equality check predicate on the "http_version_policy" field. It's identical to HTTPVersionPolicyEQ.
func HTTPVersionPolicy(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldHTTPVersionPolicy, v))
}

// UserAgent applies equality check predicate on the "user_agent" field. It's identical to UserAgentEQ.
func UserAgent(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldUserAgent, v))
}

// Enabled applies equality check predicate on the "enabled" field. It's identical to EnabledEQ.
func Enabled(v bool) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldEnabled, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldContainsFold(FieldName, v))
}

// TLSTemplateEQ applies the EQ predicate on the "tls_template" field.
func TLSTemplateEQ(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldTLSTemplate, v))
}

// TLSTemplateNEQ applies the NEQ predicate on the "tls_template" field.
func TLSTemplateNEQ(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNEQ(FieldTLSTemplate, v))
}

// TLSTemplateIn applies the In predicate on the "tls_template" field.
func TLSTemplateIn(vs ...string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldIn(FieldTLSTemplate, vs...))
}

// TLSTemplateNotIn applies the NotIn predicate on the "tls_template" field.
func TLSTemplateNotIn(vs ...string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNotIn(FieldTLSTemplate, vs...))
}

// TLSTemplateGT applies the GT predicate on the "tls_template" field.
func TLSTemplateGT(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGT(FieldTLSTemplate, v))
}

// TLSTemplateGTE applies the GTE predicate on the "tls_template" field.
func TLSTemplateGTE(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGTE(FieldTLSTemplate, v))
}

// TLSTemplateLT applies the LT predicate on the "tls_template" field.
func TLSTemplateLT(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLT(FieldTLSTemplate, v))
}

// TLSTemplateLTE applies the LTE predicate on the "tls_template" field.
func TLSTemplateLTE(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLTE(FieldTLSTemplate, v))
}

// TLSTemplateContains applies the Contains predicate on the "tls_template" field.
func TLSTemplateContains(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldContains(FieldTLSTemplate, v))
}

// TLSTemplateHasPrefix applies the HasPrefix predicate on the "tls_template" field.
func TLSTemplateHasPrefix(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldHasPrefix(FieldTLSTemplate, v))
}

// TLSTemplateHasSuffix applies the HasSuffix predicate on the "tls_template" field.
func TLSTemplateHasSuffix(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldHasSuffix(FieldTLSTemplate, v))
}

// TLSTemplateEqualFold applies the EqualFold predicate on the "tls_template" field.
func TLSTemplateEqualFold(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEqualFold(FieldTLSTemplate, v))
}

// TLSTemplateContainsFold applies the ContainsFold predicate on the "tls_template" field.
func TLSTemplateContainsFold(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldContainsFold(FieldTLSTemplate, v))
}

// HTTPVersionPolicyEQ applies the EQ predicate on the "http_version_policy" field.
func HTTPVersionPolicyEQ(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyNEQ applies the NEQ predicate on the "http_version_policy" field.
func HTTPVersionPolicyNEQ(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNEQ(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyIn applies the In predicate on the "http_version_policy" field.
func HTTPVersionPolicyIn(vs ...string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldIn(FieldHTTPVersionPolicy, vs...))
}

// HTTPVersionPolicyNotIn applies the NotIn predicate on the "http_version_policy" field.
func HTTPVersionPolicyNotIn(vs ...string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNotIn(FieldHTTPVersionPolicy, vs...))
}

// HTTPVersionPolicyGT applies the GT predicate on the "http_version_policy" field.
func HTTPVersionPolicyGT(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGT(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyGTE applies the GTE predicate on the "http_version_policy" field.
func HTTPVersionPolicyGTE(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGTE(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyLT applies the LT predicate on the "http_version_policy" field.
func HTTPVersionPolicyLT(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLT(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyLTE applies the LTE predicate on the "http_version_policy" field.
func HTTPVersionPolicyLTE(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLTE(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyContains applies the Contains predicate on the "http_version_policy" field.
func HTTPVersionPolicyContains(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldContains(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyHasPrefix applies the HasPrefix predicate on the "http_version_policy" field.
func HTTPVersionPolicyHasPrefix(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldHasPrefix(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyHasSuffix applies the HasSuffix predicate on the "http_version_policy" field.
func HTTPVersionPolicyHasSuffix(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldHasSuffix(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyEqualFold applies the EqualFold predicate on the "http_version_policy" field.
func HTTPVersionPolicyEqualFold(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEqualFold(FieldHTTPVersionPolicy, v))
}

// HTTPVersionPolicyContainsFold applies the ContainsFold predicate on the "http_version_policy" field.
func HTTPVersionPolicyContainsFold(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldContainsFold(FieldHTTPVersionPolicy, v))
}

// UserAgentEQ applies the EQ predicate on the "user_agent" field.
func UserAgentEQ(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldUserAgent, v))
}

// UserAgentNEQ applies the NEQ predicate on the "user_agent" field.
func UserAgentNEQ(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNEQ(FieldUserAgent, v))
}

// UserAgentIn applies the In predicate on the "user_agent" field.
func UserAgentIn(vs ...string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldIn(FieldUserAgent, vs...))
}

// UserAgentNotIn applies the NotIn predicate on the "user_agent" field.
func UserAgentNotIn(vs ...string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNotIn(FieldUserAgent, vs...))
}

// UserAgentGT applies the GT predicate on the "user_agent" field.
func UserAgentGT(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGT(FieldUserAgent, v))
}

// UserAgentGTE applies the GTE predicate on the "user_agent" field.
func UserAgentGTE(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldGTE(FieldUserAgent, v))
}

// UserAgentLT applies the LT predicate on the "user_agent" field.
func UserAgentLT(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLT(FieldUserAgent, v))
}

// UserAgentLTE applies the LTE predicate on the "user_agent" field.
func UserAgentLTE(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldLTE(FieldUserAgent, v))
}

// UserAgentContains applies the Contains predicate on the "user_agent" field.
func UserAgentContains(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldContains(FieldUserAgent, v))
}

// UserAgentHasPrefix applies the HasPrefix predicate on the "user_agent" field.
func UserAgentHasPrefix(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldHasPrefix(FieldUserAgent, v))
}

// UserAgentHasSuffix applies the HasSuffix predicate on the "user_agent" field.
func UserAgentHasSuffix(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldHasSuffix(FieldUserAgent, v))
}

// UserAgentEqualFold applies the EqualFold predicate on the "user_agent" field.
func UserAgentEqualFold(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEqualFold(FieldUserAgent, v))
}

// UserAgentContainsFold applies the ContainsFold predicate on the "user_agent" field.
func UserAgentContainsFold(v string) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldContainsFold(FieldUserAgent, v))
}

// ExtraHeadersIsNil applies the IsNil predicate on the "extra_headers" field.
func ExtraHeadersIsNil() predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldIsNull(FieldExtraHeaders))
}

// ExtraHeadersNotNil applies the NotNil predicate on the "extra_headers" field.
func ExtraHeadersNotNil() predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNotNull(FieldExtraHeaders))
}

// EnabledEQ applies the EQ predicate on the "enabled" field.
func EnabledEQ(v bool) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldEQ(FieldEnabled, v))
}

// EnabledNEQ applies the NEQ predicate on the "enabled" field.
func EnabledNEQ(v bool) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.FieldNEQ(FieldEnabled, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.TLSFingerprintProfile) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.TLSFingerprintProfile) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.TLSFingerprintProfile) predicate.TLSFingerprintProfile {
	return predicate.TLSFingerprintProfile(sql.NotPredicates(p))
}
