-- Create "account_group_rate_limits" table
CREATE TABLE "account_group_rate_limits" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "account_group_id" bigint NOT NULL,
  "rpm_limit" bigint NOT NULL DEFAULT 0,
  "enabled" boolean NOT NULL DEFAULT true,
  PRIMARY KEY ("id")
);
-- Create index "accountgroupratelimit_account_group_id" to table: "account_group_rate_limits"
CREATE UNIQUE INDEX "accountgroupratelimit_account_group_id" ON "account_group_rate_limits" ("account_group_id");
-- Create index "accountgroupratelimit_enabled" to table: "account_group_rate_limits"
CREATE INDEX "accountgroupratelimit_enabled" ON "account_group_rate_limits" ("enabled");
