-- Create "backup_snapshots" table to track database backup history. The daily
-- backup worker writes one row per attempted snapshot (status=running ->
-- success|failed) so operators can list past snapshots, see the kind/size/
-- checksum, download a backup, or delete one. Previously the only history
-- signal was admin_settings.backup.last_backup_at, which collapsed everything
-- into a single timestamp with no visibility.
CREATE TABLE "backup_snapshots" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "created_at" timestamptz NOT NULL,
  "updated_at" timestamptz NOT NULL,
  "kind" character varying NOT NULL DEFAULT 'scheduled',
  "started_at" timestamptz NOT NULL,
  "completed_at" timestamptz NULL,
  "size_bytes" bigint NOT NULL DEFAULT 0,
  "sha256" character varying NOT NULL DEFAULT '',
  "status" character varying NOT NULL DEFAULT 'running',
  "file_path" character varying NOT NULL DEFAULT '',
  "error_message" character varying NOT NULL DEFAULT '',
  "triggered_by_user_id" bigint NOT NULL DEFAULT 0,
  PRIMARY KEY ("id")
);
-- Create index "backupsnapshot_started_at" to table: "backup_snapshots"
CREATE INDEX "backupsnapshot_started_at" ON "backup_snapshots" ("started_at");
-- Create index "backupsnapshot_status" to table: "backup_snapshots"
CREATE INDEX "backupsnapshot_status" ON "backup_snapshots" ("status");
