// Code generated by ent, DO NOT EDIT.

package obsalertevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the obsalertevent type in the database.
	Label = "obs_alert_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldSloID holds the string denoting the slo_id field in the database.
	FieldSloID = "slo_id"
	// FieldRuleID holds the string denoting the rule_id field in the database.
	FieldRuleID = "rule_id"
	// FieldSeverity holds the string denoting the severity field in the database.
	FieldSeverity = "severity"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFingerprint holds the string denoting the fingerprint field in the database.
	FieldFingerprint = "fingerprint"
	// FieldSummary holds the string denoting the summary field in the database.
	FieldSummary = "summary"
	// FieldDetailsJSON holds the string denoting the details_json field in the database.
	FieldDetailsJSON = "details_json"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldResolvedAt holds the string denoting the resolved_at field in the database.
	FieldResolvedAt = "resolved_at"
	// FieldAcknowledgedAt holds the string denoting the acknowledged_at field in the database.
	FieldAcknowledgedAt = "acknowledged_at"
	// FieldAcknowledgedBy holds the string denoting the acknowledged_by field in the database.
	FieldAcknowledgedBy = "acknowledged_by"
	// FieldSuppressedBy holds the string denoting the suppressed_by field in the database.
	FieldSuppressedBy = "suppressed_by"
	// Table holds the table name of the obsalertevent in the database.
	Table = "obs_alert_events"
)

// Columns holds all SQL columns for obsalertevent fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldSloID,
	FieldRuleID,
	FieldSeverity,
	FieldStatus,
	FieldFingerprint,
	FieldSummary,
	FieldDetailsJSON,
	FieldStartedAt,
	FieldResolvedAt,
	FieldAcknowledgedAt,
	FieldAcknowledgedBy,
	FieldSuppressedBy,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// RuleIDValidator is a validator for the "rule_id" field. It is called by the builders before save.
	RuleIDValidator func(string) error
	// DefaultSeverity holds the default value on creation for the "severity" field.
	DefaultSeverity string
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// FingerprintValidator is a validator for the "fingerprint" field. It is called by the builders before save.
	FingerprintValidator func(string) error
	// SummaryValidator is a validator for the "summary" field. It is called by the builders before save.
	SummaryValidator func(string) error
)

// OrderOption defines the ordering options for the ObsAlertEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySloID orders the results by the slo_id field.
func BySloID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSloID, opts...).ToFunc()
}

// ByRuleID orders the results by the rule_id field.
func ByRuleID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRuleID, opts...).ToFunc()
}

// BySeverity orders the results by the severity field.
func BySeverity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeverity, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFingerprint orders the results by the fingerprint field.
func ByFingerprint(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFingerprint, opts...).ToFunc()
}

// BySummary orders the results by the summary field.
func BySummary(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSummary, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByResolvedAt orders the results by the resolved_at field.
func ByResolvedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldResolvedAt, opts...).ToFunc()
}

// ByAcknowledgedAt orders the results by the acknowledged_at field.
func ByAcknowledgedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcknowledgedAt, opts...).ToFunc()
}

// ByAcknowledgedBy orders the results by the acknowledged_by field.
func ByAcknowledgedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAcknowledgedBy, opts...).ToFunc()
}

// BySuppressedBy orders the results by the suppressed_by field.
func BySuppressedBy(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSuppressedBy, opts...).ToFunc()
}
