// Code generated by ent, DO NOT EDIT.

package usersubscription

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the usersubscription type in the database.
	Label = "user_subscription"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldPlanID holds the string denoting the plan_id field in the database.
	FieldPlanID = "plan_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStartsAt holds the string denoting the starts_at field in the database.
	FieldStartsAt = "starts_at"
	// FieldExpiresAt holds the string denoting the expires_at field in the database.
	FieldExpiresAt = "expires_at"
	// FieldEntitlementsSnapshotJSON holds the string denoting the entitlements_snapshot_json field in the database.
	FieldEntitlementsSnapshotJSON = "entitlements_snapshot_json"
	// FieldSourceType holds the string denoting the source_type field in the database.
	FieldSourceType = "source_type"
	// FieldSourceID holds the string denoting the source_id field in the database.
	FieldSourceID = "source_id"
	// FieldDailyUsageUsd holds the string denoting the daily_usage_usd field in the database.
	FieldDailyUsageUsd = "daily_usage_usd"
	// FieldDailyUsageWindowStart holds the string denoting the daily_usage_window_start field in the database.
	FieldDailyUsageWindowStart = "daily_usage_window_start"
	// FieldWeeklyUsageUsd holds the string denoting the weekly_usage_usd field in the database.
	FieldWeeklyUsageUsd = "weekly_usage_usd"
	// FieldWeeklyUsageWindowStart holds the string denoting the weekly_usage_window_start field in the database.
	FieldWeeklyUsageWindowStart = "weekly_usage_window_start"
	// FieldMonthlyUsageUsd holds the string denoting the monthly_usage_usd field in the database.
	FieldMonthlyUsageUsd = "monthly_usage_usd"
	// FieldMonthlyUsageWindowStart holds the string denoting the monthly_usage_window_start field in the database.
	FieldMonthlyUsageWindowStart = "monthly_usage_window_start"
	// Table holds the table name of the usersubscription in the database.
	Table = "user_subscriptions"
)

// Columns holds all SQL columns for usersubscription fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldPlanID,
	FieldStatus,
	FieldStartsAt,
	FieldExpiresAt,
	FieldEntitlementsSnapshotJSON,
	FieldSourceType,
	FieldSourceID,
	FieldDailyUsageUsd,
	FieldDailyUsageWindowStart,
	FieldWeeklyUsageUsd,
	FieldWeeklyUsageWindowStart,
	FieldMonthlyUsageUsd,
	FieldMonthlyUsageWindowStart,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultSourceType holds the default value on creation for the "source_type" field.
	DefaultSourceType string
	// DefaultSourceID holds the default value on creation for the "source_id" field.
	DefaultSourceID string
	// DefaultDailyUsageUsd holds the default value on creation for the "daily_usage_usd" field.
	DefaultDailyUsageUsd string
	// DefaultWeeklyUsageUsd holds the default value on creation for the "weekly_usage_usd" field.
	DefaultWeeklyUsageUsd string
	// DefaultMonthlyUsageUsd holds the default value on creation for the "monthly_usage_usd" field.
	DefaultMonthlyUsageUsd string
)

// OrderOption defines the ordering options for the UserSubscription queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByPlanID orders the results by the plan_id field.
func ByPlanID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPlanID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStartsAt orders the results by the starts_at field.
func ByStartsAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartsAt, opts...).ToFunc()
}

// ByExpiresAt orders the results by the expires_at field.
func ByExpiresAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExpiresAt, opts...).ToFunc()
}

// BySourceType orders the results by the source_type field.
func BySourceType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceType, opts...).ToFunc()
}

// BySourceID orders the results by the source_id field.
func BySourceID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSourceID, opts...).ToFunc()
}

// ByDailyUsageUsd orders the results by the daily_usage_usd field.
func ByDailyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyUsageUsd, opts...).ToFunc()
}

// ByDailyUsageWindowStart orders the results by the daily_usage_window_start field.
func ByDailyUsageWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailyUsageWindowStart, opts...).ToFunc()
}

// ByWeeklyUsageUsd orders the results by the weekly_usage_usd field.
func ByWeeklyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyUsageUsd, opts...).ToFunc()
}

// ByWeeklyUsageWindowStart orders the results by the weekly_usage_window_start field.
func ByWeeklyUsageWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyUsageWindowStart, opts...).ToFunc()
}

// ByMonthlyUsageUsd orders the results by the monthly_usage_usd field.
func ByMonthlyUsageUsd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyUsageUsd, opts...).ToFunc()
}

// ByMonthlyUsageWindowStart orders the results by the monthly_usage_window_start field.
func ByMonthlyUsageWindowStart(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMonthlyUsageWindowStart, opts...).ToFunc()
}
