// Code generated by ent, DO NOT EDIT.

package inviterelationship

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the inviterelationship type in the database.
	Label = "invite_relationship"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldInviterUserID holds the string denoting the inviter_user_id field in the database.
	FieldInviterUserID = "inviter_user_id"
	// FieldInviteeUserID holds the string denoting the invitee_user_id field in the database.
	FieldInviteeUserID = "invitee_user_id"
	// FieldInviteCodeID holds the string denoting the invite_code_id field in the database.
	FieldInviteCodeID = "invite_code_id"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFirstPaidAt holds the string denoting the first_paid_at field in the database.
	FieldFirstPaidAt = "first_paid_at"
	// Table holds the table name of the inviterelationship in the database.
	Table = "invite_relationships"
)

// Columns holds all SQL columns for inviterelationship fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldInviterUserID,
	FieldInviteeUserID,
	FieldInviteCodeID,
	FieldStatus,
	FieldFirstPaidAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
)

// OrderOption defines the ordering options for the InviteRelationship queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByInviterUserID orders the results by the inviter_user_id field.
func ByInviterUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviterUserID, opts...).ToFunc()
}

// ByInviteeUserID orders the results by the invitee_user_id field.
func ByInviteeUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteeUserID, opts...).ToFunc()
}

// ByInviteCodeID orders the results by the invite_code_id field.
func ByInviteCodeID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldInviteCodeID, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFirstPaidAt orders the results by the first_paid_at field.
func ByFirstPaidAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFirstPaidAt, opts...).ToFunc()
}
