// Code generated by ent, DO NOT EDIT.

package obsalertsilence

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldUpdatedAt, v))
}

// Comment applies equality check predicate on the "comment" field. It's identical to CommentEQ.
func Comment(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldComment, v))
}

// StartsAt applies equality check predicate on the "starts_at" field. It's identical to StartsAtEQ.
func StartsAt(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldStartsAt, v))
}

// EndsAt applies equality check predicate on the "ends_at" field. It's identical to EndsAtEQ.
func EndsAt(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldEndsAt, v))
}

// CreatedBy applies equality check predicate on the "created_by" field. It's identical to CreatedByEQ.
func CreatedBy(v int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLTE(FieldUpdatedAt, v))
}

// CommentEQ applies the EQ predicate on the "comment" field.
func CommentEQ(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldComment, v))
}

// CommentNEQ applies the NEQ predicate on the "comment" field.
func CommentNEQ(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNEQ(FieldComment, v))
}

// CommentIn applies the In predicate on the "comment" field.
func CommentIn(vs ...string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIn(FieldComment, vs...))
}

// CommentNotIn applies the NotIn predicate on the "comment" field.
func CommentNotIn(vs ...string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotIn(FieldComment, vs...))
}

// CommentGT applies the GT predicate on the "comment" field.
func CommentGT(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGT(FieldComment, v))
}

// CommentGTE applies the GTE predicate on the "comment" field.
func CommentGTE(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGTE(FieldComment, v))
}

// CommentLT applies the LT predicate on the "comment" field.
func CommentLT(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLT(FieldComment, v))
}

// CommentLTE applies the LTE predicate on the "comment" field.
func CommentLTE(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLTE(FieldComment, v))
}

// CommentContains applies the Contains predicate on the "comment" field.
func CommentContains(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldContains(FieldComment, v))
}

// CommentHasPrefix applies the HasPrefix predicate on the "comment" field.
func CommentHasPrefix(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldHasPrefix(FieldComment, v))
}

// CommentHasSuffix applies the HasSuffix predicate on the "comment" field.
func CommentHasSuffix(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldHasSuffix(FieldComment, v))
}

// CommentIsNil applies the IsNil predicate on the "comment" field.
func CommentIsNil() predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIsNull(FieldComment))
}

// CommentNotNil applies the NotNil predicate on the "comment" field.
func CommentNotNil() predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotNull(FieldComment))
}

// CommentEqualFold applies the EqualFold predicate on the "comment" field.
func CommentEqualFold(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEqualFold(FieldComment, v))
}

// CommentContainsFold applies the ContainsFold predicate on the "comment" field.
func CommentContainsFold(v string) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldContainsFold(FieldComment, v))
}

// MatcherJSONIsNil applies the IsNil predicate on the "matcher_json" field.
func MatcherJSONIsNil() predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIsNull(FieldMatcherJSON))
}

// MatcherJSONNotNil applies the NotNil predicate on the "matcher_json" field.
func MatcherJSONNotNil() predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotNull(FieldMatcherJSON))
}

// StartsAtEQ applies the EQ predicate on the "starts_at" field.
func StartsAtEQ(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldStartsAt, v))
}

// StartsAtNEQ applies the NEQ predicate on the "starts_at" field.
func StartsAtNEQ(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNEQ(FieldStartsAt, v))
}

// StartsAtIn applies the In predicate on the "starts_at" field.
func StartsAtIn(vs ...time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIn(FieldStartsAt, vs...))
}

// StartsAtNotIn applies the NotIn predicate on the "starts_at" field.
func StartsAtNotIn(vs ...time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotIn(FieldStartsAt, vs...))
}

// StartsAtGT applies the GT predicate on the "starts_at" field.
func StartsAtGT(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGT(FieldStartsAt, v))
}

// StartsAtGTE applies the GTE predicate on the "starts_at" field.
func StartsAtGTE(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGTE(FieldStartsAt, v))
}

// StartsAtLT applies the LT predicate on the "starts_at" field.
func StartsAtLT(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLT(FieldStartsAt, v))
}

// StartsAtLTE applies the LTE predicate on the "starts_at" field.
func StartsAtLTE(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLTE(FieldStartsAt, v))
}

// EndsAtEQ applies the EQ predicate on the "ends_at" field.
func EndsAtEQ(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldEndsAt, v))
}

// EndsAtNEQ applies the NEQ predicate on the "ends_at" field.
func EndsAtNEQ(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNEQ(FieldEndsAt, v))
}

// EndsAtIn applies the In predicate on the "ends_at" field.
func EndsAtIn(vs ...time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIn(FieldEndsAt, vs...))
}

// EndsAtNotIn applies the NotIn predicate on the "ends_at" field.
func EndsAtNotIn(vs ...time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotIn(FieldEndsAt, vs...))
}

// EndsAtGT applies the GT predicate on the "ends_at" field.
func EndsAtGT(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGT(FieldEndsAt, v))
}

// EndsAtGTE applies the GTE predicate on the "ends_at" field.
func EndsAtGTE(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGTE(FieldEndsAt, v))
}

// EndsAtLT applies the LT predicate on the "ends_at" field.
func EndsAtLT(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLT(FieldEndsAt, v))
}

// EndsAtLTE applies the LTE predicate on the "ends_at" field.
func EndsAtLTE(v time.Time) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLTE(FieldEndsAt, v))
}

// CreatedByEQ applies the EQ predicate on the "created_by" field.
func CreatedByEQ(v int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldEQ(FieldCreatedBy, v))
}

// CreatedByNEQ applies the NEQ predicate on the "created_by" field.
func CreatedByNEQ(v int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNEQ(FieldCreatedBy, v))
}

// CreatedByIn applies the In predicate on the "created_by" field.
func CreatedByIn(vs ...int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIn(FieldCreatedBy, vs...))
}

// CreatedByNotIn applies the NotIn predicate on the "created_by" field.
func CreatedByNotIn(vs ...int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotIn(FieldCreatedBy, vs...))
}

// CreatedByGT applies the GT predicate on the "created_by" field.
func CreatedByGT(v int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGT(FieldCreatedBy, v))
}

// CreatedByGTE applies the GTE predicate on the "created_by" field.
func CreatedByGTE(v int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldGTE(FieldCreatedBy, v))
}

// CreatedByLT applies the LT predicate on the "created_by" field.
func CreatedByLT(v int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLT(FieldCreatedBy, v))
}

// CreatedByLTE applies the LTE predicate on the "created_by" field.
func CreatedByLTE(v int) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldLTE(FieldCreatedBy, v))
}

// CreatedByIsNil applies the IsNil predicate on the "created_by" field.
func CreatedByIsNil() predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldIsNull(FieldCreatedBy))
}

// CreatedByNotNil applies the NotNil predicate on the "created_by" field.
func CreatedByNotNil() predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.FieldNotNull(FieldCreatedBy))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ObsAlertSilence) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ObsAlertSilence) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ObsAlertSilence) predicate.ObsAlertSilence {
	return predicate.ObsAlertSilence(sql.NotPredicates(p))
}
