// Code generated by ent, DO NOT EDIT.

package userredeemcoderedemption

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/srapi/srapi/apps/api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldUserID, v))
}

// RedeemCodeID applies equality check predicate on the "redeem_code_id" field. It's identical to RedeemCodeIDEQ.
func RedeemCodeID(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldRedeemCodeID, v))
}

// CodeDigest applies equality check predicate on the "code_digest" field. It's identical to CodeDigestEQ.
func CodeDigest(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldCodeDigest, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldType, v))
}

// Amount applies equality check predicate on the "amount" field. It's identical to AmountEQ.
func Amount(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldAmount, v))
}

// Currency applies equality check predicate on the "currency" field. It's identical to CurrencyEQ.
func Currency(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldCurrency, v))
}

// BalanceBefore applies equality check predicate on the "balance_before" field. It's identical to BalanceBeforeEQ.
func BalanceBefore(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceAfter applies equality check predicate on the "balance_after" field. It's identical to BalanceAfterEQ.
func BalanceAfter(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldBalanceAfter, v))
}

// BillingLedgerID applies equality check predicate on the "billing_ledger_id" field. It's identical to BillingLedgerIDEQ.
func BillingLedgerID(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldBillingLedgerID, v))
}

// UserSubscriptionID applies equality check predicate on the "user_subscription_id" field. It's identical to UserSubscriptionIDEQ.
func UserSubscriptionID(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldUserSubscriptionID, v))
}

// RedeemedAt applies equality check predicate on the "redeemed_at" field. It's identical to RedeemedAtEQ.
func RedeemedAt(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldRedeemedAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldUserID, vs...))
}

// UserIDGT applies the GT predicate on the "user_id" field.
func UserIDGT(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldUserID, v))
}

// UserIDGTE applies the GTE predicate on the "user_id" field.
func UserIDGTE(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldUserID, v))
}

// UserIDLT applies the LT predicate on the "user_id" field.
func UserIDLT(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldUserID, v))
}

// UserIDLTE applies the LTE predicate on the "user_id" field.
func UserIDLTE(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldUserID, v))
}

// RedeemCodeIDEQ applies the EQ predicate on the "redeem_code_id" field.
func RedeemCodeIDEQ(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDNEQ applies the NEQ predicate on the "redeem_code_id" field.
func RedeemCodeIDNEQ(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldRedeemCodeID, v))
}

// RedeemCodeIDIn applies the In predicate on the "redeem_code_id" field.
func RedeemCodeIDIn(vs ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDNotIn applies the NotIn predicate on the "redeem_code_id" field.
func RedeemCodeIDNotIn(vs ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldRedeemCodeID, vs...))
}

// RedeemCodeIDGT applies the GT predicate on the "redeem_code_id" field.
func RedeemCodeIDGT(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldRedeemCodeID, v))
}

// RedeemCodeIDGTE applies the GTE predicate on the "redeem_code_id" field.
func RedeemCodeIDGTE(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldRedeemCodeID, v))
}

// RedeemCodeIDLT applies the LT predicate on the "redeem_code_id" field.
func RedeemCodeIDLT(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldRedeemCodeID, v))
}

// RedeemCodeIDLTE applies the LTE predicate on the "redeem_code_id" field.
func RedeemCodeIDLTE(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldRedeemCodeID, v))
}

// CodeDigestEQ applies the EQ predicate on the "code_digest" field.
func CodeDigestEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldCodeDigest, v))
}

// CodeDigestNEQ applies the NEQ predicate on the "code_digest" field.
func CodeDigestNEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldCodeDigest, v))
}

// CodeDigestIn applies the In predicate on the "code_digest" field.
func CodeDigestIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldCodeDigest, vs...))
}

// CodeDigestNotIn applies the NotIn predicate on the "code_digest" field.
func CodeDigestNotIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldCodeDigest, vs...))
}

// CodeDigestGT applies the GT predicate on the "code_digest" field.
func CodeDigestGT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldCodeDigest, v))
}

// CodeDigestGTE applies the GTE predicate on the "code_digest" field.
func CodeDigestGTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldCodeDigest, v))
}

// CodeDigestLT applies the LT predicate on the "code_digest" field.
func CodeDigestLT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldCodeDigest, v))
}

// CodeDigestLTE applies the LTE predicate on the "code_digest" field.
func CodeDigestLTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldCodeDigest, v))
}

// CodeDigestContains applies the Contains predicate on the "code_digest" field.
func CodeDigestContains(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContains(FieldCodeDigest, v))
}

// CodeDigestHasPrefix applies the HasPrefix predicate on the "code_digest" field.
func CodeDigestHasPrefix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasPrefix(FieldCodeDigest, v))
}

// CodeDigestHasSuffix applies the HasSuffix predicate on the "code_digest" field.
func CodeDigestHasSuffix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasSuffix(FieldCodeDigest, v))
}

// CodeDigestEqualFold applies the EqualFold predicate on the "code_digest" field.
func CodeDigestEqualFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEqualFold(FieldCodeDigest, v))
}

// CodeDigestContainsFold applies the ContainsFold predicate on the "code_digest" field.
func CodeDigestContainsFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContainsFold(FieldCodeDigest, v))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContainsFold(FieldType, v))
}

// AmountEQ applies the EQ predicate on the "amount" field.
func AmountEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldAmount, v))
}

// AmountNEQ applies the NEQ predicate on the "amount" field.
func AmountNEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldAmount, v))
}

// AmountIn applies the In predicate on the "amount" field.
func AmountIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldAmount, vs...))
}

// AmountNotIn applies the NotIn predicate on the "amount" field.
func AmountNotIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldAmount, vs...))
}

// AmountGT applies the GT predicate on the "amount" field.
func AmountGT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldAmount, v))
}

// AmountGTE applies the GTE predicate on the "amount" field.
func AmountGTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldAmount, v))
}

// AmountLT applies the LT predicate on the "amount" field.
func AmountLT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldAmount, v))
}

// AmountLTE applies the LTE predicate on the "amount" field.
func AmountLTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldAmount, v))
}

// AmountContains applies the Contains predicate on the "amount" field.
func AmountContains(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContains(FieldAmount, v))
}

// AmountHasPrefix applies the HasPrefix predicate on the "amount" field.
func AmountHasPrefix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasPrefix(FieldAmount, v))
}

// AmountHasSuffix applies the HasSuffix predicate on the "amount" field.
func AmountHasSuffix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasSuffix(FieldAmount, v))
}

// AmountEqualFold applies the EqualFold predicate on the "amount" field.
func AmountEqualFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEqualFold(FieldAmount, v))
}

// AmountContainsFold applies the ContainsFold predicate on the "amount" field.
func AmountContainsFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContainsFold(FieldAmount, v))
}

// CurrencyEQ applies the EQ predicate on the "currency" field.
func CurrencyEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldCurrency, v))
}

// CurrencyNEQ applies the NEQ predicate on the "currency" field.
func CurrencyNEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldCurrency, v))
}

// CurrencyIn applies the In predicate on the "currency" field.
func CurrencyIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldCurrency, vs...))
}

// CurrencyNotIn applies the NotIn predicate on the "currency" field.
func CurrencyNotIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldCurrency, vs...))
}

// CurrencyGT applies the GT predicate on the "currency" field.
func CurrencyGT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldCurrency, v))
}

// CurrencyGTE applies the GTE predicate on the "currency" field.
func CurrencyGTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldCurrency, v))
}

// CurrencyLT applies the LT predicate on the "currency" field.
func CurrencyLT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldCurrency, v))
}

// CurrencyLTE applies the LTE predicate on the "currency" field.
func CurrencyLTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldCurrency, v))
}

// CurrencyContains applies the Contains predicate on the "currency" field.
func CurrencyContains(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContains(FieldCurrency, v))
}

// CurrencyHasPrefix applies the HasPrefix predicate on the "currency" field.
func CurrencyHasPrefix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasPrefix(FieldCurrency, v))
}

// CurrencyHasSuffix applies the HasSuffix predicate on the "currency" field.
func CurrencyHasSuffix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasSuffix(FieldCurrency, v))
}

// CurrencyEqualFold applies the EqualFold predicate on the "currency" field.
func CurrencyEqualFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEqualFold(FieldCurrency, v))
}

// CurrencyContainsFold applies the ContainsFold predicate on the "currency" field.
func CurrencyContainsFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContainsFold(FieldCurrency, v))
}

// BalanceBeforeEQ applies the EQ predicate on the "balance_before" field.
func BalanceBeforeEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldBalanceBefore, v))
}

// BalanceBeforeNEQ applies the NEQ predicate on the "balance_before" field.
func BalanceBeforeNEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldBalanceBefore, v))
}

// BalanceBeforeIn applies the In predicate on the "balance_before" field.
func BalanceBeforeIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeNotIn applies the NotIn predicate on the "balance_before" field.
func BalanceBeforeNotIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldBalanceBefore, vs...))
}

// BalanceBeforeGT applies the GT predicate on the "balance_before" field.
func BalanceBeforeGT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldBalanceBefore, v))
}

// BalanceBeforeGTE applies the GTE predicate on the "balance_before" field.
func BalanceBeforeGTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldBalanceBefore, v))
}

// BalanceBeforeLT applies the LT predicate on the "balance_before" field.
func BalanceBeforeLT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldBalanceBefore, v))
}

// BalanceBeforeLTE applies the LTE predicate on the "balance_before" field.
func BalanceBeforeLTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldBalanceBefore, v))
}

// BalanceBeforeContains applies the Contains predicate on the "balance_before" field.
func BalanceBeforeContains(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContains(FieldBalanceBefore, v))
}

// BalanceBeforeHasPrefix applies the HasPrefix predicate on the "balance_before" field.
func BalanceBeforeHasPrefix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasPrefix(FieldBalanceBefore, v))
}

// BalanceBeforeHasSuffix applies the HasSuffix predicate on the "balance_before" field.
func BalanceBeforeHasSuffix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasSuffix(FieldBalanceBefore, v))
}

// BalanceBeforeEqualFold applies the EqualFold predicate on the "balance_before" field.
func BalanceBeforeEqualFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEqualFold(FieldBalanceBefore, v))
}

// BalanceBeforeContainsFold applies the ContainsFold predicate on the "balance_before" field.
func BalanceBeforeContainsFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContainsFold(FieldBalanceBefore, v))
}

// BalanceAfterEQ applies the EQ predicate on the "balance_after" field.
func BalanceAfterEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldBalanceAfter, v))
}

// BalanceAfterNEQ applies the NEQ predicate on the "balance_after" field.
func BalanceAfterNEQ(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldBalanceAfter, v))
}

// BalanceAfterIn applies the In predicate on the "balance_after" field.
func BalanceAfterIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldBalanceAfter, vs...))
}

// BalanceAfterNotIn applies the NotIn predicate on the "balance_after" field.
func BalanceAfterNotIn(vs ...string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldBalanceAfter, vs...))
}

// BalanceAfterGT applies the GT predicate on the "balance_after" field.
func BalanceAfterGT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldBalanceAfter, v))
}

// BalanceAfterGTE applies the GTE predicate on the "balance_after" field.
func BalanceAfterGTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldBalanceAfter, v))
}

// BalanceAfterLT applies the LT predicate on the "balance_after" field.
func BalanceAfterLT(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldBalanceAfter, v))
}

// BalanceAfterLTE applies the LTE predicate on the "balance_after" field.
func BalanceAfterLTE(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldBalanceAfter, v))
}

// BalanceAfterContains applies the Contains predicate on the "balance_after" field.
func BalanceAfterContains(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContains(FieldBalanceAfter, v))
}

// BalanceAfterHasPrefix applies the HasPrefix predicate on the "balance_after" field.
func BalanceAfterHasPrefix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasPrefix(FieldBalanceAfter, v))
}

// BalanceAfterHasSuffix applies the HasSuffix predicate on the "balance_after" field.
func BalanceAfterHasSuffix(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldHasSuffix(FieldBalanceAfter, v))
}

// BalanceAfterEqualFold applies the EqualFold predicate on the "balance_after" field.
func BalanceAfterEqualFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEqualFold(FieldBalanceAfter, v))
}

// BalanceAfterContainsFold applies the ContainsFold predicate on the "balance_after" field.
func BalanceAfterContainsFold(v string) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldContainsFold(FieldBalanceAfter, v))
}

// BillingLedgerIDEQ applies the EQ predicate on the "billing_ledger_id" field.
func BillingLedgerIDEQ(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldBillingLedgerID, v))
}

// BillingLedgerIDNEQ applies the NEQ predicate on the "billing_ledger_id" field.
func BillingLedgerIDNEQ(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldBillingLedgerID, v))
}

// BillingLedgerIDIn applies the In predicate on the "billing_ledger_id" field.
func BillingLedgerIDIn(vs ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldBillingLedgerID, vs...))
}

// BillingLedgerIDNotIn applies the NotIn predicate on the "billing_ledger_id" field.
func BillingLedgerIDNotIn(vs ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldBillingLedgerID, vs...))
}

// BillingLedgerIDGT applies the GT predicate on the "billing_ledger_id" field.
func BillingLedgerIDGT(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldBillingLedgerID, v))
}

// BillingLedgerIDGTE applies the GTE predicate on the "billing_ledger_id" field.
func BillingLedgerIDGTE(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldBillingLedgerID, v))
}

// BillingLedgerIDLT applies the LT predicate on the "billing_ledger_id" field.
func BillingLedgerIDLT(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldBillingLedgerID, v))
}

// BillingLedgerIDLTE applies the LTE predicate on the "billing_ledger_id" field.
func BillingLedgerIDLTE(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldBillingLedgerID, v))
}

// BillingLedgerIDIsNil applies the IsNil predicate on the "billing_ledger_id" field.
func BillingLedgerIDIsNil() predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIsNull(FieldBillingLedgerID))
}

// BillingLedgerIDNotNil applies the NotNil predicate on the "billing_ledger_id" field.
func BillingLedgerIDNotNil() predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotNull(FieldBillingLedgerID))
}

// UserSubscriptionIDEQ applies the EQ predicate on the "user_subscription_id" field.
func UserSubscriptionIDEQ(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDNEQ applies the NEQ predicate on the "user_subscription_id" field.
func UserSubscriptionIDNEQ(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDIn applies the In predicate on the "user_subscription_id" field.
func UserSubscriptionIDIn(vs ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldUserSubscriptionID, vs...))
}

// UserSubscriptionIDNotIn applies the NotIn predicate on the "user_subscription_id" field.
func UserSubscriptionIDNotIn(vs ...int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldUserSubscriptionID, vs...))
}

// UserSubscriptionIDGT applies the GT predicate on the "user_subscription_id" field.
func UserSubscriptionIDGT(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDGTE applies the GTE predicate on the "user_subscription_id" field.
func UserSubscriptionIDGTE(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDLT applies the LT predicate on the "user_subscription_id" field.
func UserSubscriptionIDLT(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDLTE applies the LTE predicate on the "user_subscription_id" field.
func UserSubscriptionIDLTE(v int) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldUserSubscriptionID, v))
}

// UserSubscriptionIDIsNil applies the IsNil predicate on the "user_subscription_id" field.
func UserSubscriptionIDIsNil() predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIsNull(FieldUserSubscriptionID))
}

// UserSubscriptionIDNotNil applies the NotNil predicate on the "user_subscription_id" field.
func UserSubscriptionIDNotNil() predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotNull(FieldUserSubscriptionID))
}

// RedeemedAtEQ applies the EQ predicate on the "redeemed_at" field.
func RedeemedAtEQ(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldEQ(FieldRedeemedAt, v))
}

// RedeemedAtNEQ applies the NEQ predicate on the "redeemed_at" field.
func RedeemedAtNEQ(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNEQ(FieldRedeemedAt, v))
}

// RedeemedAtIn applies the In predicate on the "redeemed_at" field.
func RedeemedAtIn(vs ...time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIn(FieldRedeemedAt, vs...))
}

// RedeemedAtNotIn applies the NotIn predicate on the "redeemed_at" field.
func RedeemedAtNotIn(vs ...time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotIn(FieldRedeemedAt, vs...))
}

// RedeemedAtGT applies the GT predicate on the "redeemed_at" field.
func RedeemedAtGT(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGT(FieldRedeemedAt, v))
}

// RedeemedAtGTE applies the GTE predicate on the "redeemed_at" field.
func RedeemedAtGTE(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldGTE(FieldRedeemedAt, v))
}

// RedeemedAtLT applies the LT predicate on the "redeemed_at" field.
func RedeemedAtLT(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLT(FieldRedeemedAt, v))
}

// RedeemedAtLTE applies the LTE predicate on the "redeemed_at" field.
func RedeemedAtLTE(v time.Time) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldLTE(FieldRedeemedAt, v))
}

// MetadataJSONIsNil applies the IsNil predicate on the "metadata_json" field.
func MetadataJSONIsNil() predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldIsNull(FieldMetadataJSON))
}

// MetadataJSONNotNil applies the NotNil predicate on the "metadata_json" field.
func MetadataJSONNotNil() predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.FieldNotNull(FieldMetadataJSON))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.UserRedeemCodeRedemption) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.UserRedeemCodeRedemption) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.UserRedeemCodeRedemption) predicate.UserRedeemCodeRedemption {
	return predicate.UserRedeemCodeRedemption(sql.NotPredicates(p))
}
