/**
 * SRapi v0.1.0 query keys.
 * Centralised to avoid typos and to make targeted invalidation simple.
 */
export const queryKeys = {
  runtimeStatus: () => ["runtime-status"] as const,
  siteConfig: () => ["site-config"] as const,
  smokeStatus: (model?: string) => ["smoke-status", model ?? "default"] as const,
  currentUser: () => ["current-user"] as const,
  apiKeys: () => ["api-keys"] as const,
  apiKeyUsage: (id: string, days: number) => ["api-key-usage", id, days] as const,
  usageLogs: () => ["usage-logs"] as const,
  availableModels: () => ["available-models"] as const,
  providerAccounts: () => ["provider-accounts"] as const,
  schedulerDecisions: () => ["scheduler-decisions"] as const,
  slos: () => ["slos"] as const,
  me: {
    profile: () => ["me", "profile"] as const,
    totpStatus: () => ["me", "totp-status"] as const,
    balance: () => ["me", "balance"] as const,
    platformQuotas: () => ["me", "platform-quotas"] as const,
    orders: (params?: unknown) => ["me", "orders", params ?? {}] as const,
    order: (id: string) => ["me", "order", id] as const,
    billingHistory: (params?: unknown) => ["me", "billing-history", params ?? {}] as const,
    paymentMethods: () => ["me", "payment-methods"] as const,
    subscriptionPlans: () => ["public", "subscription-plans"] as const,
    subscriptions: () => ["me", "subscriptions"] as const,
    affiliate: () => ["me", "affiliate"] as const,
    affiliateInviteCodes: () => ["me", "affiliate-invite-codes"] as const,
    affiliateLedger: (params?: unknown) => ["me", "affiliate-ledger", params ?? {}] as const,
    announcements: () => ["me", "announcements"] as const,
    playgroundModels: () => ["me", "playground-models"] as const,
    availableModels: () => ["me", "available-models"] as const,
    notificationPreferences: () => ["me", "notification-preferences"] as const,
    notificationContacts: () => ["me", "notification-contacts"] as const,
    authIdentities: () => ["me", "auth-identities"] as const,
  },
  admin: {
    dashboardSnapshot: (params?: unknown) => ["admin", "dashboard-snapshot", params ?? {}] as const,
    schedulerOverview: () => ["admin", "scheduler", "overview"] as const,
    schedulerStrategies: () => ["admin", "scheduler", "strategies"] as const,
    opsOverview: (params?: unknown) => ["admin", "ops", "overview", params ?? {}] as const,
    opsThroughput: (params?: unknown) => ["admin", "ops", "throughput", params ?? {}] as const,
    opsErrorTrend: (params?: unknown) => ["admin", "ops", "error-trend", params ?? {}] as const,
    opsErrorDistribution: (params?: unknown) =>
      ["admin", "ops", "error-distribution", params ?? {}] as const,
    opsLatencyHistogram: (params?: unknown) =>
      ["admin", "ops", "latency-histogram", params ?? {}] as const,
    opsConcurrency: () => ["admin", "ops", "concurrency"] as const,
    opsLogs: (params?: unknown) => ["admin", "ops", "logs", params ?? {}] as const,
    opsAlerts: (params?: unknown) => ["admin", "ops", "alerts", params ?? {}] as const,
    opsSystemLogs: (params?: unknown) => ["admin", "ops", "system-logs", params ?? {}] as const,
    opsAlertEvents: (params?: unknown) => ["admin", "ops", "alert-events", params ?? {}] as const,
    opsRealtimeSlots: () => ["admin", "ops", "realtime-slots"] as const,
    opsSlos: () => ["admin", "ops", "slos"] as const,
    opsAlertRules: () => ["admin", "ops", "alert-rules"] as const,
    opsAlertSilences: () => ["admin", "ops", "alert-silences"] as const,
    users: (params?: unknown) => ["admin", "users", params ?? {}] as const,
    providers: (params?: unknown) => ["admin", "providers", params ?? {}] as const,
    models: (params?: unknown) => ["admin", "models", params ?? {}] as const,
    accounts: (params?: unknown) => ["admin", "accounts", params ?? {}] as const,
    accountsHealthSummary: () => ["admin", "accounts", "health-summary"] as const,
    accountHealth: (id: string) => ["admin", "accounts", id, "health"] as const,
    accountQuota: (id: string) => ["admin", "accounts", id, "quota"] as const,
    accountRpm: (id: string) => ["admin", "accounts", id, "rpm"] as const,
    accountProxyQuality: (id: string) => ["admin", "accounts", id, "proxy-quality"] as const,
    accountUsageWindows: (id: string) => ["admin", "accounts", id, "usage-windows"] as const,
    accountUsageToday: (id: string) => ["admin", "accounts", id, "usage-today"] as const,
    accountsUsageTodayBatch: (ids: string[]) =>
      ["admin", "accounts", "usage-today", "batch", ids] as const,
    accountUsageDaily: (id: string, days: number) =>
      ["admin", "accounts", id, "usage-daily", days] as const,
    proxies: (params?: unknown) => ["admin", "proxies", params ?? {}] as const,
    accountGroups: () => ["admin", "account-groups"] as const,
    accountGroupMembers: (groupId: string) =>
      ["admin", "account-groups", groupId, "members"] as const,
    usageLogs: (params?: unknown) => ["admin", "usage-logs", params ?? {}] as const,
    usageDaily: (params?: unknown) => ["admin", "usage-daily", params ?? {}] as const,
    usageAggregates: (dimension: string, params?: unknown) =>
      ["admin", "usage-aggregates", dimension, params ?? {}] as const,
    usageTrends: (params?: unknown) => ["admin", "usage-trends", params ?? {}] as const,
    usageErrorDistribution: (params?: unknown) =>
      ["admin", "usage-error-distribution", params ?? {}] as const,
    usageDistribution: (params?: unknown) =>
      ["admin", "usage-distribution", params ?? {}] as const,
    auditLogs: (params?: unknown) => ["admin", "audit-logs", params ?? {}] as const,
    errorLogs: (params?: unknown) => ["admin", "error-logs", params ?? {}] as const,
    errorLog: (id: string) => ["admin", "error-logs", id] as const,
    outboxEvents: (params?: unknown) => ["admin", "outbox-events", params ?? {}] as const,
    apiKeys: (params?: unknown) => ["admin", "api-keys", params ?? {}] as const,
    apiKeyUsage: (id: string, days: number) => ["admin", "api-key-usage", id, days] as const,
    billingLedger: (params?: unknown) => ["admin", "billing-ledger", params ?? {}] as const,
    affiliateInvites: (params?: unknown) => ["admin", "affiliates", "invites", params ?? {}] as const,
    affiliateRebates: (params?: unknown) => ["admin", "affiliates", "rebates", params ?? {}] as const,
    affiliateTransfers: (params?: unknown) =>
      ["admin", "affiliates", "transfers", params ?? {}] as const,
    affiliateWithdrawals: (params?: unknown) =>
      ["admin", "affiliates", "withdrawals", params ?? {}] as const,
    affiliateManualAdjustments: (params?: unknown) =>
      ["admin", "affiliates", "manual-adjustments", params ?? {}] as const,
    affiliateRules: (params?: unknown) => ["admin", "affiliates", "rules", params ?? {}] as const,
    paymentProviders: (params?: unknown) => ["admin", "payment-providers", params ?? {}] as const,
    paymentOrders: (params?: unknown) => ["admin", "payment-orders", params ?? {}] as const,
    paymentOrderAuditLogs: (id: string) => ["admin", "payment-orders", id, "audit-logs"] as const,
    paymentDashboard: (days?: number) => ["admin", "payment-dashboard", days ?? 30] as const,
    subscriptionPlans: (params?: unknown) =>
      ["admin", "subscription-plans", params ?? {}] as const,
    userSubscriptions: (params?: unknown) =>
      ["admin", "user-subscriptions", params ?? {}] as const,
    pricingRules: (params?: unknown) => ["admin", "pricing-rules", params ?? {}] as const,
    announcements: (params?: unknown) => ["admin", "announcements", params ?? {}] as const,
    announcementReads: (id: string) => ["admin", "announcement-reads", id] as const,
    redeemCodes: (params?: unknown) => ["admin", "redeem-codes", params ?? {}] as const,
    redeemStats: () => ["admin", "redeem-stats"] as const,
    promoCodes: (params?: unknown) => ["admin", "promo-codes", params ?? {}] as const,
    promoCodeUsages: (id: string) => ["admin", "promo-code-usages", id] as const,
    errorPassthroughRules: () => ["admin", "error-passthrough-rules"] as const,
    payloadRules: () => ["admin", "payload-rules"] as const,
    scheduledTestPlans: () => ["admin", "scheduled-test-plans"] as const,
    scheduledTestPlanRuns: (planId: string) =>
      ["admin", "scheduled-test-plans", planId, "runs"] as const,
    channelMonitors: () => ["admin", "channel-monitors"] as const,
    channelMonitorRuns: (id: string) => ["admin", "channel-monitor-runs", id] as const,
    channelMonitorTemplates: () => ["admin", "channel-monitor-templates"] as const,
    tlsProfiles: () => ["admin", "tls-profiles"] as const,
    roles: () => ["admin", "roles"] as const,
    permissionCatalog: () => ["admin", "permission-catalog"] as const,
    userAttributes: () => ["admin", "user-attributes"] as const,
    notificationEmailTemplates: () => ["admin", "notification-email-templates"] as const,
    accountsAvailability: (days?: number) => ["admin", "accounts-availability", days ?? 7] as const,
    userPlatformQuotas: (userId: string) => ["admin", "user-platform-quotas", userId] as const,
    userAttributeValues: (userId: string) => ["admin", "user-attribute-values", userId] as const,
    userAttributeValuesBatch: (userIds: string[]) =>
      ["admin", "user-attribute-values", "batch", userIds] as const,
    usersSpendingTodayBatch: (userIds: string[]) =>
      ["admin", "users", "spending-today", "batch", userIds] as const,
    riskConfig: () => ["admin", "risk-config"] as const,
    riskStatus: () => ["admin", "risk-status"] as const,
    riskLogs: (params?: unknown) => ["admin", "risk-logs", params ?? {}] as const,
    contentSafetyConfig: () => ["admin", "content-safety-config"] as const,
    settings: () => ["admin", "settings"] as const,
    configSnapshot: () => ["admin", "config-snapshot"] as const,
    copilotConfig: () => ["admin", "copilot-config"] as const,
  },
};
