/**
 * SRapi v0.1.0 query keys.
 * Centralised to avoid typos and to make targeted invalidation simple.
 */
export const queryKeys = {
  runtimeStatus: () => ["runtime-status"] as const,
  smokeStatus: (model?: string) => ["smoke-status", model ?? "default"] as const,
  currentUser: () => ["current-user"] as const,
  apiKeys: () => ["api-keys"] as const,
  apiKeyUsage: (id: string, days: number) => ["api-key-usage", id, days] as const,
  usageLogs: () => ["usage-logs"] as const,
  providerAccounts: () => ["provider-accounts"] as const,
  schedulerDecisions: () => ["scheduler-decisions"] as const,
  slos: () => ["slos"] as const,
  me: {
    profile: () => ["me", "profile"] as const,
    totpStatus: () => ["me", "totp-status"] as const,
    balance: () => ["me", "balance"] as const,
    orders: (params?: unknown) => ["me", "orders", params ?? {}] as const,
    paymentMethods: () => ["me", "payment-methods"] as const,
    subscriptions: () => ["me", "subscriptions"] as const,
    affiliate: () => ["me", "affiliate"] as const,
    affiliateLedger: (params?: unknown) => ["me", "affiliate-ledger", params ?? {}] as const,
    announcements: () => ["me", "announcements"] as const,
    playgroundModels: () => ["me", "playground-models"] as const,
    notificationPreferences: () => ["me", "notification-preferences"] as const,
    notificationContacts: () => ["me", "notification-contacts"] as const,
    authIdentities: () => ["me", "auth-identities"] as const,
  },
  admin: {
    dashboardSnapshot: (params?: unknown) => ["admin", "dashboard-snapshot", params ?? {}] as const,
    opsOverview: (params?: unknown) => ["admin", "ops", "overview", params ?? {}] as const,
    opsThroughput: (params?: unknown) => ["admin", "ops", "throughput", params ?? {}] as const,
    opsErrorTrend: (params?: unknown) => ["admin", "ops", "error-trend", params ?? {}] as const,
    opsErrorDistribution: (params?: unknown) =>
      ["admin", "ops", "error-distribution", params ?? {}] as const,
    opsLatencyHistogram: (params?: unknown) =>
      ["admin", "ops", "latency-histogram", params ?? {}] as const,
    opsConcurrency: () => ["admin", "ops", "concurrency"] as const,
    opsLogs: (params?: unknown) => ["admin", "ops", "logs", params ?? {}] as const,
    opsAlerts: (params?: unknown) => ["admin", "ops", "alerts", params ?? {}] as const,
    opsAlertEvents: (params?: unknown) => ["admin", "ops", "alert-events", params ?? {}] as const,
    opsRealtimeSlots: () => ["admin", "ops", "realtime-slots"] as const,
    opsSlos: () => ["admin", "ops", "slos"] as const,
    opsAlertRules: () => ["admin", "ops", "alert-rules"] as const,
    opsAlertSilences: () => ["admin", "ops", "alert-silences"] as const,
    users: (params?: unknown) => ["admin", "users", params ?? {}] as const,
    providers: (params?: unknown) => ["admin", "providers", params ?? {}] as const,
    models: (params?: unknown) => ["admin", "models", params ?? {}] as const,
    accounts: (params?: unknown) => ["admin", "accounts", params ?? {}] as const,
    accountHealth: (id: string) => ["admin", "accounts", id, "health"] as const,
    accountQuota: (id: string) => ["admin", "accounts", id, "quota"] as const,
    accountRpm: (id: string) => ["admin", "accounts", id, "rpm"] as const,
    accountProxyQuality: (id: string) => ["admin", "accounts", id, "proxy-quality"] as const,
    proxies: (params?: unknown) => ["admin", "proxies", params ?? {}] as const,
    accountGroups: () => ["admin", "account-groups"] as const,
    accountGroupMembers: (groupId: string) =>
      ["admin", "account-groups", groupId, "members"] as const,
    usageLogs: (params?: unknown) => ["admin", "usage-logs", params ?? {}] as const,
    usageDaily: (params?: unknown) => ["admin", "usage-daily", params ?? {}] as const,
    usageAggregates: (dimension: string, params?: unknown) =>
      ["admin", "usage-aggregates", dimension, params ?? {}] as const,
    auditLogs: (params?: unknown) => ["admin", "audit-logs", params ?? {}] as const,
    outboxEvents: (params?: unknown) => ["admin", "outbox-events", params ?? {}] as const,
    apiKeys: (params?: unknown) => ["admin", "api-keys", params ?? {}] as const,
    apiKeyUsage: (id: string, days: number) => ["admin", "api-key-usage", id, days] as const,
    billingLedger: (params?: unknown) => ["admin", "billing-ledger", params ?? {}] as const,
    affiliateInvites: (params?: unknown) => ["admin", "affiliates", "invites", params ?? {}] as const,
    affiliateRebates: (params?: unknown) => ["admin", "affiliates", "rebates", params ?? {}] as const,
    affiliateTransfers: (params?: unknown) =>
      ["admin", "affiliates", "transfers", params ?? {}] as const,
    paymentProviders: (params?: unknown) => ["admin", "payment-providers", params ?? {}] as const,
    paymentOrders: (params?: unknown) => ["admin", "payment-orders", params ?? {}] as const,
    subscriptionPlans: (params?: unknown) =>
      ["admin", "subscription-plans", params ?? {}] as const,
    userSubscriptions: (params?: unknown) =>
      ["admin", "user-subscriptions", params ?? {}] as const,
    pricingRules: (params?: unknown) => ["admin", "pricing-rules", params ?? {}] as const,
    announcements: (params?: unknown) => ["admin", "announcements", params ?? {}] as const,
    redeemCodes: (params?: unknown) => ["admin", "redeem-codes", params ?? {}] as const,
    redeemStats: () => ["admin", "redeem-stats"] as const,
    promoCodes: (params?: unknown) => ["admin", "promo-codes", params ?? {}] as const,
    promoCodeUsages: (id: string) => ["admin", "promo-code-usages", id] as const,
    errorPassthroughRules: () => ["admin", "error-passthrough-rules"] as const,
    payloadRules: () => ["admin", "payload-rules"] as const,
    scheduledTestPlans: () => ["admin", "scheduled-test-plans"] as const,
    scheduledTestPlanRuns: (planId: string) =>
      ["admin", "scheduled-test-plans", planId, "runs"] as const,
    channelMonitors: () => ["admin", "channel-monitors"] as const,
    channelMonitorRuns: (id: string) => ["admin", "channel-monitor-runs", id] as const,
    channelMonitorTemplates: () => ["admin", "channel-monitor-templates"] as const,
    tlsProfiles: () => ["admin", "tls-profiles"] as const,
    roles: () => ["admin", "roles"] as const,
    userAttributes: () => ["admin", "user-attributes"] as const,
    notificationEmailTemplates: () => ["admin", "notification-email-templates"] as const,
    accountsAvailability: (days?: number) => ["admin", "accounts-availability", days ?? 7] as const,
    userPlatformQuotas: (userId: string) => ["admin", "user-platform-quotas", userId] as const,
    riskConfig: () => ["admin", "risk-config"] as const,
    riskStatus: () => ["admin", "risk-status"] as const,
    riskLogs: (params?: unknown) => ["admin", "risk-logs", params ?? {}] as const,
    settings: () => ["admin", "settings"] as const,
    configSnapshot: () => ["admin", "config-snapshot"] as const,
    copilotConfig: () => ["admin", "copilot-config"] as const,
  },
};
