export const ADMIN_HOME_ROUTE = "/admin/dashboard";
export const USER_HOME_ROUTE = "/dashboard";
export const SIGN_IN_ROUTE = "/";

/** User self-service route paths. */
export const USER_ROUTES = {
  account: "/account",
  billing: "/billing",
  redeem: "/redeem",
  affiliate: "/affiliate",
  playground: "/playground",
  availableChannels: "/available-channels",
} as const;

/** Canonical admin route paths, referenced by the sidebar nav + pages. */
export const ADMIN_ROUTES = {
  dashboard: "/admin/dashboard",
  users: "/admin/users",
  quickSetup: "/admin/quick-setup",
  providers: "/admin/providers",
  models: "/admin/models",
  accounts: "/admin/accounts",
  groups: "/admin/groups",
  proxies: "/admin/proxies",
  subscriptions: "/admin/subscriptions",
  orders: "/admin/orders",
  ordersPlans: "/admin/orders/plans",
  ordersDashboard: "/admin/orders/dashboard",
  channelsPricing: "/admin/channels/pricing",
  channelDetail: (id: string) => `/admin/channels/${encodeURIComponent(id)}`,
  channelsMonitor: "/admin/channels/monitor",
  paymentProviders: "/admin/payment-providers",
  promoCodes: "/admin/promo-codes",
  redeem: "/admin/redeem",
  affiliatesInvites: "/admin/affiliates/invites",
  affiliatesRebates: "/admin/affiliates/rebates",
  affiliatesTransfers: "/admin/affiliates/transfers",
  affiliatesRules: "/admin/affiliates/rules",
  announcements: "/admin/announcements",
  ops: "/admin/ops",
  opsStrategy: "/admin/ops?tab=strategy",
  opsChannelMonitor: "/admin/ops?tab=channel-monitor",
  opsScheduledTests: "/admin/ops?tab=scheduled-tests",
  opsSchedulerDecisions: "/admin/ops?tab=scheduler-decisions",
  eventsOutbox: "/admin/ops/events",
  riskControl: "/admin/risk-control",
  auditLogs: "/admin/audit-logs",
  billingLedger: "/admin/billing-ledger",
  errorPassthrough: "/admin/error-passthrough",
  tlsProfiles: "/admin/tls-profiles",
  payloadRules: "/admin/payload-rules",
  scheduledTests: "/admin/scheduled-tests",
  roles: "/admin/roles",
  apiKeys: "/admin/api-keys",
  userAttributes: "/admin/user-attributes",
  notificationTemplates: "/admin/notification-templates",
  usage: "/admin/usage",
  copilot: "/admin/copilot",
  settings: "/admin/settings",
} as const;

export const ADMIN_ROUTE_SMOKE_TARGETS = [
  { path: "/admin/dashboard", heading: "Admin Dashboard" },
  { path: "/admin/ops", heading: "Operations Center" },
  { path: "/admin/ops/strategy", heading: "Strategy Comparison" },
  { path: "/admin/users", heading: "User Management" },
  { path: "/admin/groups", heading: "Group Management" },
  { path: "/admin/subscriptions", heading: "Subscription Management" },
  { path: "/admin/accounts", heading: "Account Pool" },
  { path: "/admin/models", heading: "Model Registry" },
  { path: "/admin/announcements", heading: "Announcement Management" },
  { path: "/admin/proxies", heading: "Proxy Management" },
  { path: "/admin/risk-control", heading: "Risk Control" },
  { path: "/admin/audit-logs", heading: "Audit logs" },
  { path: "/admin/ops/events", heading: "Event outbox" },
  { path: "/admin/api-keys", heading: "API keys" },
  { path: "/admin/billing-ledger", heading: "Billing ledger" },
  { path: "/admin/error-passthrough", heading: "Error passthrough" },
  { path: "/admin/tls-profiles", heading: "TLS profiles" },
  { path: "/admin/payload-rules", heading: "Payload rules" },
  { path: "/admin/user-attributes", heading: "User attributes" },
  { path: "/admin/roles", heading: "Role Management" },
  { path: "/admin/notification-templates", heading: "Email templates" },
  { path: "/admin/redeem", heading: "Redeem Codes" },
  { path: "/admin/promo-codes", heading: "Promo Codes" },
  { path: "/admin/usage", heading: "Usage Records" },
  { path: "/admin/settings", heading: "System Settings" },
  { path: "/admin/channels/pricing", heading: "Channel Pricing" },
  { path: "/admin/channels/openai-compatible", heading: "Channel Detail" },
  { path: "/admin/channels/monitor", heading: "Channel Monitor" },
  { path: "/admin/affiliates/invites", heading: "Affiliate Invites" },
  { path: "/admin/affiliates/rebates", heading: "Affiliate Rebates" },
  { path: "/admin/affiliates/transfers", heading: "Affiliate Transfers" },
  { path: "/admin/affiliates/rules", heading: "Affiliate Rules" },
  { path: "/admin/orders/dashboard", heading: "Payment Dashboard" },
  { path: "/admin/orders", heading: "Orders" },
  { path: "/admin/orders/plans", heading: "Order Plans" },
] as const;

export function homeRouteForRole(role: "admin" | "user"): string {
  return role === "admin" ? ADMIN_HOME_ROUTE : USER_HOME_ROUTE;
}
