/**
 * Barrel re-export of the generated SDK domain types.
 *
 * Pages live at varying depths under src/app, which makes deep relative paths
 * into packages/sdk error-prone. Import SDK types from "@/lib/sdk-types"
 * instead — this file holds the single known-good relative path.
 */
export type {
  User,
  UserStatus,
  Provider,
  PlatformFamily,
  RuntimeClass,
  Model,
  ProviderAccount,
  AccountGroup,
  ProxyDefinition,
  SubscriptionPlan,
  UserSubscription,
  PaymentOrder,
  UsageLog,
  PromoCode,
  RedeemCode,
  AffiliateInviteRecord,
  AffiliateLedgerEntry,
  AuditLog,
  BillingLedgerEntry,
  DomainEventOutbox,
  ErrorPassthroughRule,
  PayloadRule,
  TlsProfile,
  Role,
  CreateRoleRequest,
  UpdateRoleRequest,
  ApiKey,
  ApiKeyStatus,
  UserAttributeDefinition,
  NotificationEmailTemplate,
  NotificationEmailTemplateList,
  NotificationEmailTemplateEvent,
  NotificationEmailTemplateEventName,
  AccountAvailabilitySummary,
  UserPlatformQuota,
  Announcement,
  UserAnnouncement,
  PricingRule,
  RiskControlLog,
  RiskControlStatus,
  SchedulerReplayResult,
  SchedulerStrategyName,
  OpsSloDefinition,
  OpsSettings,
  OpsSystemLogLevel,
  OpsSystemLogCleanupResult,
  ModelRateLimit,
  AccountGroupRateLimit,
  AdminTestResult,
  EnabledOAuthProvider,
  OAuthPendingSession,
  UpsertModelRateLimitRequest,
  UpsertGroupRateLimitRequest,
  NotificationPreference,
  NotificationContact,
  CurrentUserAuthIdentity,
} from "../../../../packages/sdk/typescript/src/types.gen";
